Repository unicef/etools, pull requests merged in 2018-03, with the labels that each got.

#1222 Add tests for currency consistency to partner detail testcases
  EquiTrack/partners/tests/test_api_partners.py
Labels: READY

#1201 pmp changes for hact
  EquiTrack/EquiTrack/factories.py
  EquiTrack/EquiTrack/fields.py
  EquiTrack/hact/management/commands/freeze_hact_data.py
  EquiTrack/hact/tests/test_models.py
  EquiTrack/hact/tests/test_views.py
  EquiTrack/partners/admin.py
  EquiTrack/partners/exports.py
  EquiTrack/partners/exports_v2.py
  EquiTrack/partners/migrations/0062_auto_20180226_2112.py
  EquiTrack/partners/migrations/0063_auto_20180226_2112.py
  EquiTrack/partners/migrations/0064_remove_partnerorganization_shared_partner.py
  EquiTrack/partners/migrations/0065_auto_20180228_1715.py
  EquiTrack/partners/models.py
  EquiTrack/partners/serializers/exports/interventions.py
  EquiTrack/partners/serializers/interventions_v2.py
  EquiTrack/partners/serializers/partner_organization_v2.py
  EquiTrack/partners/tests/test_api_pmp.py
  EquiTrack/partners/tests/test_export_intervention.py
  EquiTrack/partners/tests/test_export_partner.py
  EquiTrack/partners/tests/test_exports.py
  EquiTrack/partners/tests/test_forms.py
  EquiTrack/partners/tests/test_models.py
  EquiTrack/partners/tests/test_serializers.py
  EquiTrack/partners/tests/test_views.py
  EquiTrack/partners/urls_v2.py
  EquiTrack/partners/views/partner_organization_v2.py
  EquiTrack/templates/hact/dashboard.html
  EquiTrack/vision/adapters/partner.py
Labels: READY

#1220 celery: added json accept content
  EquiTrack/EquiTrack/settings/base.py
Labels: READY

#1224 Partner: added base_for_risk_rating
  EquiTrack/partners/migrations/0066_partnerorganization_basis_for_risk_rating.py
  EquiTrack/partners/models.py
  EquiTrack/partners/serializers/exports/partner_organization.py
  EquiTrack/partners/serializers/partner_organization_v2.py
  EquiTrack/partners/tests/test_export_partner.py
  EquiTrack/partners/tests/test_serializers.py
  EquiTrack/partners/tests/test_views.py
Labels: READY

#1223 tweak and fix partner synchronizer
  EquiTrack/users/admin.py
  EquiTrack/vision/adapters/partner.py
  EquiTrack/vision/tasks.py
  EquiTrack/vision/tests/test_tasks.py
Labels: WIP

#1206 New pd exports
  EquiTrack/EquiTrack/util_scripts.py
  EquiTrack/audit/views.py
  EquiTrack/partners/exports_v2.py
  EquiTrack/partners/serializers/exports/interventions.py
  EquiTrack/partners/tests/test_export_intervention.py
  EquiTrack/partners/tests/test_exports.py
  EquiTrack/reports/exports.py
  EquiTrack/reports/serializers/exports.py
  EquiTrack/reports/urls_v2.py
  EquiTrack/reports/views/v2.py
Labels: READY

#1228 fixed funding synchronizer
  EquiTrack/vision/adapters/funding.py
Labels: READY

#1226 fixed settings name (after celery 4 upgrade)
  EquiTrack/EquiTrack/settings/base.py
Labels: READY

#1209 Remove last package from the str/unicode meta-test
  EquiTrack/EquiTrack/tests/test_all_models.py
Labels: READY

#1227 Feature/flake8
  EquiTrack/EquiTrack/fields.py
  EquiTrack/audit/serializers/export.py
  EquiTrack/partners/serializers/interventions_v2.py
  EquiTrack/partners/tests/test_api_pmp.py
Labels: READY

#1229 fixed celery command
  EquiTrack/EquiTrack/management/commands/init-celery.py
Labels: READY

#1232 performance and fixed chart labels
  EquiTrack/hact/models.py
  EquiTrack/partners/serializers/partner_organization_v2.py
  EquiTrack/partners/tests/test_serializers.py
  EquiTrack/partners/views/partner_organization_v2.py
Labels: READY

#1211 MOU in past status transition changes
  EquiTrack/assets/partner/agreement_permissions.csv
  EquiTrack/partners/permissions.py
  EquiTrack/partners/tests/test_api_interventions.py
  EquiTrack/partners/tests/test_serializers.py
  EquiTrack/partners/validation/agreements.py
Labels: READY, changes-requested

#1238 Fund Reservation Header: fixed end date verbose name #4437
  EquiTrack/funds/migrations/0012_auto_20180307_1816.py
  EquiTrack/funds/models.py
Labels: READY

#1241 fixed PlannedEngagement spot_check_mr validation
  EquiTrack/partners/serializers/partner_organization_v2.py
Labels: changes-requested, today

#1237 added outstanding_findings to hact json
  EquiTrack/EquiTrack/management/commands/init-celery.py
  EquiTrack/EquiTrack/settings/base.py
  EquiTrack/hact/tasks.py
  EquiTrack/partners/exports_v2.py
  EquiTrack/partners/models.py
  EquiTrack/partners/serializers/partner_organization_v2.py
  EquiTrack/partners/tests/test_views.py
Labels: changes-requested, today

#1231 Add an extra validation to intervention amendments
  EquiTrack/partners/serializers/interventions_v2.py
  EquiTrack/partners/tests/test_api_interventions.py
Labels: READY, question

#1250 fixed update_hact_values encoding
  EquiTrack/hact/tasks.py
Labels: READY

#1254 Various tweaks
  EquiTrack/assets/partner/intervention_permissions.csv
  EquiTrack/partners/exports_v2.py
  EquiTrack/partners/models.py
  EquiTrack/partners/serializers/dashboards.py
  EquiTrack/partners/tests/test_models.py
  EquiTrack/partners/tests/test_tasks.py
  EquiTrack/partners/tests/test_validation_interventions.py
  EquiTrack/partners/validation/interventions.py
  EquiTrack/partners/views/dashboards.py
Labels: READY

#1262 RAMSynchronizer: skip record criteria
  EquiTrack/vision/adapters/programme.py
Labels: READY

#1261 Assessment serializer: added validation for completed_date #4547
  EquiTrack/partners/serializers/partner_organization_v2.py
Labels: READY

#1267 added vendor_number to PartnerHact serializer #4566
  EquiTrack/partners/serializers/partner_organization_v2.py
Labels: READY

#1168 Increase Reports test coverage
  EquiTrack/EquiTrack/urls.py
  EquiTrack/funds/tests/test_views.py
  EquiTrack/partners/tests/test_models.py
  EquiTrack/partners/tests/test_views.py
  EquiTrack/reports/tests/factories.py
  EquiTrack/reports/tests/test_models.py
  EquiTrack/reports/tests/test_serializers.py
  EquiTrack/reports/tests/test_views.py
  EquiTrack/reports/urls_v2.py
  EquiTrack/reports/views/v2.py
Labels: READY

#1188 Vision test coverage
  EquiTrack/vision/adapters/funding.py
  EquiTrack/vision/adapters/manual.py
  EquiTrack/vision/adapters/partner.py
  EquiTrack/vision/adapters/programme.py
  EquiTrack/vision/tests/test_adapter_funding.py
  EquiTrack/vision/tests/test_adapter_manual.py
  EquiTrack/vision/tests/test_adapter_partner.py
  EquiTrack/vision/tests/test_adapter_programme.py
  EquiTrack/vision/tests/test_adapter_publics.py
  EquiTrack/vision/tests/test_adapter_purchase_order.py
  EquiTrack/vision/tests/test_client.py
  EquiTrack/vision/tests/test_synchronizer.py
  EquiTrack/vision/tests/test_tasks.py
  EquiTrack/vision/tests/test_utils.py
  EquiTrack/vision/vision_data_synchronizer.py
Labels: READY

#1256 Add link to Country from vision log
  EquiTrack/users/templates/admin/users/country/change_form.html
  EquiTrack/vision/admin.py
  EquiTrack/vision/templates/admin/vision/vision_log/change_form.html
Labels: READY

#1263 Init Result Type command
  EquiTrack/reports/management/__init__.py
  EquiTrack/reports/management/commands/__init__.py
  EquiTrack/reports/management/commands/init-result-type.py
  EquiTrack/reports/tests/test_commands.py
Labels: READY

#1253 Always treat print as a function
  EquiTrack/partners/migrations/0014_auto_20170127_2140.py
  EquiTrack/partners/migrations/0027_auto_20170503_1430.py
  EquiTrack/partners/migrations/0038_auto_20170628_1808.py
  EquiTrack/partners/migrations/0039_auto_20170629_1447.py
  EquiTrack/partners/migrations/0042_auto_20170707_2036.py
  EquiTrack/partners/migrations/0043_auto_20170711_1610.py
  EquiTrack/partners/migrations/0045_auto_20170714_1738.py
  EquiTrack/partners/tests/test_api_prp.py
Labels: READY

#1264 Change assertItemsEqual for Python 3
  EquiTrack/audit/tests/test_transitions.py
  EquiTrack/audit/tests/test_views.py
  EquiTrack/funds/tests/test_api.py
  EquiTrack/notification/tests/test_email.py
  EquiTrack/partners/tests/test_api_interventions.py
  EquiTrack/partners/tests/test_models.py
  EquiTrack/partners/tests/test_serializers.py
  EquiTrack/partners/tests/test_views.py
  EquiTrack/t2f/tests/test_cost_summary_calculator.py
  EquiTrack/t2f/tests/test_travel_details.py
  EquiTrack/tpm/tests/test_views.py
  EquiTrack/users/tests/test_tasks.py
Labels: READY

#1266 Small Python3 changes
  EquiTrack/EquiTrack/tests/cases.py
  EquiTrack/attachments/tests/test_base64_file_field.py
  EquiTrack/attachments/tests/test_serializers.py
  EquiTrack/firms/utils.py
  EquiTrack/funds/tests/test_api.py
  EquiTrack/hact/tests/test_views.py
  EquiTrack/manage_debug.py
  EquiTrack/management/issues/checks.py
  EquiTrack/monitoring/tests/test_views.py
  EquiTrack/partners/models.py
  EquiTrack/partners/tests/test_export_agreement.py
  EquiTrack/partners/tests/test_export_intervention.py
  EquiTrack/partners/tests/test_export_partner.py
  EquiTrack/partners/tests/test_exports.py
  EquiTrack/partners/tests/test_views.py
  EquiTrack/partners/views/partner_organization_v2.py
  EquiTrack/reports/tests/test_views.py
  EquiTrack/snapshot/utils.py
  EquiTrack/t2f/management/commands/import_dsa.py
  EquiTrack/t2f/serializers/travel.py
  EquiTrack/t2f/tests/test_exports.py
  EquiTrack/t2f/tests/test_vision_export.py
  EquiTrack/users/serializers_v3.py
  EquiTrack/users/urls_v3.py
  EquiTrack/utils/common/routers.py
Labels: READY

#1259 Dictionary iteration methods changed in Python 3
  EquiTrack/EquiTrack/validation_mixins.py
  EquiTrack/users/tasks.py
  EquiTrack/vision/adapters/funding.py
  EquiTrack/vision/adapters/manual.py
Labels: READY

#1269 Correct one of the PCA contract paragraphs
  EquiTrack/templates/partners/pca/english_pdf.html
  EquiTrack/templates/partners/pca/french_pdf.html
  EquiTrack/templates/partners/pca/ifrc_english_pdf.html
  EquiTrack/templates/partners/pca/ifrc_french_pdf.html
  EquiTrack/templates/partners/pca/portuguese_pdf.html
  EquiTrack/templates/partners/pca/russian_pdf.html
  EquiTrack/templates/partners/pca/spanish_pdf.html
Labels: READY

#1265 Interventions in amendment should not be suspendable
  EquiTrack/partners/models.py
  EquiTrack/partners/tests/test_validation_interventions.py
  EquiTrack/partners/validation/interventions.py
Labels: READY

#1216 PCA start date: changed behavior #1932
  EquiTrack/partners/models.py
  EquiTrack/partners/tests/test_models.py
Labels: READY

#1255 Use b-prefix only when appropriate
  EquiTrack/attachments/migrations/0001_initial.py
  EquiTrack/attachments/tests/test_models.py
  EquiTrack/audit/tests/test_models.py
  EquiTrack/funds/migrations/0005_auto_20170912_2129.py
  EquiTrack/funds/tests/test_models.py
  EquiTrack/locations/migrations/0001_initial.py
  EquiTrack/locations/tests/test_models.py
  EquiTrack/management/migrations/0001_initial.py
  EquiTrack/management/migrations/0002_flaggedissue_issue_status.py
  EquiTrack/management/migrations/0003_auto_20170920_1157.py
  EquiTrack/notification/migrations/0001_initial.py
  EquiTrack/notification/tests/test_models.py
  EquiTrack/partners/migrations/0001_initial.py
  EquiTrack/partners/migrations/0005_auto_20161227_1953.py
  EquiTrack/partners/migrations/0006_auto_20170106_1356.py
  EquiTrack/partners/migrations/0007_auto_20170109_1840.py
  EquiTrack/partners/migrations/0008_auto_20170110_2245.py
  EquiTrack/partners/migrations/0014_auto_20170127_2140.py
  EquiTrack/partners/migrations/0015_auto_20170127_2140.py
  EquiTrack/partners/migrations/0019_auto_20170208_2158.py
  EquiTrack/partners/migrations/0023_auto_20170301_2324.py
  EquiTrack/partners/migrations/0024_auto_20170404_2041.py
  EquiTrack/partners/migrations/0028_auto_20170517_1516.py
  EquiTrack/partners/migrations/0029_auto_20170517_2017.py
  EquiTrack/partners/migrations/0062_auto_20180226_2112.py
  EquiTrack/partners/tests/test_models.py
  EquiTrack/publics/tests/test_models.py
  EquiTrack/reports/migrations/0001_initial.py
  EquiTrack/reports/migrations/0002_auto_20161209_2030.py
  EquiTrack/reports/migrations/0009_auto_20170623_1630.py
  EquiTrack/reports/tests/test_models.py
  EquiTrack/t2f/tests/test_models.py
  EquiTrack/trips/migrations/0001_initial.py
  EquiTrack/users/migrations/0001_initial.py
  EquiTrack/users/tests/test_models.py
  EquiTrack/workplan/migrations/0001_initial.py
Labels: READY

#1272 Attachments Endpoint
  EquiTrack/EquiTrack/urls.py
  EquiTrack/assets/partner/intervention_permissions.csv
  EquiTrack/attachments/admin.py
  EquiTrack/attachments/migrations/0005_auto_20180206_1700.py
  EquiTrack/attachments/models.py
  EquiTrack/attachments/serializers.py
  EquiTrack/attachments/serializers_fields.py
  EquiTrack/attachments/tests/factories.py
  EquiTrack/attachments/tests/test_base64_file_field.py
  EquiTrack/attachments/tests/test_modelchoice.py
  EquiTrack/attachments/tests/test_models.py
  EquiTrack/attachments/tests/test_serializers.py
  EquiTrack/attachments/tests/test_serializers_fields.py
  EquiTrack/attachments/tests/test_views.py
  EquiTrack/attachments/urls.py
  EquiTrack/attachments/views.py
  EquiTrack/audit/serializers/export.py
  EquiTrack/partners/management/commands/copy_attachments.py
  EquiTrack/partners/models.py
  EquiTrack/partners/permissions.py
  EquiTrack/partners/serializers/agreements_v2.py
  EquiTrack/partners/serializers/exports/interventions.py
  EquiTrack/partners/serializers/interventions_v2.py
  EquiTrack/partners/serializers/partner_organization_v2.py
  EquiTrack/partners/tasks.py
  EquiTrack/partners/tests/factories.py
  EquiTrack/partners/tests/test_api_interventions.py
  EquiTrack/partners/tests/test_api_pmp.py
  EquiTrack/partners/tests/test_commands.py
  EquiTrack/partners/tests/test_serializers.py
  EquiTrack/partners/tests/test_views.py
  EquiTrack/partners/utils.py
  EquiTrack/partners/views/v2.py
Labels: READY, has-migrations

#1257 Many things aren't lists in python 3
  EquiTrack/EquiTrack/parsers.py
  EquiTrack/audit/management/commands/update_audit_permissions.py
  EquiTrack/audit/serializers/risks.py
  EquiTrack/audit/tests/test_transitions.py
  EquiTrack/locations/tests/test_views.py
  EquiTrack/partners/tests/test_api_interventions.py
  EquiTrack/partners/tests/test_export_partner.py
  EquiTrack/partners/tests/test_exports.py
  EquiTrack/partners/tests/test_serializers.py
  EquiTrack/partners/tests/test_views.py
  EquiTrack/reports/tests/test_views.py
  EquiTrack/t2f/helpers/cost_summary_calculator.py
  EquiTrack/tpm/management/commands/update_tpm_permissions.py
  EquiTrack/tpm/models.py
  EquiTrack/tpm/tests/test_transitions.py
  EquiTrack/users/tasks.py
  EquiTrack/utils/permissions/metadata.py
  EquiTrack/utils/permissions/models/models.py
  EquiTrack/utils/permissions/serializers.py
Labels: READY

#1258 Exception.message is gone in Python3
  EquiTrack/hact/tasks.py
  EquiTrack/locations/tasks.py
  EquiTrack/partners/models.py
  EquiTrack/publics/migrations/0022_auto_20170514_1645.py
  EquiTrack/publics/tasks.py
  EquiTrack/t2f/models.py
  EquiTrack/t2f/vision.py
  EquiTrack/users/management/commands/add_country.py
  EquiTrack/users/models.py
  EquiTrack/users/serializers.py
  EquiTrack/users/tasks.py
  EquiTrack/vision/adapters/manual.py
  EquiTrack/vision/adapters/partner.py
  EquiTrack/vision/exceptions.py
  EquiTrack/vision/tasks.py
  EquiTrack/vision/tests/test_synchronizer.py
  EquiTrack/vision/tests/test_tasks.py
  EquiTrack/vision/vision_data_synchronizer.py
Labels: READY

#1274 str and unicode for Python 3 compatibility
  EquiTrack/EquiTrack/serializers.py
  EquiTrack/EquiTrack/settings/base.py
  EquiTrack/EquiTrack/tests/test_validation_mixins.py
  EquiTrack/EquiTrack/util_scripts.py
  EquiTrack/EquiTrack/validation_mixins.py
  EquiTrack/attachments/serializers_fields.py
  EquiTrack/audit/tests/test_models.py
  EquiTrack/environment/models.py
  EquiTrack/environment/tests/test_models.py
  EquiTrack/funds/serializer_exports.py
  EquiTrack/funds/tests/test_models.py
  EquiTrack/locations/forms.py
  EquiTrack/locations/tasks.py
  EquiTrack/locations/tests/test_models.py
  EquiTrack/management/issues/checks.py
  EquiTrack/management/models.py
  EquiTrack/management/tests/test_models.py
  EquiTrack/notification/models.py
  EquiTrack/notification/tests/test_models.py
  EquiTrack/partners/admin.py
  EquiTrack/partners/models.py
  EquiTrack/partners/serializers/exports/interventions.py
  EquiTrack/partners/serializers/partner_organization_v2.py
  EquiTrack/partners/tasks.py
  EquiTrack/partners/templatetags/userprofile_tags.py
  EquiTrack/partners/tests/test_api_dashboards.py
  EquiTrack/partners/tests/test_export_agreement.py
  EquiTrack/partners/tests/test_export_intervention.py
  EquiTrack/partners/tests/test_export_partner.py
  EquiTrack/partners/tests/test_exports.py
  EquiTrack/partners/tests/test_models.py
  EquiTrack/partners/tests/test_tasks.py
  EquiTrack/partners/tests/test_views.py
  EquiTrack/partners/validation/interventions.py
  EquiTrack/publics/tasks.py
  EquiTrack/publics/tests/test_models.py
  EquiTrack/reports/migrations/0015_auto_20180129_1921.py
  EquiTrack/reports/migrations/0017_indicators_p2.py
  EquiTrack/reports/serializers/exports.py
  EquiTrack/reports/tests/test_models.py
  EquiTrack/snapshot/models.py
  EquiTrack/snapshot/tests/test_models.py
  EquiTrack/snapshot/utils.py
  EquiTrack/t2f/management/commands/import_dsa.py
  EquiTrack/t2f/serializers/invoices.py
  EquiTrack/t2f/tests/test_dsa_calculations.py
  EquiTrack/t2f/tests/test_models.py
  EquiTrack/t2f/views/__init__.py
  EquiTrack/t2f/vision.py
  EquiTrack/trips/models.py
  EquiTrack/users/tasks.py
  EquiTrack/users/tests/test_models.py
  EquiTrack/users/tests/test_views.py
  EquiTrack/utils/permissions/tests/test_permission_serializers.py
  EquiTrack/vision/adapters/funding.py
  EquiTrack/vision/adapters/programme.py
  EquiTrack/vision/client.py
  EquiTrack/vision/tests/test_models.py
  EquiTrack/vision/tests/test_synchronizer.py
Labels: READY

#1247 Give models correct plural verbose names
  EquiTrack/audit/migrations/0031_auto_20180309_1210.py
  EquiTrack/audit/models.py
  EquiTrack/hact/migrations/0003_auto_20180309_1210.py
  EquiTrack/hact/models.py
  EquiTrack/partners/migrations/0067_auto_20180309_1210.py
  EquiTrack/partners/models.py
  EquiTrack/publics/migrations/0025_auto_20180309_1210.py
  EquiTrack/publics/models.py
  EquiTrack/t2f/migrations/0023_auto_20180309_1210.py
  EquiTrack/t2f/models.py
  EquiTrack/users/migrations/0011_auto_20180309_1210.py
  EquiTrack/users/models.py
  EquiTrack/utils/common/tests/models.py
  EquiTrack/utils/common/tests/test_utils.py
  EquiTrack/utils/writable_serializers/tests/models.py
Labels: READY, has-migrations

#1271 Intervention validation for cp structure
  EquiTrack/partners/admin.py
  EquiTrack/partners/tests/test_api_interventions.py
  EquiTrack/partners/tests/test_views.py
  EquiTrack/partners/urls_v2.py
  EquiTrack/partners/validation/agreements.py
  EquiTrack/partners/validation/interventions.py
  EquiTrack/partners/views/agreements_v2.py
  EquiTrack/partners/views/interventions_v2.py
Labels: READY

#1273 API Dropdown sorted alphabetically by value: 1880
  EquiTrack/EquiTrack/mixins.py
  EquiTrack/partners/tests/test_views.py
  EquiTrack/partners/views/agreements_v2.py
  EquiTrack/partners/views/interventions_v2.py
  EquiTrack/partners/views/partner_organization_v2.py
  EquiTrack/partners/views/v2.py
  EquiTrack/reports/views/v2.py
  EquiTrack/users/migrations/0012_auto_20180321_1830.py
  EquiTrack/users/models.py
Labels: WIP

#1280 Intervention export
  EquiTrack/partners/serializers/exports/interventions.py
  EquiTrack/partners/tests/test_export_intervention.py
  EquiTrack/partners/tests/test_exports.py
Labels: READY

#1282 Handle queryset lists in snapshot jsonify
  EquiTrack/snapshot/tests/test_utils.py
  EquiTrack/snapshot/utils.py
Labels: READY

#1281 Attachment data denormalized
  EquiTrack/attachments/migrations/0006_attachmentflat.py
  EquiTrack/attachments/models.py
  EquiTrack/attachments/serializers.py
  EquiTrack/attachments/tests/test_views.py
  EquiTrack/attachments/utils.py
  EquiTrack/attachments/views.py
  EquiTrack/partners/utils.py
Labels: READY, has-migrations

#1287 changed MR threshold
  EquiTrack/partners/models.py
Labels: READY

#1288 Update partner field size in attachment flat model
  EquiTrack/attachments/migrations/0007_auto_20180323_1240.py
  EquiTrack/attachments/migrations/0008_auto_20180323_1724.py
  EquiTrack/attachments/models.py
  EquiTrack/attachments/serializers.py
  EquiTrack/attachments/tests/test_views.py
Labels: READY, has-migrations

#1291 Add filename to attachments endpoint dataset
  EquiTrack/attachments/serializers.py
  EquiTrack/attachments/tests/test_views.py
Labels: READY

#1290 Show all cp outputs
  EquiTrack/reports/views/v2.py
  EquiTrack/requirements/base.txt
Labels: READY

#1295 fixed task
  EquiTrack/users/tasks.py
Labels: READY

#1191 azure integration
  EquiTrack/EquiTrack/settings/base.py
  EquiTrack/azure_graph_api/__init__.py
  EquiTrack/azure_graph_api/client.py
  EquiTrack/azure_graph_api/tasks.py
  EquiTrack/azure_graph_api/tests/__init__.py
  EquiTrack/azure_graph_api/tests/test_client.py
  EquiTrack/azure_graph_api/tests/test_tasks.py
  EquiTrack/azure_graph_api/tests/test_utils.py
  EquiTrack/azure_graph_api/utils.py
  EquiTrack/requirements/base.txt
  EquiTrack/setup.cfg
  EquiTrack/users/admin.py
  EquiTrack/users/tasks.py
  EquiTrack/users/templates/admin/users/country/change_form.html
  EquiTrack/users/templates/admin/users/user/change_form.html
  EquiTrack/vision/tasks.py
Labels: READY

#1301 Third party management updates
  EquiTrack/activities/models.py
  EquiTrack/tpm/export/renderers.py
  EquiTrack/tpm/export/serializers.py
  EquiTrack/tpm/views.py
Labels: READY, bug

#1304 [Auditor Portal] Engagement action points validation fix
  EquiTrack/audit/serializers/engagement.py
  EquiTrack/audit/tests/test_views.py
Labels: READY, bug
