Repository unicef/etools, pull requests merged in 2018-04, with the labels that each got.

#1305 Issue special audit attachment
  EquiTrack/attachments/serializers.py
  EquiTrack/attachments/views.py
  EquiTrack/audit/serializers/export.py
  EquiTrack/audit/tests/test_views.py
Labels: READY, bug

#1317 Fix dirty test
  EquiTrack/EquiTrack/tests/test_all_models.py
  EquiTrack/EquiTrack/tests/test_parsers.py
  EquiTrack/EquiTrack/tests/test_utils.py
  EquiTrack/EquiTrack/tests/test_validation_mixins.py
  EquiTrack/audit/tests/test_models.py
  EquiTrack/firms/tests/test_utils.py
  EquiTrack/funds/tests/test_api.py
  EquiTrack/locations/tests/test_models.py
  EquiTrack/management/tests/test_api.py
  EquiTrack/monitoring/tests/test_checks.py
  EquiTrack/partners/tests/test_api_agreements.py
  EquiTrack/partners/tests/test_api_interventions.py
  EquiTrack/partners/tests/test_api_partners.py
  EquiTrack/partners/tests/test_api_pmp.py
  EquiTrack/partners/tests/test_models.py
  EquiTrack/partners/tests/test_views.py
  EquiTrack/publics/tests/test_models.py
  EquiTrack/reports/tests/test_models.py
  EquiTrack/reports/tests/test_views.py
  EquiTrack/users/tests/test_models.py
  EquiTrack/vision/tests/test_client.py
  EquiTrack/vision/tests/test_models.py
  EquiTrack/vision/tests/test_tasks.py
  EquiTrack/vision/tests/test_utils.py
Labels: READY

#1319 Add country to flat exports
  EquiTrack/EquiTrack/mixins.py
  EquiTrack/funds/serializer_exports.py
  EquiTrack/partners/serializers/exports/agreements.py
  EquiTrack/partners/serializers/exports/interventions.py
  EquiTrack/partners/serializers/exports/partner_organization.py
  EquiTrack/partners/tests/test_export_partner.py
  EquiTrack/reports/serializers/exports.py
Labels: READY

#1318 Fix for swagger exception
  EquiTrack/partners/tests/test_api_interventions.py
  EquiTrack/partners/urls_v2.py
Labels: READY

#1310 Update azure graph api tests to work with --keepdb test flag
  EquiTrack/azure_graph_api/tests/test_utils.py
Labels: READY

#1308 Increase attachment api endpoint performance
  EquiTrack/attachments/migrations/0002_attachmentflat_filename.py
  EquiTrack/attachments/models.py
  EquiTrack/attachments/serializers.py
  EquiTrack/attachments/utils.py
Labels: READY, enhancement

#1309 Migrate Auditor portal & TPM email templates into update_notifications command.
  EquiTrack/EquiTrack/data/emails.json
  EquiTrack/audit/tests/test_email.py
  EquiTrack/audit/tests/test_transitions.py
  EquiTrack/audit/tests/test_views.py
  EquiTrack/notification/management/commands/update_notifications.py
  EquiTrack/tpm/tests/test_transitions.py
  EquiTrack/tpm/tests/test_views.py
  EquiTrack/utils/common/utils.py
Labels: READY, enhancement

#1306 Increase max-digits on fields to handle larger numbers
  EquiTrack/funds/migrations/0003_auto_20180329_1154.py
  EquiTrack/funds/models.py
  EquiTrack/funds/tests/test_models.py
  EquiTrack/partners/migrations/0003_auto_20180329_1155.py
  EquiTrack/partners/models.py
Labels: READY, bug, has-migrations

#1300 increased UserProfile maxlength
  EquiTrack/users/migrations/0002_auto_20180329_2123.py
  EquiTrack/users/models.py
Labels: READY, has-migrations

#1299 tpm 4 hact ch4859
  EquiTrack/EquiTrack/settings/local.py
  EquiTrack/hact/tasks.py
  EquiTrack/partners/models.py
  EquiTrack/partners/tests/test_models.py
  EquiTrack/tpm/models.py
Labels: READY

#1297 HACT fixes ch4940
  EquiTrack/hact/models.py
  EquiTrack/partners/exports_v2.py
Labels: READY

#1289 Run tests on both python2 and python3
  .circleci/config.yml
  .circleci/images/primary/Dockerfile
  EquiTrack/.coveragerc
  EquiTrack/.flake8
  EquiTrack/EquiTrack/utils.py
  EquiTrack/attachments/models.py
  EquiTrack/attachments/tests/factories.py
  EquiTrack/attachments/tests/test_models.py
  EquiTrack/attachments/tests/test_views.py
  EquiTrack/attachments/views.py
  EquiTrack/audit/tests/test_transitions.py
  EquiTrack/locations/migrations/0001_initial.py
  EquiTrack/locations/tests/test_models.py
  EquiTrack/locations/tests/test_views.py
  EquiTrack/management/views/reports.py
  EquiTrack/monitoring/views.py
  EquiTrack/notification/tests/test_models.py
  EquiTrack/partners/permissions.py
  EquiTrack/partners/tests/test_api_pmp.py
  EquiTrack/partners/tests/test_models.py
  EquiTrack/partners/tests/test_views.py
  EquiTrack/publics/tests/test_models.py
  EquiTrack/reports/tests/test_models.py
  EquiTrack/reports/tests/test_views.py
  EquiTrack/requirements/base.txt
  EquiTrack/runtests.sh
  EquiTrack/t2f/serializers/travel.py
  EquiTrack/t2f/tests/test_action_points.py
  EquiTrack/t2f/tests/test_exports.py
  EquiTrack/t2f/tests/test_models.py
  EquiTrack/t2f/tests/test_state_machine.py
  EquiTrack/t2f/tests/test_travel_details.py
  EquiTrack/t2f/tests/test_vision_export.py
  EquiTrack/t2f/vision.py
  EquiTrack/tox.ini
  EquiTrack/users/management/commands/add_country.py
  EquiTrack/users/migrations/0001_initial.py
  EquiTrack/users/tests/factories.py
  EquiTrack/users/tests/test_models.py
  EquiTrack/users/tests/test_tasks.py
  EquiTrack/utils/permissions/models/models.py
  EquiTrack/vision/adapters/funding.py
  EquiTrack/vision/adapters/partner.py
  EquiTrack/vision/adapters/programme.py
  EquiTrack/vision/adapters/purchase_order.py
  EquiTrack/vision/adapters/tpm_adapter.py
  EquiTrack/vision/client.py
  EquiTrack/vision/vision_data_converter.py
  EquiTrack/vision/vision_data_synchronizer.py
Labels: READY

#1279 Locations gis api
  EquiTrack/EquiTrack/urls.py
  EquiTrack/locations/tests/test_views.py
  EquiTrack/locations/views.py
  EquiTrack/management/serializers.py
  EquiTrack/management/tests/test_views.py
  EquiTrack/management/urls_gis.py
  EquiTrack/management/views/gis_v1.py
Labels: READY, changes-requested

#1210 Remove commented code
  EquiTrack/EquiTrack/utils.py
  EquiTrack/partners/admin.py
  EquiTrack/partners/exports_v2.py
  EquiTrack/partners/forms.py
  EquiTrack/partners/permissions.py
  EquiTrack/partners/serializers/interventions_v2.py
  EquiTrack/partners/templatetags/intervention_tags.py
  EquiTrack/partners/tests/test_api_interventions.py
  EquiTrack/partners/tests/test_models.py
  EquiTrack/partners/urls_v2.py
  EquiTrack/partners/validation/interventions.py
  EquiTrack/partners/views/partner_organization_v2.py
  EquiTrack/reports/admin.py
  EquiTrack/t2f/management/commands/_private.py
  EquiTrack/t2f/models.py
  EquiTrack/t2f/serializers/travel.py
  EquiTrack/t2f/tests/test_cost_summary_calculator.py
  EquiTrack/t2f/tests/test_threshold.py
  EquiTrack/t2f/views/travel.py
  EquiTrack/vision/adapters/programme.py
Labels: READY

#1203 Clean up EquiTrack.mixins
  EquiTrack/EquiTrack/auth.py
  EquiTrack/EquiTrack/middleware.py
  EquiTrack/EquiTrack/mixins.py
  EquiTrack/EquiTrack/settings/base.py
  EquiTrack/EquiTrack/settings/local.py
  EquiTrack/EquiTrack/settings/production.py
  EquiTrack/EquiTrack/tests/test_middleware.py
  EquiTrack/partners/admin.py
  EquiTrack/partners/migrations/0001_initial.py
  EquiTrack/partners/mixins.py
  EquiTrack/partners/models.py
  EquiTrack/partners/tests/test_models.py
Labels: READY

#1197 Notifications rework
  EquiTrack/EquiTrack/tests/cases.py
  EquiTrack/EquiTrack/tests/test_utils.py
  EquiTrack/EquiTrack/utils.py
  EquiTrack/audit/models.py
  EquiTrack/audit/purchase_order/models.py
  EquiTrack/audit/purchase_order/utils.py
  EquiTrack/audit/tests/base.py
  EquiTrack/email_auth/views.py
  EquiTrack/firms/tests/test_staff_member.py
  EquiTrack/firms/utils.py
  EquiTrack/notification/migrations/0002_auto_20180330_1347.py
  EquiTrack/notification/migrations/0003_create_email_templates.py
  EquiTrack/notification/models.py
  EquiTrack/notification/tests/test_email.py
  EquiTrack/notification/utils.py
  EquiTrack/partners/tasks.py
  EquiTrack/partners/tests/test_export_agreement.py
  EquiTrack/partners/tests/test_export_intervention.py
  EquiTrack/partners/tests/test_exports.py
  EquiTrack/partners/tests/test_tasks.py
  EquiTrack/snapshot/tests/test_models.py
  EquiTrack/t2f/models.py
  EquiTrack/t2f/vision.py
  EquiTrack/tpm/models.py
  EquiTrack/users/models.py
  EquiTrack/users/serializers_v3.py
  EquiTrack/users/tasks.py
  EquiTrack/users/tests/test_views.py
  EquiTrack/users/tests/test_views_v2.py
  EquiTrack/users/tests/test_views_v3.py
  EquiTrack/users/views.py
  EquiTrack/utils/mail/tests/test_loaders.py
Labels: READY

#1208 Make char and text fields not nullable where possible
  EquiTrack/EquiTrack/fields.py
  EquiTrack/EquiTrack/settings/base.py
  EquiTrack/attachments/migrations/0003_fix_null_values.py
  EquiTrack/attachments/migrations/0004_make_not_nullable.py
  EquiTrack/attachments/models.py
  EquiTrack/attachments/views.py
  EquiTrack/audit/migrations/0003_fix_null_values.py
  EquiTrack/audit/migrations/0004_make_not_nullable.py
  EquiTrack/audit/models.py
  EquiTrack/audit/purchase_order/migrations/0002_fix_null_values.py
  EquiTrack/audit/purchase_order/migrations/0003_make_not_nullable.py
  EquiTrack/firms/models.py
  EquiTrack/funds/migrations/0004_fix_null_values.py
  EquiTrack/funds/migrations/0005_make_not_nullable.py
  EquiTrack/funds/models.py
  EquiTrack/locations/migrations/0002_fix_null_values.py
  EquiTrack/locations/migrations/0003_make_not_nullable.py
  EquiTrack/locations/models.py
  EquiTrack/partners/migrations/0004_fix_null_values.py
  EquiTrack/partners/migrations/0005_make_not_nullable.py
  EquiTrack/partners/models.py
  EquiTrack/partners/serializers/dashboards.py
  EquiTrack/partners/serializers/exports/interventions.py
  EquiTrack/partners/serializers/interventions_v2.py
  EquiTrack/partners/serializers/prp_v1.py
  EquiTrack/partners/tests/data/prp-intervention-list.json
  EquiTrack/partners/tests/test_api_pmp.py
  EquiTrack/partners/tests/test_api_prp.py
  EquiTrack/partners/tests/test_models.py
  EquiTrack/partners/tests/test_views.py
  EquiTrack/partners/views/partner_organization_v2.py
  EquiTrack/partners/views/v1.py
  EquiTrack/publics/migrations/0002_fix_null_values.py
  EquiTrack/publics/migrations/0003_make_not_nullable.py
  EquiTrack/publics/models.py
  EquiTrack/publics/tests/factories.py
  EquiTrack/reports/migrations/0002_fix_null_values.py
  EquiTrack/reports/migrations/0003_make_not_nullable.py
  EquiTrack/reports/models.py
  EquiTrack/reports/tests/factories.py
  EquiTrack/reports/tests/test_models.py
  EquiTrack/t2f/migrations/0002_fix_null_values.py
  EquiTrack/t2f/migrations/0003_make_not_nullable.py
  EquiTrack/t2f/models.py
  EquiTrack/t2f/tests/test_action_points.py
  EquiTrack/t2f/tests/test_exports.py
  EquiTrack/tpm/tpmpartners/migrations/0002_auto_20180308_2137.py
  EquiTrack/users/migrations/0003_fix_null_values.py
  EquiTrack/users/migrations/0004_make_not_nullable.py
  EquiTrack/users/models.py
  EquiTrack/users/tests/test_tasks.py
  EquiTrack/utils/common/migrating.py
  EquiTrack/vision/adapters/partner.py
  EquiTrack/vision/migrations/0002_fix_null_values.py
  EquiTrack/vision/migrations/0003_make_not_nullable.py
  EquiTrack/vision/models.py
  EquiTrack/vision/tests/test_adapter_partner.py
  EquiTrack/vision/vision_data_synchronizer.py
  dev_environ_setup_linux.md
Labels: READY, has-migrations

#1314 fixed tasks in order to be compatible with import from future ch4980
  EquiTrack/hact/tasks.py
Labels: READY

#1334 Fix InterventionPartnershipDashView query
  EquiTrack/partners/serializers/dashboards.py
  EquiTrack/partners/views/dashboards.py
Labels: READY

#1337 first attempt to fix the 'build_and_test' circleci task
  .circleci/images/primary/Dockerfile
Labels: WIP, question

#1340 Location imports utf8 fix
  EquiTrack/locations/tasks.py
Labels: READY, question

#1338 Circleci build changes - cleaned up
  .circleci/images/primary/Dockerfile
Labels: READY

#1342 fix pd result export forgot to return ram indicators
  EquiTrack/reports/serializers/exports.py
Labels: READY

#1298 t2f 4 hact ch4598
  EquiTrack/partners/models.py
  EquiTrack/partners/tests/test_models.py
  EquiTrack/t2f/models.py
Labels: READY

#1324 Disaggregation create/update requests require pme permission
  EquiTrack/partners/permissions.py
  EquiTrack/reports/permissions.py
  EquiTrack/reports/tests/test_views.py
  EquiTrack/reports/views/v2.py
  EquiTrack/utils/permissions/utils.py
Labels: READY

#1316 Action points models
  .circleci/config.yml
  EquiTrack/EquiTrack/settings/base.py
  EquiTrack/action_points/__init__.py
  EquiTrack/action_points/admin.py
  EquiTrack/action_points/apps.py
  EquiTrack/action_points/conditions.py
  EquiTrack/action_points/migrations/0001_initial.py
  EquiTrack/action_points/migrations/__init__.py
  EquiTrack/action_points/models.py
  EquiTrack/action_points/signals.py
  EquiTrack/action_points/tests/__init__.py
  EquiTrack/action_points/tests/factories.py
  EquiTrack/action_points/tests/test_emails.py
  EquiTrack/action_points/tests/test_models.py
  EquiTrack/notification/management/commands/update_notifications.py
  EquiTrack/partners/tests/test_api_interventions.py
  EquiTrack/requirements/base.txt
  EquiTrack/requirements/input/base.in
  EquiTrack/requirements/local.txt
  EquiTrack/requirements/production.txt
  EquiTrack/requirements/test.txt
  EquiTrack/snapshot/utils.py
Labels: READY, feature, has-migrations

#1325 file loader
  EquiTrack/vision/adapters/partner.py
  EquiTrack/vision/tests/test_synchronizer.py
  EquiTrack/vision/vision_data_synchronizer.py
Labels: READY, enhancement

#1328 update init celery command
  EquiTrack/EquiTrack/management/commands/init-celery.py
Labels: READY

#1341 added filters for export ch4794
  EquiTrack/t2f/views/exports.py
Labels: READY

#1344 [ch5158] Fix production settings/cryptography with Python 3
  EquiTrack/EquiTrack/settings/production.py
Labels: READY

#1347 hact export: removed net_ct_cy [ch5167]
  EquiTrack/partners/exports_v2.py
  EquiTrack/partners/tests/test_export_partner.py
Labels: READY

#1352 Change from fabric to invoke
  EquiTrack/requirements/base.txt
  EquiTrack/requirements/input/local.in
  EquiTrack/requirements/local.txt
  EquiTrack/requirements/test.txt
  fabfile.py
  tasks.py
Labels: READY

#1339 Add is_high_frequency and is_active fields to AppliedIndicator
  EquiTrack/partners/serializers/interventions_v2.py
  EquiTrack/partners/serializers/prp_v1.py
  EquiTrack/partners/tests/data/prp-intervention-list.json
  EquiTrack/partners/tests/test_api_interventions.py
  EquiTrack/partners/tests/test_serializers_intervention.py
  EquiTrack/partners/urls_v2.py
  EquiTrack/partners/views/interventions_v2.py
  EquiTrack/reports/migrations/0004_auto_20180403_1309.py
  EquiTrack/reports/migrations/0005_reportingrequirement.py
  EquiTrack/reports/models.py
  EquiTrack/reports/serializers/v2.py
  EquiTrack/reports/tests/factories.py
  EquiTrack/reports/tests/test_serializers.py
  EquiTrack/reports/tests/test_views.py
Labels: READY, has-migrations

#1346 Remove django-smart-selects
  EquiTrack/EquiTrack/settings/base.py
  EquiTrack/EquiTrack/urls.py
  EquiTrack/partners/migrations/0002_auto_20180326_1605.py
  EquiTrack/partners/migrations/0006_auto_20180411_1702.py
  EquiTrack/partners/models.py
  EquiTrack/requirements/base.txt
  EquiTrack/requirements/input/base.in
  EquiTrack/requirements/local.txt
  EquiTrack/requirements/production.txt
  EquiTrack/requirements/test.txt
Labels: READY, has-migrations

#1348 Remove django allauth
  EquiTrack/EquiTrack/auth.py
  EquiTrack/EquiTrack/settings/base.py
  EquiTrack/EquiTrack/settings/local.py
  EquiTrack/EquiTrack/tests/test_all_models.py
  EquiTrack/EquiTrack/urls.py
  EquiTrack/requirements/base.txt
  EquiTrack/requirements/input/base.in
  EquiTrack/requirements/local.txt
  EquiTrack/requirements/production.txt
  EquiTrack/requirements/test.txt
  EquiTrack/templates/frontend/choose_login.html
Labels: READY

#1353 fix for py3 [ch5215]
  EquiTrack/partners/models.py
Labels: READY

#1355 t2f export filter: change filtername [ch4794]
  EquiTrack/t2f/views/exports.py
Labels: READY

#1356 file fund serializer [ch4894]
  EquiTrack/vision/adapters/funding.py
  EquiTrack/vision/vision_data_synchronizer.py
Labels: READY

#1358 fixed test warning [ch5222]
  EquiTrack/partners/models.py
  EquiTrack/partners/tests/test_api_prp.py
  EquiTrack/partners/tests/test_models.py
  EquiTrack/reports/tests/factories.py
  EquiTrack/snapshot/tests/test_views.py
  EquiTrack/snapshot/views.py
  EquiTrack/t2f/tests/test_exports.py
Labels: READY

#1354 fixed PartnerOrganizationAddView [ch5090]
  EquiTrack/partners/tests/test_api_partners.py
  EquiTrack/partners/tests/test_tasks.py
  EquiTrack/partners/views/partner_organization_v2.py
  EquiTrack/vision/adapters/partner.py
Labels: READY

#1360 Denormalize Tpm and Ap attachments
  EquiTrack/attachments/management/__init__.py
  EquiTrack/attachments/management/commands/__init__.py
  EquiTrack/attachments/management/commands/denormalize_attachments.py
  EquiTrack/attachments/tests/test_commands.py
  EquiTrack/attachments/tests/test_views.py
  EquiTrack/attachments/utils.py
Labels: READY

#1361 Feature/display expired cp outputs
  EquiTrack/partners/serializers/interventions_v2.py
  EquiTrack/partners/tests/test_views.py
Labels: READY

#1345 toward django 1.11 [ch396]
  EquiTrack/EquiTrack/settings/base.py
  EquiTrack/EquiTrack/settings/local.py
  EquiTrack/EquiTrack/urls.py
  EquiTrack/audit/urls.py
  EquiTrack/environment/urls_v2.py
  EquiTrack/funds/urls.py
  EquiTrack/hact/urls.py
  EquiTrack/partners/prp_urls.py
  EquiTrack/partners/urls_v2.py
  EquiTrack/partners/views/interventions_v2.py
  EquiTrack/publics/urls.py
  EquiTrack/snapshot/urls.py
  EquiTrack/users/tests/test_tasks.py
  EquiTrack/users/tests/test_views.py
  EquiTrack/users/urls.py
  EquiTrack/users/urls_v2.py
  EquiTrack/users/urls_v3.py
  EquiTrack/users/views.py
  EquiTrack/utils/common/urlresolvers.py
  EquiTrack/utils/writable_serializers/tests/models.py
Labels: READY

#1362 [ch4978] Fix exception in vision funding adapter
  EquiTrack/vision/adapters/funding.py
  EquiTrack/vision/tests/test_adapter_funding.py
Labels: READY

#1364 Validation Parser allow empty strings
  EquiTrack/EquiTrack/validation_mixins.py
Labels: READY

#1363 Test TPM activity attachments
  EquiTrack/attachments/serializers_fields.py
  EquiTrack/attachments/tests/test_serializers_fields.py
  EquiTrack/tpm/tests/test_views.py
Labels: READY

#1323 added basis for risk rating validation ch4887
  EquiTrack/partners/admin.py
  EquiTrack/partners/models.py
  EquiTrack/partners/serializers/partner_organization_v2.py
  EquiTrack/partners/tests/test_forms.py
  EquiTrack/partners/tests/test_views.py
  EquiTrack/vision/adapters/partner.py
Labels: changes-requested

#1369 make responsible_person nullable [ch5324]
  EquiTrack/funds/migrations/0007_auto_20180418_1830.py
  EquiTrack/funds/models.py
Labels: READY

#1388 Add multi currency flag to exports
  EquiTrack/partners/exports_v2.py
  EquiTrack/partners/serializers/exports/interventions.py
  EquiTrack/partners/tests/test_export_intervention.py
  EquiTrack/partners/tests/test_exports.py
Labels: READY

#1370 [ch5310] Add on_delete to FKs in action_points
  EquiTrack/action_points/models.py
Labels: READY

#1371 [ch5310] Add on_delete to FKs in activities
  EquiTrack/activities/models.py
Labels: READY

#1372 [ch5310] Add on_delete to FKs in attachments
  EquiTrack/attachments/models.py
Labels: READY

#1373 [ch5310] Add on_delete to FKs in audit
  EquiTrack/audit/models.py
  EquiTrack/audit/purchase_order/models.py
Labels: READY

#1374 [ch5310] Add on_delete to FKs in funds
  EquiTrack/funds/models.py
Labels: READY

#1375 [ch5310] Add on_delete to FKs in hact
  EquiTrack/hact/models.py
Labels: READY

#1376 [ch5310] Add on_delete to FKs in locations
  EquiTrack/locations/models.py
Labels: READY

#1377 [ch5310] Add on_delete to FKs in partners
  EquiTrack/partners/models.py
Labels: READY

#1378 [ch5310] Add on_delete to FKs in publics
  EquiTrack/publics/models.py
Labels: READY

#1379 [ch5310] Add on_delete to FKs in reports
  EquiTrack/reports/models.py
Labels: READY

#1381 [ch5310] Add on_delete to FKs in t2f
  EquiTrack/t2f/models.py
Labels: READY

#1382 [ch5310] Add on_delete to FKs in tpm
  EquiTrack/tpm/models.py
  EquiTrack/tpm/tpmpartners/models.py
Labels: READY

#1383 [ch5310] Add on_delete to FKs in users
  EquiTrack/users/models.py
Labels: READY

#1384 [ch5310] Add on_delete to FKs in utils
  EquiTrack/utils/common/tests/models.py
  EquiTrack/utils/permissions/tests/models.py
  EquiTrack/utils/writable_serializers/tests/models.py
Labels: READY

#1385 [ch5310] Add on_delete to FKs in vision
  EquiTrack/vision/models.py
Labels: READY

#1391 added on_delete on other relationship (tree, oneToOne) [ch5310]
  EquiTrack/firms/models.py
  EquiTrack/locations/models.py
  EquiTrack/partners/models.py
  EquiTrack/publics/models.py
  EquiTrack/t2f/models.py
  EquiTrack/users/models.py
Labels: READY

#1392 Azure Integration: improve filter for not Unicef users & migrations to Profile [ch4276]
  EquiTrack/azure_graph_api/tests/test_utils.py
  EquiTrack/users/migrations/0005_auto_20180419_2113.py
  EquiTrack/users/models.py
  EquiTrack/users/tasks.py
  EquiTrack/users/tests/test_tasks.py
Labels: READY

#1397 fix add partner
  EquiTrack/partners/views/partner_organization_v2.py
Labels: READY

#1396 Update Auditor portal libs
  EquiTrack/requirements/base.txt
  EquiTrack/requirements/input/base.in
  EquiTrack/requirements/local.txt
  EquiTrack/requirements/production.txt
  EquiTrack/requirements/test.txt
Labels: READY

#1399 Applied Indicator: means of verification nullable
  EquiTrack/partners/tests/data/prp-intervention-list.json
  EquiTrack/reports/migrations/0006_auto_20180423_1757.py
  EquiTrack/reports/models.py
Labels: READY

#1405 [ch5467] Make partners and reports fields nullable again
  EquiTrack/partners/migrations/0007_auto_20180424_1916.py
  EquiTrack/partners/models.py
  EquiTrack/reports/migrations/0007_auto_20180424_1845.py
  EquiTrack/reports/models.py
Labels: READY

#1411 Refactor user endpoint
  EquiTrack/users/tests/test_views.py
  EquiTrack/users/views.py
Labels: READY

#1403 new django urls [ch396]
  EquiTrack/EquiTrack/urls.py
  EquiTrack/email_auth/urls.py
  EquiTrack/hact/tests/test_views.py
  EquiTrack/publics/tests/test_dsa_rates.py
  EquiTrack/publics/tests/test_ghost_data.py
  EquiTrack/publics/tests/test_static_data_endpoints.py
  EquiTrack/publics/tests/test_wbs_grant_fund_endpoint.py
  EquiTrack/snapshot/tests/test_views.py
  EquiTrack/users/urls_v3.py
Labels: READY

#1409 t2f added filter for location [ch5381]
  EquiTrack/t2f/views/exports.py
Labels: READY

#1410 removed is authenticated warnings [ch396]
  EquiTrack/EquiTrack/middleware.py
  EquiTrack/environment/models.py
  EquiTrack/locations/views.py
  EquiTrack/partners/permissions.py
Labels: READY

#1400 users: staff id sync [ch4276]
  EquiTrack/users/migrations/0006_auto_20180423_1515.py
  EquiTrack/users/models.py
  EquiTrack/users/tasks.py
Labels: READY

#1326 update requirements part 1
  EquiTrack/EquiTrack/urls.py
  EquiTrack/reports/tests/test_models.py
  EquiTrack/reports/tests/test_serializers.py
  EquiTrack/reports/tests/test_views.py
  EquiTrack/requirements/base.txt
  EquiTrack/requirements/input/base.in
  EquiTrack/requirements/input/test.in
  EquiTrack/requirements/local.txt
  EquiTrack/requirements/production.txt
  EquiTrack/requirements/test.txt
  EquiTrack/tpm/apps.py
  EquiTrack/tpm/models.py
  EquiTrack/vision/tests/test_adapter_programme.py
Labels: READY

#1418 Remove disable behavior
  EquiTrack/users/tasks.py
Labels: READY

#1389 Third party management updates
  EquiTrack/notification/management/commands/update_notifications.py
  EquiTrack/tpm/admin.py
  EquiTrack/tpm/export/renderers.py
  EquiTrack/tpm/export/serializers.py
  EquiTrack/tpm/migrations/0002_tpmvisit_cancel_comment.py
  EquiTrack/tpm/models.py
  EquiTrack/tpm/serializers/visit.py
  EquiTrack/tpm/signals.py
  EquiTrack/tpm/tests/factories.py
  EquiTrack/tpm/tests/test_email.py
  EquiTrack/tpm/tests/test_models.py
  EquiTrack/tpm/tests/test_transitions.py
  EquiTrack/tpm/tests/test_views.py
  EquiTrack/tpm/tpmpartners/migrations/0003_tpmpartner_countries.py
  EquiTrack/tpm/tpmpartners/models.py
  EquiTrack/tpm/transitions/serializers.py
  EquiTrack/tpm/views.py
Labels: READY, has-migrations

#1421 fix hact task
  EquiTrack/hact/tasks.py
  EquiTrack/partners/models.py
Labels: READY

#1415 fixed admin partner readonly
  EquiTrack/partners/admin.py
Labels: READY

#1416 simple hact export view [ch5397]
  EquiTrack/partners/exports_v2.py
  EquiTrack/partners/urls_v2.py
  EquiTrack/partners/views/partner_organization_v2.py
Labels: READY
