Repository unicef/etools, pull requests merged in 2018-12, with the labels that each got.

#1999 [ch8116] export applied indicators
  src/etools/applications/reports/models.py
  src/etools/applications/reports/views/v2.py
Labels: READY

#1907 [Field monitoring][Step 1] Models & base api for settings
  src/etools/applications/EquiTrack/data/field_monitoring_methods.json
  src/etools/applications/field_monitoring/fm_settings/__init__.py
  src/etools/applications/field_monitoring/fm_settings/admin.py
  src/etools/applications/field_monitoring/fm_settings/apps.py
  src/etools/applications/field_monitoring/fm_settings/filters.py
  src/etools/applications/field_monitoring/fm_settings/migrations/0001_initial.py
  src/etools/applications/field_monitoring/fm_settings/migrations/__init__.py
  src/etools/applications/field_monitoring/fm_settings/models/__init__.py
  src/etools/applications/field_monitoring/fm_settings/models/cp_outputs.py
  src/etools/applications/field_monitoring/fm_settings/models/locations.py
  src/etools/applications/field_monitoring/fm_settings/models/methods.py
  src/etools/applications/field_monitoring/fm_settings/serializers/__init__.py
  src/etools/applications/field_monitoring/fm_settings/serializers/cp_outputs.py
  src/etools/applications/field_monitoring/fm_settings/serializers/methods.py
  src/etools/applications/field_monitoring/fm_settings/serializers/sites.py
  src/etools/applications/field_monitoring/fm_settings/tests/__init__.py
  src/etools/applications/field_monitoring/fm_settings/tests/factories.py
  src/etools/applications/field_monitoring/fm_settings/tests/test_models.py
  src/etools/applications/field_monitoring/fm_settings/tests/test_views.py
  src/etools/applications/field_monitoring/fm_settings/urls.py
  src/etools/applications/field_monitoring/fm_settings/views.py
  src/etools/applications/field_monitoring/groups.py
  src/etools/applications/field_monitoring/shared/__init__.py
  src/etools/applications/field_monitoring/shared/admin.py
  src/etools/applications/field_monitoring/shared/apps.py
  src/etools/applications/field_monitoring/shared/migrations/0001_initial.py
  src/etools/applications/field_monitoring/shared/migrations/__init__.py
  src/etools/applications/field_monitoring/shared/models.py
  src/etools/applications/field_monitoring/tests/__init__.py
  src/etools/applications/field_monitoring/tests/base.py
  src/etools/applications/field_monitoring/tests/factories.py
  src/etools/applications/field_monitoring/urls.py
  src/etools/applications/field_monitoring/views.py
  src/etools/applications/reports/tests/factories.py
  src/etools/config/settings/base.py
  src/etools/config/settings/local.py
  src/etools/config/urls.py
Labels: MERGE beginning next sprint, READY, has-migrations

#2008 [ch8116] pd result export fix
  src/etools/applications/reports/models.py
Labels: READY

#1993 Use correct file type for TPMAttachmentLinks
  src/etools/applications/tpm/serializers/attachments.py
  src/etools/applications/tpm/tests/test_views.py
Labels: READY

#2000 Add cso_type field to intervention export
  src/etools/applications/partners/serializers/exports/interventions.py
  src/etools/applications/partners/tests/test_export_intervention.py
Labels: READY

#1998 Update Partner Dashboard view queryset to handle filtering/searching
  src/etools/applications/partners/tests/test_views.py
  src/etools/applications/partners/views/partner_organization_v2.py
Labels: READY

#2002 [ch8797] hact dashboard: added outstanding previous year
  src/etools/applications/hact/models.py
  src/etools/applications/hact/tests/test_models.py
Labels: READY

#2003 [ch1907] new my dashboard
  src/etools/applications/partners/views/dashboards.py
Labels: READY

#2005 remove utf-8 declaration
  src/etools/applications/EquiTrack/checks.py
  src/etools/applications/audit/models.py
  src/etools/applications/funds/models.py
  src/etools/applications/funds/tests/test_models.py
  src/etools/applications/partners/models.py
  src/etools/applications/publics/management/commands/load_initial_data.py
  src/etools/applications/reports/models.py
  src/etools/applications/t2f/management/commands/et2f_init.py
  src/etools/applications/vision/migrations/0001_initial.py
  src/etools/libraries/locations/__init__.py
  src/etools/libraries/locations/tests/__init__.py
  src/etools/libraries/locations/views.py
  src/etools/libraries/tests/test_storages_azure.py
  src/etools/libraries/utils/test/api_checker.py
Labels: READY

#1994 Add filter on Special Condition PCA, and add to exports
  src/etools/applications/partners/exports_v2.py
  src/etools/applications/partners/serializers/agreements_v2.py
  src/etools/applications/partners/serializers/exports/agreements.py
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIAgreements/get__api_v2_agreements_.response.json
  src/etools/applications/partners/tests/test_api_agreements.py
  src/etools/applications/partners/tests/test_export_agreement.py
  src/etools/applications/partners/tests/test_exports.py
  src/etools/applications/partners/tests/test_views.py
  src/etools/applications/partners/views/agreements_v2.py
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/test.txt
Labels: READY

#2011 Update Dockerfile-dev to set REQUIREMENTS_FILE env var
  Dockerfile-dev
Labels: READY

#2013 [ch8791] freeze hact data fix
  src/etools/applications/hact/management/commands/freeze_hact_data.py
Labels: READY

#2015 1907 my dashboard enhancement
  src/etools/applications/partners/serializers/dashboards.py
Labels: READY

#2007 [ch8793] freeze hact charts
  src/etools/applications/hact/models.py
  src/etools/applications/hact/renderers.py
  src/etools/applications/hact/tests/test_models.py
  src/etools/applications/hact/urls.py
  src/etools/applications/hact/views.py
Labels: READY

#2019 Add partner_type field to partner dashboard payload
  src/etools/applications/partners/serializers/partner_organization_v2.py
Labels: READY

#2018 update etools version
  src/etools/__init__.py
Labels: READY

#2014 Attachment assessments
  src/etools/applications/partners/migrations/0030_assessment_active.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/tests/test_api_partners.py
  src/etools/applications/partners/tests/test_export_partner.py
  src/etools/applications/partners/tests/test_views.py
  src/etools/applications/partners/urls_v2.py
  src/etools/applications/partners/views/partner_organization_v2.py
Labels: READY, has-migrations

#2006 [ch8842] Filter exported TPM vendor list by user country
  src/etools/applications/tpm/views.py
Labels: READY

#2034 py3 super syntax - Publics app
  src/etools/applications/publics/admin.py
  src/etools/applications/publics/models.py
  src/etools/applications/publics/serializers.py
  src/etools/applications/publics/synchronizers.py
  src/etools/applications/publics/views.py
Labels: READY

#2036 py3 super syntax - libraries
  src/etools/libraries/azure_storage_backend.py
  src/etools/libraries/djangolib/models.py
  src/etools/libraries/monitoring/tests/test_views.py
Labels: READY

#2032 py3 super syntax - Partners app
  src/etools/applications/partners/forms.py
  src/etools/applications/partners/mixins.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/permissions.py
  src/etools/applications/partners/serializers/agreements_v2.py
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/serializers/partner_organization_v2.py
  src/etools/applications/partners/synchronizers.py
  src/etools/applications/partners/tests/test_admin.py
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/tests/test_api_partners.py
  src/etools/applications/partners/tests/test_api_pmp.py
  src/etools/applications/partners/tests/test_api_prp.py
  src/etools/applications/partners/tests/test_export_agreement.py
  src/etools/applications/partners/tests/test_export_intervention.py
  src/etools/applications/partners/tests/test_export_partner.py
  src/etools/applications/partners/tests/test_forms.py
  src/etools/applications/partners/tests/test_models.py
  src/etools/applications/partners/tests/test_tasks.py
  src/etools/applications/partners/tests/test_validation_interventions.py
  src/etools/applications/partners/tests/test_views.py
  src/etools/applications/partners/views/agreements_v2.py
  src/etools/applications/partners/views/interventions_v2.py
  src/etools/applications/partners/views/partner_organization_v2.py
  src/etools/applications/partners/views/prp_v1.py
  src/etools/applications/partners/views/v1.py
  src/etools/applications/partners/views/v2.py
Labels: READY

#2030 py3 super syntax - Firms app
  src/etools/applications/firms/serializers.py
Labels: READY

#2025 py3 super syntax - Action points app
  src/etools/applications/action_points/serializers.py
  src/etools/applications/action_points/tests/base.py
  src/etools/applications/action_points/tests/factories.py
  src/etools/applications/action_points/tests/test_transitions.py
  src/etools/applications/action_points/tests/test_views.py
  src/etools/applications/action_points/transitions/conditions.py
Labels: READY

#2024 py3 super syntax - Equitrack app
  src/etools/applications/EquiTrack/auth.py
  src/etools/applications/EquiTrack/mixins.py
  src/etools/applications/EquiTrack/serializers.py
  src/etools/applications/EquiTrack/tests/mixins.py
Labels: READY

#2027 py3 super syntax - Attachments app
  src/etools/applications/attachments/models.py
Labels: READY

#2029 py3 super syntax - Env app
  src/etools/applications/environment/models.py
Labels: READY

#2033 py3 super syntax - Permissions app
  src/etools/applications/permissions2/metadata.py
  src/etools/applications/permissions2/serializers.py
  src/etools/applications/permissions2/tests/mixins.py
  src/etools/applications/permissions2/views.py
Labels: READY

#2028 py3 super syntax - Audit app
  src/etools/applications/audit/exports.py
  src/etools/applications/audit/models.py
  src/etools/applications/audit/purchase_order/synchronizers.py
  src/etools/applications/audit/serializers/auditor.py
  src/etools/applications/audit/serializers/engagement.py
  src/etools/applications/audit/serializers/mixins.py
  src/etools/applications/audit/serializers/risks.py
  src/etools/applications/audit/tests/base.py
  src/etools/applications/audit/tests/test_email.py
  src/etools/applications/audit/tests/test_transitions.py
  src/etools/applications/audit/tests/test_views.py
  src/etools/applications/audit/transitions/conditions.py
  src/etools/applications/audit/views.py
Labels: READY

#2031 py3 super syntax - Funds app
  src/etools/applications/funds/models.py
  src/etools/applications/funds/synchronizers.py
  src/etools/applications/funds/tests/test_api.py
  src/etools/applications/funds/views.py
Labels: READY

#2026 py3 super syntax - Activitites app
  src/etools/applications/activities/serializers.py
Labels: READY

#2035 py3 super syntax - management app
  src/etools/applications/management/tests/test_issue_checks.py
  src/etools/applications/management/tests/test_issue_project_checks.py
  src/etools/applications/management/tests/test_models.py
  src/etools/applications/management/tests/test_views.py
Labels: READY

#2043 py3 super syntax - TPM app
  src/etools/applications/tpm/models.py
  src/etools/applications/tpm/serializers/attachments.py
  src/etools/applications/tpm/serializers/visit.py
  src/etools/applications/tpm/tests/factories.py
  src/etools/applications/tpm/tests/test_transitions.py
  src/etools/applications/tpm/tests/test_views.py
  src/etools/applications/tpm/tpmpartners/synchronizers.py
  src/etools/applications/tpm/views.py
Labels: READY

#2038 py3 super syntax - T2F app
  src/etools/applications/t2f/filters/travel_list.py
  src/etools/applications/t2f/helpers/permission_matrix.py
  src/etools/applications/t2f/html_views.py
  src/etools/applications/t2f/models.py
  src/etools/applications/t2f/serializers/__init__.py
  src/etools/applications/t2f/serializers/export.py
  src/etools/applications/t2f/serializers/filters/__init__.py
  src/etools/applications/t2f/serializers/filters/travel_list.py
  src/etools/applications/t2f/serializers/invoices.py
  src/etools/applications/t2f/serializers/travel.py
  src/etools/applications/t2f/tests/test_dsa_calculations.py
  src/etools/applications/t2f/tests/test_invoice_making.py
  src/etools/applications/t2f/tests/test_travel_details.py
  src/etools/applications/t2f/views/exports.py
  src/etools/applications/t2f/views/travel.py
Labels: READY

#2041 py3 super syntax - utils app
  src/etools/applications/utils/common/models/mixins.py
  src/etools/applications/utils/common/schemas.py
  src/etools/applications/utils/common/tests/factories.py
  src/etools/applications/utils/sentry/client.py
Labels: READY

#2021 Update prc review interview payload name to match what front end uses
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_amendments_.response.json
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/tests/test_export_intervention.py
Labels: READY

#2047 [ch9073] partner dashboard: fixed alert
  src/etools/applications/partners/views/partner_organization_v2.py
Labels: READY

#2055 [ch9073] dashboard alert fixes
  src/etools/applications/partners/views/partner_organization_v2.py
Labels: READY

#2059 PCA Special Condition export value Yes/No
  src/etools/applications/partners/exports_v2.py
  src/etools/applications/partners/serializers/exports/agreements.py
  src/etools/applications/partners/tests/test_export_agreement.py
  src/etools/applications/partners/tests/test_exports.py
Labels: READY

#2066 Change indicators amendment
  src/etools/applications/reports/serializers/v2.py
  src/etools/applications/reports/tests/test_serializers.py
Labels: READY

#2061 CSO type intervention export
  src/etools/applications/partners/exports_v2.py
  src/etools/applications/partners/tests/test_export_intervention.py
  src/etools/applications/partners/tests/test_exports.py
Labels: READY

#2067 [ch9073] partner dashboard: ignore Government parters
  src/etools/applications/partners/views/partner_organization_v2.py
Labels: READY

#1987 Simplified view-level permissions
  src/etools/applications/permissions2/views.py
  src/etools/applications/permissions_simplified/__init__.py
  src/etools/applications/permissions_simplified/metadata.py
  src/etools/applications/permissions_simplified/permissions.py
  src/etools/applications/permissions_simplified/readme.py
  src/etools/applications/permissions_simplified/serializers.py
  src/etools/applications/permissions_simplified/tests/__init__.py
  src/etools/applications/permissions_simplified/tests/factory.py
  src/etools/applications/permissions_simplified/tests/models.py
  src/etools/applications/permissions_simplified/tests/permissions.py
  src/etools/applications/permissions_simplified/tests/serializers.py
  src/etools/applications/permissions_simplified/tests/test_permissions.py
  src/etools/applications/permissions_simplified/tests/test_serializers.py
  src/etools/applications/permissions_simplified/tests/test_transitions.py
  src/etools/applications/permissions_simplified/tests/test_utils.py
  src/etools/applications/permissions_simplified/tests/test_views.py
  src/etools/applications/permissions_simplified/tests/urls.py
  src/etools/applications/permissions_simplified/tests/views.py
  src/etools/applications/permissions_simplified/views.py
  src/etools/config/settings/base.py
Labels: READY

#1986 [Field monitoring] Permissions for settings & planning (simplified)
  src/etools/applications/field_monitoring/fm_settings/serializers/attachments.py
  src/etools/applications/field_monitoring/fm_settings/serializers/cp_outputs.py
  src/etools/applications/field_monitoring/fm_settings/serializers/issues.py
  src/etools/applications/field_monitoring/fm_settings/serializers/locations.py
  src/etools/applications/field_monitoring/fm_settings/serializers/methods.py
  src/etools/applications/field_monitoring/fm_settings/tests/test_models.py
  src/etools/applications/field_monitoring/fm_settings/tests/test_views.py
  src/etools/applications/field_monitoring/fm_settings/views.py
  src/etools/applications/field_monitoring/metadata.py
  src/etools/applications/field_monitoring/permissions.py
  src/etools/applications/field_monitoring/planning/serializers.py
  src/etools/applications/field_monitoring/planning/tests/test_views.py
  src/etools/applications/field_monitoring/planning/views.py
  src/etools/applications/field_monitoring/tests/base.py
Labels: READY

#2049 Fix admin Partner export(remove work_plan, also address TODO)
  src/etools/applications/partners/exports.py
Labels: READY

#2069 hact charts: add tests
  src/etools/applications/hact/tests/test_models.py
Labels: READY

#2070 Update AppliedIndicatorSerializer test to be more robust
  src/etools/applications/reports/tests/test_serializers.py
Labels: READY

#2001 [ch8917] djangorestframework 39
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/publics/tests/test_ghost_data.py
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/test.txt
Labels: MERGE beginning next sprint, READY

#2062 flake
  .flake8
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/tests/test_api_prp.py
  src/etools/applications/permissions2/admin.py
  src/etools/applications/permissions2/drf_permissions.py
  src/etools/applications/permissions2/fsm.py
  src/etools/applications/permissions2/serializers.py
  src/etools/applications/permissions2/tests/test_external_context_serializers.py
  src/etools/applications/reports/serializers/v2.py
  src/etools/applications/tpm/views.py
  src/etools/applications/users/tests/test_admin.py
  src/etools/applications/utils/common/tests/models.py
  src/etools/applications/utils/common/tests/test_utils.py
  src/etools/applications/vision/client.py
  src/etools/libraries/azure_graph_api/tests/test_utils.py
  src/etools/libraries/locations/tests/test_tasks.py
  src/etools/libraries/tests/test_storages_azure.py
Labels: READY

#2010 [ch8880] permission2 fix
  src/etools/applications/audit/transitions/conditions.py
Labels: READY

#2075 t2f isort
  src/etools/applications/t2f/management/commands/et2f_init.py
  src/etools/applications/t2f/migrations/0002_fix_null_values.py
  src/etools/applications/t2f/tests/factories.py
  src/etools/applications/t2f/tests/test_exports.py
  src/etools/applications/t2f/tests/test_settings.py
  src/etools/applications/t2f/tests/test_state_machine.py
  src/etools/applications/t2f/tests/test_threshold.py
  src/etools/applications/t2f/tests/test_travel_details.py
  src/etools/applications/t2f/tests/test_travel_list.py
  src/etools/applications/t2f/views/__init__.py
  src/etools/applications/t2f/views/exports.py
Labels: READY

#2074 update etools version (6.7)
  src/etools/__init__.py
Labels: READY

#2077 cleaning t2f html views and vision integration
  src/etools/applications/t2f/html_views.py
  src/etools/applications/t2f/serializers/export.py
  src/etools/applications/t2f/templates/details.html
  src/etools/applications/t2f/tests/test_exports.py
  src/etools/applications/t2f/tests/test_invoice_making.py
  src/etools/applications/t2f/tests/test_travel_list.py
  src/etools/applications/t2f/tests/test_vision_export.py
  src/etools/applications/t2f/urls.py
  src/etools/applications/t2f/views/exports.py
  src/etools/applications/t2f/views/vision.py
  src/etools/applications/t2f/vision.py
Labels: READY

#2078 [ch9284] vision api change
  src/etools/applications/hact/models.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/serializers/partner_organization_v2.py
  src/etools/applications/partners/synchronizers.py
  src/etools/applications/partners/tests/test_models.py
Labels: READY

#2079 [ch9284] Hotfix/vision api change
  src/etools/__init__.py
  src/etools/applications/hact/models.py
  src/etools/applications/partners/mixins.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/serializers/partner_organization_v2.py
  src/etools/applications/partners/synchronizers.py
  src/etools/applications/partners/tests/test_models.py
Labels: READY

#2080 [ch9234] t2f simplify workflow
  src/etools/applications/t2f/helpers/misc.py
  src/etools/applications/t2f/management/commands/_private.py
  src/etools/applications/t2f/migrations/0009_auto_20181227_0815.py
  src/etools/applications/t2f/models.py
  src/etools/applications/t2f/serializers/travel.py
  src/etools/applications/t2f/serializers/user_data.py
  src/etools/applications/t2f/templates/emails/certificate_rejected.html
  src/etools/applications/t2f/templates/emails/certificate_submitted.html
  src/etools/applications/t2f/templates/emails/certified.html
  src/etools/applications/t2f/templates/emails/sent_for_payment.html
  src/etools/applications/t2f/tests/test_dashboard.py
  src/etools/applications/t2f/tests/test_mailing.py
  src/etools/applications/t2f/tests/test_overlapping_trips.py
  src/etools/applications/t2f/tests/test_permission_matrix.py
  src/etools/applications/t2f/tests/test_settings.py
  src/etools/applications/t2f/tests/test_state_machine.py
  src/etools/applications/t2f/tests/test_threshold.py
  src/etools/applications/t2f/tests/test_travel_details.py
  src/etools/applications/t2f/tests/test_travel_list.py
  src/etools/applications/t2f/tests/test_user_endpoint.py
  src/etools/applications/t2f/urls.py
  src/etools/applications/t2f/views/generics.py
  src/etools/applications/t2f/views/travel.py
  src/etools/config/settings/base.py
Labels: READY
