Repository unicef/etools, pull requests merged in 2018-05, with the labels that each got.

#1428 firms: fixed warnings
  EquiTrack/firms/models.py
  EquiTrack/firms/utils.py
Labels: READY

#1431 Fix copy attachments partner task
  EquiTrack/partners/tasks.py
  EquiTrack/partners/tests/test_tasks.py
Labels: READY

#1430 Auditor portal permissions hotfix
  EquiTrack/audit/management/commands/update_audit_permissions.py
  EquiTrack/audit/migrations/0007_auto_20180502_0938.py
  EquiTrack/audit/models.py
Labels: READY, bug

#1432 Move 'UNICEF Focal Point' and 'Office(s) of UNICEF Focal Point(s)' to the activity level
  EquiTrack/tpm/management/commands/update_tpm_permissions.py
  EquiTrack/tpm/migrations/0003_tpmactivity_unicef_focal_points.py
  EquiTrack/tpm/models.py
  EquiTrack/tpm/serializers/visit.py
  EquiTrack/tpm/tests/factories.py
  EquiTrack/tpm/tests/test_email.py
  EquiTrack/tpm/tests/test_transitions.py
  EquiTrack/tpm/tests/test_views.py
  EquiTrack/tpm/views.py
Labels: READY, feature

#1413 User model step1
  EquiTrack/partners/models.py
  EquiTrack/partners/tasks.py
  EquiTrack/partners/tests/test_tasks.py
  EquiTrack/partners/views/v2.py
  EquiTrack/t2f/models.py
  EquiTrack/t2f/serializers/travel.py
  EquiTrack/tpm/models.py
  EquiTrack/tpm/tests/test_models.py
  EquiTrack/users/migrations/0007_user.py
  EquiTrack/users/models.py
  EquiTrack/users/tasks.py
  EquiTrack/users/tests/test_tasks.py
  EquiTrack/users/tests/test_views.py
  EquiTrack/users/tests/test_views_v2.py
  EquiTrack/users/tests/test_views_v3.py
  EquiTrack/utils/permissions/tests/test_permission_serializers.py
Labels: READY, has-migrations

#1447 Auditor portal updates [Master]
  EquiTrack/attachments/serializers.py
  EquiTrack/audit/management/commands/update_audit_permissions.py
  EquiTrack/audit/serializers/engagement.py
  EquiTrack/audit/serializers/export.py
  EquiTrack/audit/templates/audit/audit_pdf.html
  EquiTrack/audit/templates/audit/engagement_pdf.html
  EquiTrack/audit/tests/test_views.py
  EquiTrack/audit/views.py
  EquiTrack/firms/models.py
  EquiTrack/notification/management/commands/update_notifications.py
  EquiTrack/tpm/export/serializers.py
  EquiTrack/utils/common/models/mixins.py
  EquiTrack/utils/common/serializers/fields.py
  EquiTrack/utils/common/views.py
Labels: READY, notifications update required

#1455 TPM & Auditor portal fixes [Staging]
  EquiTrack/audit/conditions.py
  EquiTrack/audit/management/commands/update_audit_permissions.py
  EquiTrack/audit/models.py
  EquiTrack/audit/tests/test_transitions.py
  EquiTrack/audit/transitions/conditions.py
  EquiTrack/audit/views.py
  EquiTrack/email_auth/forms.py
  EquiTrack/email_auth/templates/email_auth/login.html
  EquiTrack/email_auth/views.py
  EquiTrack/utils/common/urlresolvers.py
  EquiTrack/vision/adapters/manual.py
Labels: READY, bug, enhancement, permissions update required

#1453 TPM & Auditor portal fixes
  src/etools/applications/audit/conditions.py
  src/etools/applications/audit/management/commands/update_audit_permissions.py
  src/etools/applications/audit/models.py
  src/etools/applications/audit/tests/test_transitions.py
  src/etools/applications/audit/transitions/conditions.py
  src/etools/applications/audit/views.py
  src/etools/applications/email_auth/forms.py
  src/etools/applications/email_auth/templates/email_auth/login.html
  src/etools/applications/email_auth/views.py
  src/etools/applications/utils/common/urlresolvers.py
  src/etools/applications/vision/adapters/manual.py
Labels: READY, bug, enhancement, permissions update required

#1460 [ch5698] Add HACT update button to country page
  src/etools/applications/users/admin.py
  src/etools/applications/users/templates/admin/users/country/change_form.html
  src/etools/applications/users/tests/test_admin.py
Labels: READY

#1458 fixed tpm urls
  src/etools/applications/tpm/urls.py
Labels: READY

#1448 improved pmp report [ch5638]
  src/etools/applications/partners/tasks.py
  src/etools/applications/users/tasks.py
Labels: READY

#1412 HACT chart: assurance coverage [ch5391] [ch5390]
  src/etools/applications/EquiTrack/checks.py
  src/etools/applications/audit/conditions.py
  src/etools/applications/audit/models.py
  src/etools/applications/hact/models.py
  src/etools/applications/hact/tasks.py
  src/etools/applications/management/tasks.py
  src/etools/applications/management/tests/test_issue_checks.py
  src/etools/applications/management/tests/test_issue_project_checks.py
  src/etools/applications/management/urls.py
  src/etools/applications/management/views/tasks_endpoints.py
  src/etools/applications/partners/forms.py
  src/etools/applications/partners/migrations/0008_auto_20180509_1426.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/serializers/exports/interventions.py
  src/etools/applications/partners/tests/test_models.py
  src/etools/applications/partners/tests/test_views.py
  src/etools/applications/partners/urls_v2.py
  src/etools/applications/partners/views/interventions_v2.py
  src/etools/applications/partners/views/partner_organization_v2.py
  src/etools/applications/permissions2/utils.py
  src/etools/applications/vision/tests/test_tasks.py
Labels: READY

#1456 [ch5676] Update dev_environ_setup*.md to use Python 3
  dev_environ_setup.md
  dev_environ_setup_linux.md
Labels: READY

#1417 update requirements part 2
  src/etools/applications/attachments/models.py
  src/etools/config/settings/local.py
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/input/test.in
  src/requirements/local.txt
  src/requirements/production.txt
  src/requirements/test.txt
Labels: READY

#1462 removed migration
  src/etools/applications/partners/migrations/0008_auto_20180509_1426.py
Labels: READY

#1461 Update reporting requirements
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/tests/test_serializers_intervention.py
  src/etools/applications/partners/urls_v2.py
  src/etools/applications/partners/views/interventions_v2.py
Labels: READY

#1472 removed migration function
  src/etools/applications/users/migration_functions.py
Labels: READY

#1470 make InterventionPartnershipDashView filterable [ch5606]
  src/etools/applications/EquiTrack/mixins.py
  src/etools/applications/partners/views/dashboards.py
Labels: READY

#1468 update partner rating, added filter by rating [ch1884] [ch1879]
  src/etools/applications/partners/admin.py
  src/etools/applications/partners/migrations/0008_auto_20180510_1905.py
  src/etools/applications/partners/migrations/0009_auto_20180510_1940.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/views/partner_organization_v2.py
  src/etools/applications/utils/common/urlresolvers.py
  src/etools/applications/vision/adapters/partner.py
Labels: READY

#1483 [ch396] removed warnings django
  src/etools/applications/email_auth/utils.py
  src/etools/applications/partners/tests/test_api_agreements.py
  src/etools/applications/partners/tests/test_api_dashboards.py
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/tests/test_api_partners.py
  src/etools/applications/partners/tests/test_api_pmp.py
  src/etools/applications/partners/tests/test_api_prp.py
  src/etools/applications/partners/tests/test_export_agreement.py
  src/etools/applications/partners/tests/test_export_intervention.py
  src/etools/applications/partners/tests/test_export_partner.py
  src/etools/applications/partners/tests/test_models.py
  src/etools/applications/partners/tests/test_views.py
  src/etools/applications/t2f/vision.py
  src/etools/applications/users/admin.py
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/local.txt
  src/requirements/production.txt
  src/requirements/test.txt
Labels: READY

#1475 [ch5770] log hact periodic task
  src/etools/applications/hact/tasks.py
  src/etools/applications/hact/tests/test_tasks.py
  src/etools/applications/partners/tests/test_models.py
Labels: READY

#1484 Feature/fr donors , grants, locations
  src/etools/applications/EquiTrack/serializers.py
  src/etools/applications/funds/migrations/0008_fundsreservationitem_donor.py
  src/etools/applications/funds/migrations/0009_auto_20180515_1720.py
  src/etools/applications/funds/models.py
  src/etools/applications/funds/serializers.py
  src/etools/applications/funds/tests/factories.py
  src/etools/applications/funds/tests/test_api.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/vision/adapters/funding.py
  src/etools/applications/vision/tests/test_adapter_funding.py
Labels: READY, has-migrations

#1482 Special reporting requirements model
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/tests/test_serializers_intervention.py
  src/etools/applications/partners/views/interventions_v2.py
  src/etools/applications/reports/migrations/0008_auto_20180515_1744.py
  src/etools/applications/reports/models.py
  src/etools/applications/reports/serializers/v2.py
  src/etools/applications/reports/tests/factories.py
  src/etools/applications/reports/tests/test_views.py
  src/etools/applications/reports/urls_v2.py
  src/etools/applications/reports/views/v2.py
Labels: READY, has-migrations

#1486 fix admin tenant colors
  src/etools/applications/partners/templatetags/userprofile_tags.py
  src/etools/templates/admin/index.html
Labels: READY

#1485 [ch5458] added filter by year for monitoring visits
  src/etools/applications/t2f/views/travel.py
Labels: READY

#1471 Pca pdf templates - bank detail table changes
  src/etools/applications/partners/views/v1.py
  src/etools/templates/partners/pca/arabic_pdf.html
  src/etools/templates/partners/pca/english_pdf.html
  src/etools/templates/partners/pca/french_pdf.html
  src/etools/templates/partners/pca/ifrc_english_pdf.html
  src/etools/templates/partners/pca/ifrc_french_pdf.html
  src/etools/templates/partners/pca/portuguese_pdf.html
  src/etools/templates/partners/pca/russian_pdf.html
  src/etools/templates/partners/pca/spanish_pdf.html
Labels: READY

#1459 [ch5701] Fix datetime warnings in tests
  src/etools/applications/partners/utils.py
Labels: READY

#1473 [ch5667] create notification to be triggered when a partner is hidden during s…
  src/etools/applications/notification/management/commands/update_notifications.py
  src/etools/applications/notification/migrations/0004_auto_20180510_2030.py
  src/etools/applications/partners/tasks.py
  src/etools/applications/users/templates/admin/users/country/change_form.html
  src/etools/applications/vision/adapters/partner.py
Labels: READY

#1504 label fixed
  src/etools/applications/hact/models.py
Labels: READY

#1489 clean vision
  src/etools/applications/vision/adapters/funding.py
  src/etools/applications/vision/adapters/partner.py
  src/etools/applications/vision/adapters/programme.py
  src/etools/applications/vision/adapters/publics_adapter.py
  src/etools/applications/vision/client.py
  src/etools/applications/vision/exceptions.py
  src/etools/applications/vision/models.py
  src/etools/applications/vision/tests/test_adapter_partner.py
  src/etools/applications/vision/tests/test_adapter_programme.py
  src/etools/applications/vision/tests/test_client.py
  src/etools/applications/vision/tests/test_models.py
  src/etools/applications/vision/tests/test_synchronizer.py
  src/etools/applications/vision/tests/test_tasks.py
  src/etools/applications/vision/vision_data_synchronizer.py
  src/etools/config/settings/base.py
Labels: READY

#1496 docs: remove py3 preparation
  docs/guidelines.rst
Labels: READY

#1469 Hotfix carto query pagination for develop
  src/etools/applications/locations/tasks.py
  src/etools/applications/locations/tests/test_tasks.py
Labels: READY

#1503 Add grants list to the cached pmp data on the frontend
  src/etools/applications/partners/tests/test_api_pmp.py
  src/etools/applications/partners/views/v2.py
Labels: READY

#1478 New permissions for TPM
  src/etools/applications/tpm/admin.py
  src/etools/applications/tpm/conditions.py
  src/etools/applications/tpm/management/commands/update_tpm_permissions.py
  src/etools/applications/tpm/metadata.py
  src/etools/applications/tpm/migrations/0004_delete_tpmpermission.py
  src/etools/applications/tpm/models.py
  src/etools/applications/tpm/permissions.py
  src/etools/applications/tpm/serializers/partner.py
  src/etools/applications/tpm/serializers/visit.py
  src/etools/applications/tpm/tests/base.py
  src/etools/applications/tpm/tests/test_transitions.py
  src/etools/applications/tpm/tests/test_views.py
  src/etools/applications/tpm/urls.py
  src/etools/applications/tpm/views.py
Labels: READY, enhancement, has-migrations, permissions update required

#1500 [Action Points Module] ActionPoint should be connected to Travel instead of TravelActivity
  src/etools/applications/action_points/migrations/0002_auto_20180518_0835.py
  src/etools/applications/action_points/models.py
  src/etools/applications/action_points/tests/test_models.py
Labels: READY, has-migrations

#1491 Update PartnerPlannedVisitsSerializer
  src/etools/applications/partners/serializers/partner_organization_v2.py
  src/etools/applications/partners/tests/test_api_partners.py
Labels: READY

#1498 Remove django-analytical
  src/etools/config/settings/base.py
  src/etools/templates/admin/base_site.html
  src/etools/templates/base.html
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/local.txt
  src/requirements/production.txt
  src/requirements/test.txt
Labels: READY

#1508 remove warning
  src/etools/applications/EquiTrack/middleware.py
Labels: READY

#1513 [ch5857] added endpoint for Partner Rating and fixed choice
  src/etools/applications/partners/migrations/0009_auto_20180510_1940.py
  src/etools/applications/partners/migrations/0011_auto_20180521_1552.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/tests/test_api_pmp.py
  src/etools/applications/partners/views/v2.py
Labels: READY

#1512 Remove django-autocomplete-light
  src/etools/applications/locations/tests/test_views.py
  src/etools/applications/locations/urls.py
  src/etools/applications/locations/views.py
  src/etools/applications/partners/admin.py
  src/etools/applications/partners/forms.py
  src/etools/config/settings/base.py
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/local.txt
  src/requirements/production.txt
  src/requirements/test.txt
Labels: READY

#1509 Remove django-hstore and drf-hstore
  .circleci/config.yml
  db/load_db_data.sh
  dev_environ_setup.md
  dev_environ_setup_linux.md
  src/etools/applications/EquiTrack/tests/runners.py
  src/etools/config/settings/base.py
  src/etools/templates/hstore_default_widget.html
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/local.txt
  src/requirements/production.txt
  src/requirements/test.txt
Labels: READY

#1515 Third party management updates
  src/etools/applications/tpm/export/renderers.py
  src/etools/applications/tpm/export/serializers.py
  src/etools/applications/tpm/management/commands/update_tpm_permissions.py
  src/etools/applications/tpm/migrations/0005_tpmvisit_author.py
  src/etools/applications/tpm/models.py
  src/etools/applications/tpm/serializers/visit.py
  src/etools/applications/tpm/tests/factories.py
  src/etools/applications/tpm/tests/test_email.py
  src/etools/applications/tpm/tests/test_views.py
Labels: READY, has-migrations

#1517 Change special reporting requirements URL to include intervention ID
  src/etools/applications/reports/tests/test_views.py
  src/etools/applications/reports/urls_v2.py
  src/etools/applications/reports/views/v2.py
Labels: READY

#1523 A starting config for pyup.io
  .pyup.yml
Labels: READY

#1587 [ch5631] intervention with indicator export
  .isort.cfg
  src/etools/applications/partners/views/v2.py
  src/etools/applications/reports/urls_v2.py
  src/etools/applications/reports/views/v2.py
Labels: READY

#1592 added encoder
  src/etools/applications/EquiTrack/encoders.py
  src/etools/applications/hact/management/commands/freeze_hact_data.py
  src/etools/applications/hact/models.py
  src/etools/applications/hact/tasks.py
  src/etools/applications/partners/models.py
Labels: READY

#1605 Update hact values field to better handle obj in json format
  src/etools/applications/partners/serializers/fields.py
  src/etools/applications/partners/tests/test_export_partner.py
Labels: READY, bug
