Repository unicef/etools, pull requests merged in 2018-10, with the labels that each got.

#1878 [ch7616] tpm visits and engagments multiple select filter
  src/etools/applications/audit/filters.py
  src/etools/applications/audit/views.py
  src/etools/applications/tpm/views.py
Labels: READY

#1879 [ch7024] fixed staff spot checks
  src/etools/applications/hact/models.py
  src/etools/applications/hact/tests/test_models.py
  src/etools/applications/t2f/tests/test_travel_details.py
Labels: READY

#1849 [ch7567] allow to filter auditor staff member by workspace
  src/etools/applications/audit/purchase_order/admin.py
  src/etools/applications/audit/views.py
Labels: READY

#1866 Fix missing labels for cancel & reject visit popups
  src/etools/applications/tpm/management/commands/update_tpm_permissions.py
Labels: READY

#1882 [ch7557] update tpm permissions
  src/etools/applications/tpm/management/commands/update_tpm_permissions.py
Labels: READY

#1883 [ch7555] Restore Attachment Visit
  src/etools/applications/permissions2/drf_permissions.py
  src/etools/applications/tpm/management/commands/update_tpm_permissions.py
  src/etools/applications/tpm/migrations/0007_auto_20180926_1310.py
  src/etools/applications/tpm/models.py
  src/etools/applications/tpm/serializers/attachments.py
  src/etools/applications/tpm/tests/test_views.py
  src/etools/applications/tpm/urls.py
  src/etools/applications/tpm/views.py
Labels: READY

#1885 [ch7869] report refactoring, added fam report
  src/etools/applications/management/tasks.py
  src/etools/applications/management/templates/portal.html
  src/etools/applications/management/urls.py
  src/etools/applications/management/views/tasks_endpoints.py
  src/etools/applications/management/views/v1.py
  src/etools/applications/partners/tasks.py
  src/etools/applications/users/tasks.py
  src/etools/templates/admin/base_site.html
Labels: READY

#1884 little cleaning
  src/etools/applications/partners/tests/test_serializers_intervention.py
  src/etools/applications/partners/tests/test_views.py
Labels: READY

#1880 fixed AD logging
  src/etools/libraries/azure_graph_api/tasks.py
Labels: READY

#1863 [ch7345] IP Dashboard filters
  src/etools/applications/partners/views/partner_organization_v2.py
Labels: READY

#1858 [Ch6228] location remapping
  src/etools/applications/management/serializers.py
  src/etools/applications/management/tests/test_views.py
  src/etools/applications/management/urls_gis.py
  src/etools/applications/management/views/gis_v1.py
  src/etools/applications/partners/tests/test_export_intervention.py
  src/etools/config/urls.py
  src/etools/libraries/locations/admin.py
  src/etools/libraries/locations/task_utils.py
  src/etools/libraries/locations/tasks.py
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/test.txt
Labels: READY

#1887 [ch6228] Locations remap quickfixes
  src/etools/libraries/locations/admin.py
  src/etools/libraries/locations/task_utils.py
  src/etools/libraries/locations/tasks.py
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/test.txt
Labels: READY, question

#1896 Add vendor number to partner dashboard
  src/etools/applications/partners/serializers/partner_organization_v2.py
  src/etools/applications/partners/tests/test_views.py
Labels: READY

#1848 [ch7569] Deactivate only not unicef users
  src/etools/applications/audit/views.py
  src/etools/applications/tpm/signals.py
  src/etools/applications/users/models.py
  src/etools/applications/users/tests/test_models.py
Labels: READY

#1886 Update pd email notification
  src/etools/applications/partners/tasks.py
Labels: READY

#1888 [ch7673] country office permission update
  src/etools/applications/EquiTrack/data/groups.json
  src/etools/applications/vision/vision_data_synchronizer.py
Labels: READY

#1891 Update unicef-attachments requirement to 0.3.0
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/test.txt
Labels: READY

#1892 add 'status' filter to the location GIS API
  src/etools/applications/management/tests/test_views.py
  src/etools/applications/management/views/gis_v1.py
Labels: READY

#1894 [ch7550] changed TPM labels
  src/etools/applications/tpm/views.py
Labels: READY

#1900 [ch8127] sentry-staging-675475485: fixed admin filter
  src/etools/applications/audit/admin.py
Labels: READY

#1901 [ch7895] purchase order str method
  src/etools/applications/audit/purchase_order/models.py
Labels: READY

#1903 [ch7489] Engagement removed id from export
  src/etools/applications/audit/serializers/engagement.py
Labels: READY

#1902 [ch8162] old sdk: upgrade sentry
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/test.txt
Labels: READY

#1904 [ch7881] POSynchronizer_removed_donor_and_grant
  src/etools/applications/audit/purchase_order/synchronizers.py
  src/etools/applications/audit/purchase_order/tests/test_synchronizers.py
Labels: READY

#1909 Add TPM Activity endpoint to handling linking attachments
  src/etools/applications/attachments/tests/test_views.py
  src/etools/applications/tpm/serializers/attachments.py
  src/etools/applications/tpm/tests/test_views.py
  src/etools/applications/tpm/urls.py
  src/etools/applications/tpm/views.py
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/test.txt
Labels: READY

#1906 [#ch7804] Do not edit contingency flag in amendment
  src/etools/assets/partner/intervention_permissions.csv
Labels: READY

#1889 [ch7900] Dashboard: filter by cluster + cluster API
  src/etools/applications/partners/models.py
  src/etools/applications/partners/views/interventions_v2.py
  src/etools/applications/reports/serializers/v2.py
  src/etools/applications/reports/tests/test_views.py
  src/etools/applications/reports/urls_v2.py
  src/etools/applications/reports/views/v2.py
Labels: READY

#1895 More location remap quickfixes
  src/etools/libraries/locations/admin.py
  src/etools/libraries/locations/task_utils.py
  src/etools/libraries/locations/tasks.py
  src/etools/libraries/locations/tests/test_tasks.py
Labels: READY, changes-requested

#1917 SSFA Header not move to signed and add year to admin
  src/etools/applications/partners/admin.py
  src/etools/applications/partners/validation/agreements.py
Labels: READY

#1905 7841 changed PDF PCA filename
  src/etools/applications/partners/views/v1.py
Labels: READY

#1877 [ch7839] Intervention Admin: add activation letter
  src/etools/applications/partners/admin.py
Labels: READY

#1911 [ch8169] ip_dashboard pca required alert
  src/etools/applications/partners/views/partner_organization_v2.py
Labels: READY

#1920 [ch8114] fixed_applied_indicator_export
  src/etools/applications/reports/views/v2.py
Labels: READY

#1925 added etools version in the admin
  src/etools/__init__.py
  src/etools/applications/EquiTrack/templatetags/__init__.py
  src/etools/applications/EquiTrack/templatetags/etools.py
  src/etools/templates/admin/base_site.html
Labels: READY

#1923 [ch8232] tpm visit list view added full name to focal point
  src/etools/applications/firms/serializers.py
  src/etools/applications/users/models.py
Labels: READY

#1922 Audit/TPM filter tests
  src/etools/applications/audit/filters.py
  src/etools/applications/audit/tests/test_views.py
  src/etools/applications/audit/views.py
  src/etools/applications/tpm/filters.py
  src/etools/applications/tpm/tests/test_views.py
  src/etools/applications/tpm/views.py
Labels: READY

#1921 [ch7840] softdeletemixin allow force delete
  src/etools/applications/publics/models.py
Labels: READY
