Repository unicef/etools, pull requests merged in 2018-06, with the labels that each got.

#1618 Allow planned visit hact values to be set for government types
  src/etools/applications/partners/models.py
  src/etools/applications/partners/tests/test_models.py
Labels: READY

#1329 [ch6049] improvements for drf
  src/etools/applications/audit/views.py
  src/etools/applications/partners/serializers/exports/interventions.py
  src/etools/applications/publics/tests/test_static_data_endpoints.py
  src/etools/applications/t2f/migrations/0004_auto_20180524_1831.py
  src/etools/applications/t2f/models.py
  src/etools/applications/tpm/views.py
  src/etools/applications/users/serializers.py
  src/etools/applications/users/tests/factories.py
  src/etools/applications/utils/common/views.py
Labels: READY

#1610 changed MR calculation for Spot Check
  src/etools/applications/partners/models.py
  src/etools/applications/partners/tests/test_models.py
Labels: READY

#1614 [ch5607] Intervention Detail API added vendor number
  src/etools/applications/partners/serializers/interventions_v2.py
Labels: READY

#1616 [ch4244] Agreement Export: added vendor number
  src/etools/applications/partners/serializers/exports/agreements.py
  src/etools/applications/partners/tests/test_export_agreement.py
Labels: READY

#1613 [ch4233] tweak partner blocking
  src/etools/applications/partners/admin.py
  src/etools/applications/partners/migrations/0012_partnerorganization_manually_blocked.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/tests/test_export_partner.py
  src/etools/applications/partners/tests/test_serializers.py
  src/etools/applications/vision/adapters/partner.py
Labels: READY

#1124 Add filtering on funds reservations for grants and donors
  setup.py
  src/etools/applications/funds/tests/test_views.py
  src/etools/applications/funds/views.py
Labels: READY

#1615 Allow country to be overridden by get param
  src/etools/applications/EquiTrack/tests/test_utils.py
  src/etools/applications/EquiTrack/utils.py
  src/etools/config/settings/base.py
Labels: READY, feature

#1311 Moved validation to separate package/library
  src/etools/applications/EquiTrack/parsers.py
  src/etools/applications/EquiTrack/tests/test_parsers.py
  src/etools/applications/EquiTrack/tests/test_validation_mixins.py
  src/etools/applications/EquiTrack/validation_mixins.py
  src/etools/applications/partners/permissions.py
  src/etools/applications/partners/tests/test_validation_agreements.py
  src/etools/applications/partners/tests/test_validation_interventions.py
  src/etools/applications/partners/validation/agreements.py
  src/etools/applications/partners/validation/interventions.py
  src/etools/applications/partners/views/agreements_v2.py
  src/etools/applications/partners/views/interventions_v2.py
  src/etools/applications/partners/views/partner_organization_v2.py
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/input/local.in
  src/requirements/local.txt
  src/requirements/production.txt
  src/requirements/test.txt
  tasks.py
Labels: READY

#1414 User model step2
  src/etools/applications/EquiTrack/data/audit_users.json
  src/etools/applications/EquiTrack/data/users.json
  src/etools/applications/EquiTrack/tests/test_utils.py
  src/etools/applications/tpm/tpmpartners/migrations/0004_auto_20180503_1311.py
  src/etools/applications/users/admin.py
  src/etools/applications/users/migrations/0001_squashed_0007_user.py
  src/etools/applications/users/migrations/0002_auto_20180424_1740.py
  src/etools/applications/users/models.py
  src/etools/applications/utils/permissions/tests/test_permission_models.py
  src/etools/config/settings/base.py
Labels: READY, has-migrations

#1477 Action points serializers & api
  src/etools/applications/action_points/conditions.py
  src/etools/applications/action_points/filters.py
  src/etools/applications/action_points/management/__init__.py
  src/etools/applications/action_points/management/commands/__init__.py
  src/etools/applications/action_points/management/commands/update_action_points_permissions.py
  src/etools/applications/action_points/metadata.py
  src/etools/applications/action_points/migrations/0001_initial.py
  src/etools/applications/action_points/migrations/0003_auto_20180518_1610.py
  src/etools/applications/action_points/models.py
  src/etools/applications/action_points/serializers.py
  src/etools/applications/action_points/tests/base.py
  src/etools/applications/action_points/tests/factories.py
  src/etools/applications/action_points/tests/test_emails.py
  src/etools/applications/action_points/tests/test_models.py
  src/etools/applications/action_points/tests/test_transitions.py
  src/etools/applications/action_points/tests/test_views.py
  src/etools/applications/action_points/transitions/__init__.py
  src/etools/applications/action_points/transitions/conditions.py
  src/etools/applications/action_points/urls.py
  src/etools/applications/action_points/views.py
  src/etools/applications/audit/tests/factories.py
  src/etools/applications/management/tests/test_views.py
  src/etools/applications/notification/management/commands/update_notifications.py
  src/etools/applications/snapshot/models.py
  src/etools/applications/snapshot/serializers.py
  src/etools/applications/tpm/tests/factories.py
  src/etools/applications/tpm/tests/test_transitions.py
  src/etools/applications/users/tests/factories.py
  src/etools/applications/utils/common/tests/factories.py
  src/etools/applications/utils/groups/wrappers.py
  src/etools/applications/utils/permissions/tests/mixins.py
  src/etools/config/urls.py
Labels: READY, enhancement, has-migrations, permissions update required

#1620 [ch6025] fixed intervention export
  src/etools/applications/partners/views/interventions_v2.py
Labels: READY

#1621 [ch6104] [ch5397] Hact fixes
  src/etools/applications/hact/models.py
  src/etools/applications/partners/exports_v2.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/serializers/exports/partner_organization.py
  src/etools/applications/partners/tests/test_export_partner.py
  src/etools/applications/partners/tests/test_exports.py
Labels: READY

#1622 [ch5991] friendly CSV renderer
  src/etools/applications/EquiTrack/renderers.py
  src/etools/applications/partners/exports_v2.py
Labels: READY

#1623 Add agreement reference number to attachment api
  src/etools/applications/attachments/migrations/0005_attachmentflat_agreement_reference_number.py
  src/etools/applications/attachments/models.py
  src/etools/applications/attachments/tests/test_models.py
  src/etools/applications/attachments/tests/test_views.py
  src/etools/applications/attachments/utils.py
Labels: READY, has-migrations

#1624 update drf 3.6
  src/etools/applications/audit/views.py
  src/etools/applications/partners/serializers/exports/agreements.py
  src/etools/applications/partners/serializers/exports/interventions.py
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/publics/tests/test_static_data_endpoints.py
  src/etools/applications/reports/serializers/exports.py
  src/etools/applications/users/serializers_v3.py
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/local.txt
  src/requirements/production.txt
  src/requirements/test.txt
Labels: READY

#1629 [ch5861] fix notifications
  src/etools/applications/notification/utils.py
Labels: READY

#1631 [STAGING] [TPM] Action points changes to export & permissions
  src/etools/applications/tpm/export/renderers.py
  src/etools/applications/tpm/export/serializers.py
  src/etools/applications/tpm/management/commands/update_tpm_permissions.py
  src/etools/applications/tpm/models.py
Labels: READY, permissions update required

#1612 Tweak tokens
  src/etools/applications/audit/models.py
  src/etools/applications/email_auth/urls.py
  src/etools/applications/email_auth/views.py
  src/etools/applications/firms/utils.py
  src/etools/applications/tokens/__init__.py
  src/etools/applications/tokens/forms.py
  src/etools/applications/tokens/middleware.py
  src/etools/applications/tokens/templates/tokens/login.html
  src/etools/applications/tokens/tests/__init__.py
  src/etools/applications/tokens/tests/test_middleware.py
  src/etools/applications/tokens/tests/test_views.py
  src/etools/applications/tokens/urls.py
  src/etools/applications/tokens/utils.py
  src/etools/applications/tokens/views.py
  src/etools/applications/tpm/models.py
  src/etools/applications/utils/common/urlresolvers.py
  src/etools/config/settings/base.py
  src/etools/config/urls.py
Labels: READY, feature

#1642 fix 'createsuperuser' failing due to not asking for the 'email'
  src/etools/applications/users/models.py
Labels: READY

#1643 [ch6198] Spot check refactoring
  src/etools/applications/partners/admin.py
  src/etools/applications/partners/exports_v2.py
  src/etools/applications/partners/migrations/0013_auto_20180611_1823.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/serializers/partner_organization_v2.py
  src/etools/applications/partners/tests/test_models.py
  src/etools/applications/partners/tests/test_serializers.py
Labels: READY

#1644 Admin user form fix
  src/etools/applications/users/admin.py
Labels: READY

#1633 [ch5893] added Intervention Link to Partnership Export
  src/etools/applications/partners/exports_v2.py
  src/etools/applications/partners/serializers/dashboards.py
Labels: READY

#1645 Update etools validator requirement to 0.2.1
  src/etools/applications/partners/permissions.py
  src/etools/applications/partners/tests/test_validation_agreements.py
  src/etools/applications/partners/tests/test_validation_interventions.py
  src/etools/applications/partners/validation/agreements.py
  src/etools/applications/partners/validation/interventions.py
  src/etools/applications/partners/views/agreements_v2.py
  src/etools/applications/partners/views/interventions_v2.py
  src/etools/applications/partners/views/partner_organization_v2.py
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/local.txt
  src/requirements/production.txt
  src/requirements/test.txt
Labels: READY

#1636 Feature/removes custom django storarge package
  .gitignore
  src/etools/config/settings/production.py
  src/etools/libraries/azure_storage_backend.py
  src/etools/libraries/tests/test_storages_azure.py
  src/requirements/input/base.in
  src/requirements/local.txt
  src/requirements/production.txt
  src/requirements/test.txt
Labels: READY

#1635 [ch6198] HACT: generate hact every day and removed static methods
  src/etools/applications/audit/models.py
  src/etools/applications/hact/tasks.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/tests/test_models.py
  src/etools/applications/t2f/models.py
  src/etools/applications/vision/tasks.py
  src/etools/applications/vision/tests/test_tasks.py
Labels: READY

#1607 User Sync Refactoring
  src/etools/applications/users/tasks.py
  src/etools/applications/users/tests/test_tasks.py
Labels: WIP

#1637 [Auditor portal & TPM] New action points integration
  src/etools/applications/EquiTrack/data/audit_users.json
  src/etools/applications/action_points/export/__init__.py
  src/etools/applications/action_points/export/renderers.py
  src/etools/applications/action_points/export/serializers.py
  src/etools/applications/action_points/filters.py
  src/etools/applications/action_points/migrations/0004_auto_20180521_1052.py
  src/etools/applications/action_points/models.py
  src/etools/applications/action_points/tests/factories.py
  src/etools/applications/action_points/tests/test_models.py
  src/etools/applications/action_points/tests/test_views.py
  src/etools/applications/action_points/views.py
  src/etools/applications/audit/admin.py
  src/etools/applications/audit/management/commands/update_audit_permissions.py
  src/etools/applications/audit/migrations/0009_auto_20180521_1052.py
  src/etools/applications/audit/models.py
  src/etools/applications/audit/serializers/engagement.py
  src/etools/applications/audit/signals.py
  src/etools/applications/audit/tests/factories.py
  src/etools/applications/audit/tests/test_models.py
  src/etools/applications/audit/tests/test_views.py
  src/etools/applications/audit/urls.py
  src/etools/applications/audit/views.py
  src/etools/applications/notification/management/commands/update_notifications.py
  src/etools/applications/permissions2/drf_permissions.py
  src/etools/applications/permissions2/metadata.py
  src/etools/applications/permissions2/views.py
  src/etools/applications/tpm/admin.py
  src/etools/applications/tpm/export/serializers.py
  src/etools/applications/tpm/management/commands/update_tpm_permissions.py
  src/etools/applications/tpm/migrations/0006_auto_20180522_0736.py
  src/etools/applications/tpm/models.py
  src/etools/applications/tpm/serializers/visit.py
  src/etools/applications/tpm/signals.py
  src/etools/applications/tpm/tests/factories.py
  src/etools/applications/tpm/tests/test_views.py
  src/etools/applications/tpm/urls.py
  src/etools/applications/tpm/views.py
  src/etools/applications/utils/common/models/mixins.py
  src/etools/applications/utils/common/tests/test_utils.py
Labels: READY, has-migrations, permissions update required

#1641 [Audit / TPM / Action points] Add country code to reference number
  src/etools/applications/action_points/models.py
  src/etools/applications/action_points/tests/test_models.py
  src/etools/applications/audit/models.py
  src/etools/applications/tpm/models.py
Labels: READY

#1627 PMP indicators targets
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/reports/migrations/0009_auto_20180606_1807.py
  src/etools/applications/reports/migrations/0010_migrate_targets.py
  src/etools/applications/reports/models.py
  src/etools/applications/reports/serializers/v2.py
  src/etools/applications/reports/tests/test_views.py
Labels: READY

#1646 regenerate reqs
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/local.txt
  src/requirements/production.txt
  src/requirements/test.txt
Labels: READY

#1632 Fixes for location import errors & geojson support
  src/etools/applications/locations/models.py
  src/etools/applications/locations/serializers.py
  src/etools/applications/locations/tasks.py
  src/etools/applications/management/serializers.py
  src/etools/applications/management/tests/test_views.py
  src/etools/applications/management/views/gis_v1.py
  src/etools/config/settings/base.py
Labels: READY

#1611 Feature/api checker
  src/etools/applications/partners/models.py
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIAgreements/api_v2_agreements.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIAgreements/api_v2_agreements_5.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIAgreements/fixtures.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/api_v2_interventions.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/api_v2_interventions_101.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/api_v2_interventions_amendments.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/api_v2_interventions_indicators.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/api_v2_interventions_map.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/fixtures.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestPartners/api_v2_partners.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestPartners/api_v2_partners_101.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestPartners/fixtures.json
  src/etools/applications/partners/tests/test_api.py
  src/etools/libraries/utils/__init__.py
  src/etools/libraries/utils/test/__init__.py
  src/etools/libraries/utils/test/api_checker.py
  src/requirements/input/test.in
  src/requirements/test.txt
Labels: READY

#1639 Pd page notifications
  src/etools/applications/firms/tests/factories.py
  src/etools/applications/notification/management/commands/update_notifications.py
  src/etools/applications/partners/management/commands/send_pca_missing_notifications.py
  src/etools/applications/partners/management/commands/send_pca_required_notifications.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/tasks.py
  src/etools/applications/partners/tests/test_commands.py
  src/etools/applications/partners/tests/test_models.py
  src/etools/applications/partners/tests/test_tasks.py
  src/etools/applications/partners/tests/test_utils.py
  src/etools/applications/partners/utils.py
  src/etools/config/settings/base.py
Labels: READY

#1652 allow authentication to Carto API without an API key - staging
  src/etools/applications/locations/auth.py
  src/etools/applications/locations/forms.py
  src/etools/applications/locations/tasks.py
Labels: READY

#1648 [ch6250] Feature/fix dashboard
  src/etools/applications/partners/serializers/partner_organization_v2.py
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestPartners/api_v2_partners.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestPartners/api_v2_partners_101.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestPartners/fixtures.json
  src/etools/applications/partners/tests/test_serializers.py
Labels: READY

#1649 [ch6189] added filters for CSO Dashboard
  src/etools/applications/partners/views/dashboards.py
Labels: READY

#1650 [ch5988] fixed travel activity year filter
  src/etools/applications/t2f/views/travel.py
Labels: READY

#1654 [Audit] Engagements hact view fix
  src/etools/applications/audit/serializers/engagement.py
  src/etools/applications/audit/tests/test_views.py
  src/etools/applications/audit/views.py
Labels: READY

#1663 Auditor portal updates & fixes
  src/etools/applications/audit/management/commands/update_audit_permissions.py
  src/etools/applications/audit/serializers/engagement.py
  src/etools/applications/audit/serializers/export.py
  src/etools/applications/audit/templates/audit/engagement_pdf.html
  src/etools/applications/audit/tests/test_views.py
  src/etools/applications/utils/common/serializers/fields.py
Labels: READY, bug, enhancement, permissions update required

#1658 [Staging] [TPM] Upload attachments using multipart/form-data
  src/etools/applications/attachments/admin.py
  src/etools/applications/attachments/serializers.py
  src/etools/applications/attachments/tests/test_serializers.py
  src/etools/applications/attachments/utils.py
  src/etools/applications/permissions2/drf_permissions.py
  src/etools/applications/tpm/serializers/attachments.py
  src/etools/applications/tpm/serializers/partner.py
  src/etools/applications/tpm/serializers/visit.py
  src/etools/applications/tpm/tests/base.py
  src/etools/applications/tpm/tests/test_views.py
  src/etools/applications/tpm/urls.py
  src/etools/applications/tpm/views.py
  src/etools/applications/utils/common/views.py
Labels: READY

#1668 Add countryprogramme id to the agreement list
  src/etools/applications/partners/serializers/agreements_v2.py
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIAgreements/api_v2_agreements.response.json
Labels: READY

#1656 [Develop merge] [TPM] Upload attachments using multipart/form-data
  src/etools/applications/attachments/admin.py
  src/etools/applications/attachments/serializers.py
  src/etools/applications/attachments/tests/test_serializers.py
  src/etools/applications/attachments/utils.py
  src/etools/applications/permissions2/drf_permissions.py
  src/etools/applications/tpm/serializers/attachments.py
  src/etools/applications/tpm/serializers/partner.py
  src/etools/applications/tpm/serializers/visit.py
  src/etools/applications/tpm/tests/base.py
  src/etools/applications/tpm/tests/test_views.py
  src/etools/applications/tpm/urls.py
  src/etools/applications/tpm/views.py
  src/etools/applications/utils/common/views.py
Labels: READY

#1657 [Develop merge][Audit] Upload attachments using multipart/form-data
  src/etools/applications/action_points/views.py
  src/etools/applications/attachments/utils.py
  src/etools/applications/audit/models.py
  src/etools/applications/audit/serializers/engagement.py
  src/etools/applications/audit/tests/test_views.py
  src/etools/applications/audit/urls.py
  src/etools/applications/audit/views.py
  src/etools/applications/permissions2/views.py
  src/etools/applications/tpm/views.py
  src/etools/applications/utils/common/models/mixins.py
Labels: READY

#1659 [Audit/TPM] Using correct auth url in emails to staff members.
  src/etools/applications/EquiTrack/views.py
  src/etools/applications/action_points/models.py
  src/etools/applications/audit/models.py
  src/etools/applications/audit/purchase_order/models.py
  src/etools/applications/tpm/models.py
  src/etools/applications/utils/common/tests/test_utils.py
  src/etools/applications/utils/common/urlresolvers.py
Labels: READY

#1669 [Audit/TPM] Multipart attachments improvement
  src/etools/applications/attachments/serializers.py
  src/etools/applications/tpm/tests/test_models.py
Labels: READY

#1666 Fixed user sync
  src/etools/applications/users/tasks.py
  src/etools/applications/users/templates/admin/users/user/api.html
  src/etools/applications/users/urls_v3.py
  src/etools/applications/users/views.py
  src/etools/libraries/azure_graph_api/tasks.py
  src/etools/libraries/azure_graph_api/utils.py
Labels: READY

#1667 Audit & TPM fixes
  src/etools/applications/audit/serializers/engagement.py
  src/etools/applications/audit/tests/test_views.py
  src/etools/applications/audit/views.py
  src/etools/applications/tpm/tests/test_views.py
  src/etools/applications/tpm/views.py
  src/etools/applications/users/views.py
Labels: READY

#1675 add parent_id to the geojson output
  src/etools/applications/management/serializers.py
  src/etools/applications/management/tests/test_views.py
Labels: READY

#1671 [ch6320] changed hact date for travel spot checks
  src/etools/applications/partners/models.py
  src/etools/applications/partners/tests/test_models.py
  src/etools/applications/t2f/models.py
Labels: READY

#1665 Trips: fixed inconsistencies when filtering
  src/etools/applications/t2f/filters/travel_list.py
Labels: READY

#1679 DynamicChoicesField fix
  src/etools/applications/audit/serializers/export.py
  src/etools/applications/audit/serializers/risks.py
  src/etools/applications/utils/common/serializers/fields.py
  src/etools/applications/utils/common/utils.py
Labels: READY

#1681 fix locations on dash
  src/etools/applications/partners/models.py
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/views/interventions_v2.py
Labels: WIP

#1682 Remove encoding on azure url
  src/etools/libraries/azure_storage_backend.py
Labels: READY

#1690 [ch5397] fixed hact export
  src/etools/applications/partners/exports_v2.py
Labels: READY

#1692 [ch5397] fixed exports
  src/etools/applications/partners/exports_v2.py
  src/etools/applications/partners/views/partner_organization_v2.py
Labels: READY
