Repository unicef/etools, pull requests merged in 2018-08, with the labels that each got.

#1760 Move action points categories into public schema
  src/etools/applications/EquiTrack/data/action_points_categories.json
  src/etools/applications/action_points/admin.py
  src/etools/applications/action_points/categories/__init__.py
  src/etools/applications/action_points/categories/admin.py
  src/etools/applications/action_points/categories/apps.py
  src/etools/applications/action_points/categories/migrations/0001_initial.py
  src/etools/applications/action_points/categories/migrations/__init__.py
  src/etools/applications/action_points/categories/models.py
  src/etools/applications/action_points/categories/serializers.py
  src/etools/applications/action_points/migrations/0007_auto_20180731_0920.py
  src/etools/applications/action_points/migrations/0008_auto_20180731_1050.py
  src/etools/applications/action_points/models.py
  src/etools/applications/action_points/serializers.py
  src/etools/applications/action_points/tests/factories.py
  src/etools/applications/action_points/tests/test_views.py
  src/etools/applications/action_points/views.py
  src/etools/applications/audit/serializers/engagement.py
  src/etools/applications/reports/models.py
  src/etools/config/settings/base.py
Labels: READY

#1762 Fix action points csv export error for missing `reference_number` attribute in TravelActivity.
  src/etools/applications/action_points/tests/test_views.py
  src/etools/applications/t2f/models.py
Labels: READY

#1759 emails notifications for T2F AP
  src/etools/applications/action_points/models.py
  src/etools/applications/t2f/admin.py
  src/etools/applications/t2f/migrations/0007_t2factionpoint.py
  src/etools/applications/t2f/models.py
  src/etools/applications/t2f/notifications/travel_activity-action_point_assigned.py
  src/etools/applications/t2f/notifications/trip-action-created-updated-clased.py
Labels: READY

#1765 t2f notifications
  src/etools/applications/action_points/signals.py
  src/etools/applications/t2f/models.py
Labels: READY

#1771 Action point "Completed" not showing in "History"
  src/etools/applications/action_points/models.py
  src/etools/applications/action_points/tests/test_views.py
  src/etools/applications/action_points/views.py
  src/etools/applications/audit/models.py
  src/etools/applications/audit/tests/test_views.py
  src/etools/applications/audit/views.py
  src/etools/applications/snapshot/views.py
  src/etools/applications/tpm/models.py
  src/etools/applications/tpm/tests/test_views.py
  src/etools/applications/tpm/views.py
  src/etools/applications/utils/common/views.py
Labels: READY

#1755 Staff spot checks
  src/etools/applications/audit/purchase_order/admin.py
  src/etools/applications/audit/purchase_order/migrations/0006_auto_20180730_1121.py
  src/etools/applications/audit/purchase_order/models.py
  src/etools/applications/audit/serializers/engagement.py
  src/etools/applications/audit/tests/factories.py
  src/etools/applications/audit/tests/test_views.py
  src/etools/applications/audit/urls.py
  src/etools/applications/audit/views.py
  src/etools/applications/permissions2/conditions.py
  src/etools/applications/utils/common/views.py
Labels: READY

#1761 upgrade location library
  src/etools/libraries/locations/tests/test_views.py
  src/etools/libraries/locations/views.py
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/test.txt
Labels: READY

#1772 Filter action points within a period
  src/etools/applications/action_points/serializers.py
  src/etools/applications/action_points/views.py
Labels: READY

#1775 Handle None value set for attachment field
  src/etools/applications/attachments/serializers.py
  src/etools/applications/partners/migrations/0021_auto_20180801_1643.py
  src/etools/applications/partners/models.py
Labels: READY, has-migrations

#1778 [ch1511] agreement permissions changed for authorized_officers
  src/etools/applications/partners/permissions.py
  src/etools/assets/partner/agreement_permissions.csv
Labels: READY

#1779 [ch5968] fixed InterventionListMapView
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/views/interventions_v2.py
Labels: READY

#1677 [ch6630] upgrade DRF
  src/etools/applications/action_points/export/serializers.py
  src/etools/applications/action_points/tests/test_transitions.py
  src/etools/applications/action_points/tests/test_views.py
  src/etools/applications/action_points/views.py
  src/etools/applications/audit/serializers/export.py
  src/etools/applications/audit/serializers/risks.py
  src/etools/applications/audit/views.py
  src/etools/applications/partners/serializers/exports/agreements.py
  src/etools/applications/partners/serializers/exports/interventions.py
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/reports/serializers/exports.py
  src/etools/applications/reports/serializers/v2.py
  src/etools/applications/t2f/serializers/__init__.py
  src/etools/applications/t2f/serializers/export.py
  src/etools/applications/t2f/serializers/mailing.py
  src/etools/applications/tpm/tests/test_transitions.py
  src/etools/applications/tpm/tests/test_views.py
  src/etools/applications/tpm/views.py
  src/etools/applications/utils/common/inspectors.py
  src/etools/applications/utils/common/serializers/fields.py
  src/etools/applications/utils/common/utils.py
  src/etools/applications/utils/common/views.py
  src/etools/config/settings/base.py
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/test.txt
Labels: MERGE beginning next sprint, READY

#1728 Section Migration: part 4 [do not merge]
  src/etools/applications/action_points/migrations/0001_initial.py
  src/etools/applications/action_points/migrations/0003_auto_20180518_1610.py
  src/etools/applications/action_points/models.py
  src/etools/applications/partners/admin.py
  src/etools/applications/partners/migrations/0001_initial.py
  src/etools/applications/partners/migrations/0002_auto_20180326_1605.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/serializers/exports/interventions.py
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/tests/factories.py
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/tests/test_views.py
  src/etools/applications/partners/views/interventions_v2.py
  src/etools/applications/reports/admin.py
  src/etools/applications/reports/migrations/0001_initial.py
  src/etools/applications/reports/migrations/0002_fix_null_values.py
  src/etools/applications/reports/migrations/0003_make_not_nullable.py
  src/etools/applications/reports/migrations/0007_auto_20180424_1845.py
  src/etools/applications/reports/models.py
  src/etools/applications/reports/serializers/v1.py
  src/etools/applications/reports/tests/factories.py
  src/etools/applications/reports/views/v1.py
  src/etools/applications/t2f/migrations/0001_initial.py
  src/etools/applications/t2f/models.py
  src/etools/applications/t2f/serializers/static_data.py
  src/etools/applications/tpm/migrations/0001_initial.py
  src/etools/applications/tpm/models.py
  src/etools/applications/tpm/tests/factories.py
  src/etools/applications/tpm/views.py
Labels: MERGE beginning next sprint

#1786 [ch6931] added object_url to EngagementHactSerializer
  src/etools/applications/audit/serializers/engagement.py
Labels: READY

#1776 Remove snapshot app
  src/etools/applications/action_points/views.py
  src/etools/applications/snapshot/__init__.py
  src/etools/applications/snapshot/admin.py
  src/etools/applications/snapshot/migrations/0001_initial.py
  src/etools/applications/snapshot/migrations/0002_auto_20180626_1219.py
  src/etools/applications/snapshot/migrations/__init__.py
  src/etools/applications/snapshot/models.py
  src/etools/applications/snapshot/serializers.py
  src/etools/applications/snapshot/urls.py
  src/etools/applications/snapshot/utils.py
  src/etools/applications/snapshot/views.py
  src/etools/config/settings/base.py
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/test.txt
Labels: READY

#1787 fix tables references
  src/etools/applications/action_points/migrations/0001_initial.py
  src/etools/applications/action_points/migrations/0003_auto_20180518_1610.py
  src/etools/applications/action_points/models.py
  src/etools/applications/partners/migrations/0001_initial.py
  src/etools/applications/partners/migrations/0002_auto_20180326_1605.py
  src/etools/applications/partners/models.py
  src/etools/applications/reports/migrations/0001_initial.py
  src/etools/applications/reports/migrations/0002_fix_null_values.py
  src/etools/applications/reports/migrations/0003_make_not_nullable.py
  src/etools/applications/reports/migrations/0007_auto_20180424_1845.py
  src/etools/applications/reports/models.py
  src/etools/applications/t2f/migrations/0001_initial.py
  src/etools/applications/t2f/models.py
  src/etools/applications/tpm/migrations/0001_initial.py
  src/etools/applications/tpm/models.py
Labels: READY

#1790 Fixed user serializer (after drf update)
  src/etools/applications/users/serializers.py
Labels: READY

#1783 [ch6025] fixed InterventionList result filter
  src/etools/applications/partners/models.py
  src/etools/applications/partners/views/interventions_v2.py
Labels: READY

#1747 Add middle name to user model
  src/etools/applications/users/admin.py
  src/etools/applications/users/migrations/0005_user_middle_name.py
  src/etools/applications/users/models.py
  src/etools/applications/users/serializers.py
  src/etools/applications/users/serializers_v3.py
  src/etools/applications/users/tests/test_models.py
Labels: READY, has-migrations

#1793 Remove duplicate delete result link endpoint
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/urls_v2.py
  src/etools/applications/partners/views/interventions_v2.py
Labels: READY

#1777 Remove notification app
  src/etools/applications/action_points/models.py
  src/etools/applications/notification/__init__.py
  src/etools/applications/notification/migrations/0001_initial.py
  src/etools/applications/notification/migrations/0002_auto_20180330_1347.py
  src/etools/applications/notification/migrations/0003_create_email_templates.py
  src/etools/applications/notification/migrations/0004_auto_20180510_2030.py
  src/etools/applications/notification/migrations/0005_auto_20180628_1651.py
  src/etools/applications/notification/migrations/__init__.py
  src/etools/applications/notification/models.py
  src/etools/applications/notification/tests/__init__.py
  src/etools/applications/notification/tests/factories.py
  src/etools/applications/notification/tests/test_email.py
  src/etools/applications/notification/tests/test_models.py
  src/etools/applications/notification/utils.py
  src/etools/config/settings/base.py
Labels: READY

#1795 toward django 2.0 (remove warning)
  src/etools/applications/EquiTrack/tests/cases.py
  src/etools/applications/EquiTrack/tests/mixins.py
  src/etools/applications/EquiTrack/tests/test_middleware.py
  src/etools/applications/action_points/models.py
  src/etools/applications/action_points/tests/test_transitions.py
  src/etools/applications/action_points/tests/test_views.py
  src/etools/applications/attachments/tests/test_views.py
  src/etools/applications/environment/tests/test_views.py
  src/etools/applications/funds/tests/test_api.py
  src/etools/applications/funds/tests/test_views.py
  src/etools/applications/hact/tests/test_views.py
  src/etools/applications/management/tests/test_views.py
  src/etools/applications/partners/admin.py
  src/etools/applications/publics/tests/test_dsa_rates.py
  src/etools/applications/publics/tests/test_ghost_data.py
  src/etools/applications/publics/tests/test_static_data_endpoints.py
  src/etools/applications/publics/tests/test_wbs_grant_fund_endpoint.py
  src/etools/applications/reports/tests/test_serializers.py
  src/etools/applications/reports/tests/test_views.py
  src/etools/applications/t2f/tests/test_dashboard.py
  src/etools/applications/t2f/tests/test_exports.py
  src/etools/applications/t2f/tests/test_invoice_endpoints.py
  src/etools/applications/t2f/tests/test_invoice_making.py
  src/etools/applications/t2f/tests/test_overlapping_trips.py
  src/etools/applications/t2f/tests/test_permission_matrix.py
  src/etools/applications/t2f/tests/test_reference_number.py
  src/etools/applications/t2f/tests/test_settings.py
  src/etools/applications/t2f/tests/test_state_machine.py
  src/etools/applications/t2f/tests/test_static_data_endpoint.py
  src/etools/applications/t2f/tests/test_threshold.py
  src/etools/applications/t2f/tests/test_travel_details.py
  src/etools/applications/t2f/tests/test_travel_list.py
  src/etools/applications/t2f/tests/test_user_endpoint.py
  src/etools/applications/t2f/tests/test_vendor_numbers.py
  src/etools/applications/t2f/tests/test_vision_export.py
  src/etools/applications/tpm/tests/test_transitions.py
  src/etools/applications/tpm/tests/test_views.py
  src/etools/applications/users/tests/test_csrf.py
  src/etools/applications/users/tests/test_views.py
  src/etools/applications/users/tests/test_views_v2.py
  src/etools/applications/users/tests/test_views_v3.py
  src/etools/applications/utils/common/tests/test_utils.py
  src/etools/applications/utils/writable_serializers/tests/models.py
  src/etools/config/settings/base.py
  src/etools/libraries/locations/tests/test_views.py
  src/etools/libraries/monitoring/tests/test_views.py
Labels: READY

#1789 [ch7076] removed signed by unicef field
  src/etools/applications/partners/admin.py
  src/etools/applications/partners/exports_v2.py
  src/etools/applications/partners/migrations/0020_auto_20180719_1815.py
  src/etools/applications/partners/migrations/0022_remove_intervention_signed_by_unicef.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/fixtures.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_101_.response.json
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/tests/test_export_intervention.py
  src/etools/applications/partners/tests/test_validation_interventions.py
Labels: READY, has-migrations

#1797 Update djangosaml2 to latest version, includes update of pysaml2
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/test.txt
Labels: READY

#1788 [ch7069] removed fund commitment model
  src/etools/applications/partners/admin.py
  src/etools/applications/partners/migrations/0023_auto_20180814_1754.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIAgreements/get__api_v2_agreements_1672_.response.json
  src/etools/applications/partners/tests/factories.py
  src/etools/applications/partners/tests/test_admin.py
  src/etools/applications/partners/tests/test_models.py
Labels: READY, has-migrations

#1662 integrating djangolib
  src/etools/applications/EquiTrack/fields.py
  src/etools/applications/EquiTrack/forms.py
  src/etools/applications/EquiTrack/mixins.py
  src/etools/applications/EquiTrack/permissions.py
  src/etools/applications/EquiTrack/utils.py
  src/etools/applications/audit/models.py
  src/etools/applications/funds/migrations/0005_make_not_nullable.py
  src/etools/applications/funds/models.py
  src/etools/applications/funds/views.py
  src/etools/applications/management/views/general.py
  src/etools/applications/management/views/gis_v1.py
  src/etools/applications/management/views/reports.py
  src/etools/applications/management/views/tasks_endpoints.py
  src/etools/applications/partners/forms.py
  src/etools/applications/partners/migrations/0001_initial.py
  src/etools/applications/partners/migrations/0005_make_not_nullable.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/tests/test_api_pmp.py
  src/etools/applications/partners/views/agreements_v2.py
  src/etools/applications/partners/views/dashboards.py
  src/etools/applications/partners/views/interventions_v2.py
  src/etools/applications/partners/views/partner_organization_v2.py
  src/etools/applications/partners/views/v2.py
  src/etools/applications/publics/views.py
  src/etools/applications/reports/admin.py
  src/etools/applications/reports/views/v2.py
  src/etools/applications/t2f/views/exports.py
  src/etools/applications/t2f/views/travel.py
  src/etools/applications/tpm/models.py
  src/etools/applications/users/views.py
  src/etools/applications/users/views_v3.py
  src/etools/applications/utils/common/models/fields.py
  src/etools/applications/utils/common/tests/models.py
  src/etools/applications/utils/writable_serializers/serializers.py
  src/etools/applications/utils/writable_serializers/tests/models.py
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/test.txt
Labels: READY

#1802 missing migration
  src/etools/applications/partners/migrations/0024_remove_partnerorganization_core_values_assessment.py
Labels: READY

#1805 Update unicef-attachments to 0.2.4
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/test.txt
Labels: READY

#1803 Action Point closed email notification always says the assignee closed the action point, while sometimes the assigner did
  src/etools/applications/action_points/models.py
  src/etools/applications/action_points/notifications/action_point-completed.py
  src/etools/applications/action_points/tests/test_emails.py
  src/etools/applications/action_points/transitions/serializers/__init__.py
  src/etools/applications/action_points/transitions/serializers/serializers.py
Labels: READY, notifications update required

#1808 Fix AssertionErrror on incorrect request type in tpm visits subviews
  src/etools/applications/tpm/tests/test_views.py
  src/etools/applications/tpm/views.py
Labels: READY

#1811 revert saml2
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/test.txt
Labels: READY

#1791 Termination and Contingency
  src/etools/applications/EquiTrack/util_scripts.py
  src/etools/applications/partners/migrations/0025_auto_20180815_2026.py
  src/etools/applications/partners/migrations/0026_save_interventions.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/permissions.py
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_101_.response.json
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/tests/test_export_intervention.py
  src/etools/applications/partners/tests/test_validation_interventions.py
  src/etools/applications/partners/utils.py
  src/etools/applications/partners/validation/interventions.py
  src/etools/assets/partner/intervention_permissions.csv
Labels: READY

#1814 remove filter to show all document types
  src/etools/applications/partners/views/v2.py
Labels: READY

#1806 log AD Sync Tasks
  src/etools/libraries/azure_graph_api/tasks.py
  src/etools/libraries/azure_graph_api/tests/test_tasks.py
Labels: READY

#1818 Add update_attachment_source command
  src/etools/applications/attachments/management/commands/update_attachment_source.py
Labels: READY

#1819 Fix exception name spelling
  src/etools/applications/attachments/migrations/0010_auto_20180802_1245.py
Labels: READY

#1807 [ch6934] Return 0 instead of None as default in engagement pending_unsupported_amount
  src/etools/applications/audit/migrations/0010_auto_20180824_1552.py
  src/etools/applications/audit/models.py
  src/etools/applications/audit/tests/test_models.py
  src/etools/applications/audit/transitions/conditions.py
Labels: READY

#1821 Intervention Map Tweaks
  src/etools/applications/partners/serializers/interventions_v2.py
Labels: READY

#1825 PMP permissions tweaks
  src/etools/applications/partners/serializers/prp_v1.py
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_101_.response.json
  src/etools/applications/partners/tests/data/prp-intervention-list.json
  src/etools/assets/partner/intervention_permissions.csv
Labels: READY

#1828 Handle multiple records in copy_attachments
  src/etools/applications/partners/utils.py
Labels: READY, bug

#1830 [ch7346] fixed export (DRF 3.8)
  src/etools/applications/partners/serializers/exports/interventions.py
Labels: READY

#1832 Action Point assigner should be able to complete the action point
  src/etools/applications/action_points/management/commands/update_action_points_permissions.py
  src/etools/applications/action_points/tests/test_transitions.py
Labels: READY

#1816 [ch7296] fixed exception
  src/etools/applications/partners/serializers/partner_organization_v2.py
  src/etools/applications/partners/tests/test_api_partners.py
  src/etools/applications/partners/tests/test_views.py
Labels: READY

#1836 fixed AD sync
  src/etools/applications/users/tasks.py
Labels: READY

#1831 [Action Points] Changes to Related Document link
  src/etools/applications/action_points/models.py
  src/etools/applications/action_points/tests/test_models.py
  src/etools/applications/t2f/models.py
Labels: READY

#1833 [ch6478] tweaked admin and added updated groups json
  src/etools/applications/EquiTrack/data/groups.json
  src/etools/applications/partners/admin.py
Labels: READY
