Repository unicef/etools, pull requests merged in 2018-11, with the labels that each got.

#1930 [ch8169] fixed ip dashboard alert
  src/etools/applications/partners/models.py
  src/etools/applications/partners/views/partner_organization_v2.py
Labels: READY

#1932 [ch7559] tpm label
  src/etools/applications/tpm/serializers/visit.py
Labels: READY

#1933 dashboard integer api
  src/etools/applications/partners/serializers/partner_organization_v2.py
  src/etools/applications/partners/tests/test_views.py
Labels: READY

#1934 Add pd_ssfa id to attachment flat
  src/etools/applications/attachments/migrations/0013_attachmentflat_pd_ssfa.py
  src/etools/applications/attachments/models.py
  src/etools/applications/attachments/tests/test_views.py
  src/etools/applications/attachments/utils.py
Labels: READY

#1935 [ch7840] updated djangolib
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/test.txt
Labels: READY

#1937 ip dashboard: refine for action point
  src/etools/applications/partners/tests/test_views.py
  src/etools/applications/partners/views/partner_organization_v2.py
Labels: READY

#1941 updated tag version [6.4]
  src/etools/__init__.py
Labels: READY

#1942 [ch8116] pd export: fixed display for baseline and target
  src/etools/applications/reports/models.py
  src/etools/applications/reports/views/v2.py
Labels: READY

#1938 moved group wrapper to library
  src/etools/applications/action_points/models.py
  src/etools/applications/action_points/tests/base.py
  src/etools/applications/audit/models.py
  src/etools/applications/audit/tests/base.py
  src/etools/applications/tpm/models.py
  src/etools/applications/tpm/tests/base.py
  src/etools/libraries/djangolib/__init__.py
  src/etools/libraries/djangolib/models.py
Labels: READY

#1924 Fix for result_type filter in OutputListAPIView
  src/etools/applications/reports/serializers/v2.py
  src/etools/applications/reports/tests/test_views.py
  src/etools/applications/reports/views/v2.py
Labels: bug

#1943 python packages: updated minor version libraries
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/test.txt
Labels: READY

#1948 [ch7673] country office admin permissions
  src/etools/applications/EquiTrack/data/groups.json
Labels: READY

#1919 [ch8208] renamed misspelled functions
  src/etools/applications/partners/migrations/0001_initial.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/tests/test_models.py
Labels: READY

#1949 [ch6247] updated fr validation
  src/etools/applications/funds/tests/test_views.py
  src/etools/applications/funds/views.py
Labels: READY

#1950 [ch8381] changed export column name
  src/etools/applications/action_points/export/renderers.py
Labels: READY

#1953 [ch8474] fixed fam status filter
  src/etools/applications/audit/filters.py
Labels: READY

#1952 [ch8437] remove intervention sector location link model
  src/etools/applications/attachments/tests/test_views.py
  src/etools/applications/partners/admin.py
  src/etools/applications/partners/migrations/0028_auto_20181108_1503.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/serializers/exports/interventions.py
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_amendments_.response.json
  src/etools/applications/partners/tests/factories.py
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/tests/test_export_intervention.py
  src/etools/applications/partners/tests/test_models.py
  src/etools/applications/partners/tests/test_views.py
  src/etools/applications/partners/urls_v2.py
  src/etools/applications/partners/views/interventions_v2.py
  src/etools/applications/tpm/tests/factories.py
Labels: READY

#1959 [ch7560] TPM: allow to filter by date
  src/etools/applications/tpm/filters.py
Labels: READY

#1962 [ch8448] HACT: fixed error counting spot check completed
  src/etools/applications/hact/models.py
Labels: READY

#1967 [ch8270] permission matrix: allow to change unicef_signatory in Signed Status
  src/etools/assets/partner/intervention_permissions.csv
Labels: READY

#1968 [ch8251] update tpm permission matrix
  src/etools/applications/tpm/management/commands/update_tpm_permissions.py
Labels: READY

#1969 [ch8567] ADP: export added high priority
  src/etools/applications/action_points/export/renderers.py
  src/etools/applications/action_points/export/serializers.py
Labels: READY

#1981 [ch7560] TPM: remove duplicated
  src/etools/applications/tpm/views.py
Labels: READY

#1977 [ch8647] user sync: fixed user without profile + changed celery queue
  src/etools/applications/users/tasks.py
  src/etools/config/settings/base.py
  src/etools/libraries/azure_graph_api/tasks.py
Labels: READY

#1970 TPM attachment updates
  src/etools/applications/attachments/tests/factories.py
  src/etools/applications/tpm/serializers/attachments.py
  src/etools/applications/tpm/tests/test_views.py
  src/etools/applications/tpm/urls.py
  src/etools/applications/tpm/views.py
Labels: READY

#1974 Send suspension notification when agreement suspended
  src/etools/applications/partners/notifications/agreement-suspended.py
  src/etools/applications/partners/tests/test_views.py
  src/etools/applications/partners/utils.py
  src/etools/applications/partners/views/agreements_v2.py
Labels: changes-requested

#1984 [ch8475] added filtering for rt export
  src/etools/applications/action_points/views.py
  src/etools/applications/audit/views.py
  src/etools/applications/tpm/views.py
Labels: WIP

#1989 [ch8820] ap export fixed none value for str
  src/etools/applications/action_points/export/serializers.py
Labels: READY

#1988 [ch8808] ap export fixed action
  .gitignore
  src/etools/applications/action_points/export/renderers.py
Labels: READY

#1992 Ensure we pass a list of recipients to send_notification_with_template
  src/etools/applications/partners/tests/test_api_agreements.py
  src/etools/applications/partners/utils.py
Labels: READY, bug

#1996 Denormalize attachments all flag
  src/etools/applications/attachments/management/commands/denormalize_attachments.py
Labels: READY
