Repository unicef/etools, pull requests merged in 2018-07, with the labels that each got.

#1698 [ch6524] Hotfix: fixed notification
  src/etools/applications/partners/tasks.py
  src/etools/applications/vision/adapters/partner.py
Labels: READY

#1697 management api for monthly report
  src/etools/applications/management/urls.py
  src/etools/applications/management/views/tasks_endpoints.py
  src/etools/applications/partners/tasks.py
  src/etools/applications/users/tasks.py
Labels: READY

#1691 Reset location parent to root level if there's no parent in the Carto table
  src/etools/applications/locations/tasks.py
Labels: READY

#1689 Token auth now also checks against drf token auth
  src/etools/applications/tokens/middleware.py
Labels: READY

#1699 Ensure tasks is run across all workspaces
  src/etools/applications/partners/tasks.py
Labels: READY

#1686 Ability to create t2f/ap/tpm related action points from base api.
  src/etools/applications/action_points/management/commands/update_action_points_permissions.py
  src/etools/applications/action_points/serializers.py
  src/etools/applications/action_points/tests/test_views.py
  src/etools/applications/action_points/views.py
  src/etools/applications/t2f/models.py
Labels: READY

#1680 upgrade requirements + refactoring
  .circleci/images/primary/Dockerfile
  .pyup.yml
  Dockerfile
  requirements.txt
  setup.py
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/input/local.in
  src/requirements/input/production.in
  src/requirements/input/test.in
  src/requirements/local.txt
  src/requirements/production.txt
  src/requirements/test.txt
  tasks.py
Labels: READY

#1708 Attachments upload
  src/etools/applications/attachments/admin.py
  src/etools/applications/attachments/migrations/0006_auto_20180321_1423.py
  src/etools/applications/attachments/migrations/0007_auto_20180322_1723.py
  src/etools/applications/attachments/models.py
  src/etools/applications/attachments/serializers.py
  src/etools/applications/attachments/serializers_fields.py
  src/etools/applications/attachments/tests/test_models.py
  src/etools/applications/attachments/tests/test_views.py
  src/etools/applications/attachments/urls.py
  src/etools/applications/attachments/utils.py
  src/etools/applications/attachments/views.py
  src/etools/applications/partners/admin.py
  src/etools/applications/partners/serializers/agreements_v2.py
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/serializers/partner_organization_v2.py
  src/etools/applications/partners/tests/test_api_agreements.py
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/tests/test_api_partners.py
  src/etools/applications/partners/tests/test_serializers.py
  src/etools/applications/partners/tests/test_utils.py
  src/etools/applications/partners/tests/test_views.py
  src/etools/applications/partners/validation/agreements.py
Labels: READY, has-migrations

#1711 Prp tweaks
  src/etools/applications/partners/serializers/prp_v1.py
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/api_v2_interventions.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/api_v2_interventions_101.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/api_v2_interventions_amendments.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/api_v2_interventions_indicators.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/api_v2_interventions_map.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestPartners/api_v2_partners.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestPartners/api_v2_partners_101.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestPartners/api_v2_partners_not_programmatic_visit.response.json
  src/etools/applications/partners/tests/data/prp-intervention-list.json
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/reports/migrations/0011_auto_20180709_1326.py
  src/etools/applications/reports/migrations/0012_auto_20180709_1328.py
  src/etools/applications/reports/migrations/0013_auto_20180709_1348.py
  src/etools/applications/reports/models.py
  src/etools/applications/reports/serializers/v2.py
  src/etools/applications/reports/tests/test_views.py
Labels: READY, has-migrations

#1704 [ch5499] Remove Section Model (part 1)
  src/etools/applications/action_points/serializers.py
  src/etools/applications/management/tests/test_views.py
  src/etools/applications/management/urls.py
  src/etools/applications/management/views/v1.py
  src/etools/applications/t2f/admin.py
  src/etools/applications/t2f/migrations/0005_remove_travel_section.py
  src/etools/applications/t2f/migrations/0006_auto_20180703_2200.py
  src/etools/applications/t2f/models.py
  src/etools/applications/t2f/serializers/export.py
  src/etools/applications/t2f/serializers/filters/travel_list.py
  src/etools/applications/t2f/serializers/travel.py
  src/etools/applications/t2f/tests/factories.py
  src/etools/applications/t2f/tests/test_exports.py
  src/etools/applications/t2f/tests/test_travel_list.py
  src/etools/applications/t2f/views/dashboard.py
  src/etools/applications/t2f/views/exports.py
  src/etools/applications/users/admin.py
  src/etools/applications/users/forms.py
  src/etools/applications/users/migrations/0003_auto_20180703_1729.py
  src/etools/applications/users/models.py
  src/etools/applications/users/serializers.py
  src/etools/applications/users/tasks.py
  src/etools/applications/users/tests/factories.py
  src/etools/applications/users/tests/test_models.py
  src/etools/applications/users/tests/test_tasks.py
  src/etools/applications/users/tests/test_views.py
  src/etools/applications/users/views.py
  src/etools/config/urls.py
Labels: READY

#1707 [ch6531] PD Exports harmonize
  src/etools/applications/partners/exports_v2.py
  src/etools/applications/partners/serializers/exports/interventions.py
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIAgreements/fixtures.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIAgreements/get__api_v2_agreements_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIAgreements/get__api_v2_agreements_5_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIAgreements/get__api_v2_agreements_amendments_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/api_v2_interventions.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/api_v2_interventions_101.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/api_v2_interventions_amendments.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/api_v2_interventions_indicators.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/api_v2_interventions_map.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/fixtures.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_101_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_amendments_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestPartners/api_v2_partners.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestPartners/api_v2_partners_101.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestPartners/api_v2_partners_not_programmatic_visit.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestPartners/fixtures.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestPartners/get__api_v2_partners_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestPartners/get__api_v2_partners_101_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestPartners/get__api_v2_partners_not_programmatic_visit_.response.json
  src/etools/applications/partners/tests/test_export_intervention.py
  src/etools/applications/partners/tests/test_exports.py
  src/etools/applications/partners/views/interventions_v2.py
  src/etools/applications/reports/views/v2.py
Labels: READY

#1705 [ch5499] migrate sections (part 2)
  src/etools/applications/action_points/serializers.py
  src/etools/applications/action_points/tests/factories.py
  src/etools/applications/action_points/tests/test_views.py
  src/etools/applications/attachments/tests/test_views.py
  src/etools/applications/audit/serializers/engagement.py
  src/etools/applications/audit/tests/test_views.py
  src/etools/applications/partners/admin.py
  src/etools/applications/partners/serializers/exports/interventions.py
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/serializers/prp_v1.py
  src/etools/applications/partners/tests/factories.py
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/tests/test_export_intervention.py
  src/etools/applications/partners/tests/test_models.py
  src/etools/applications/partners/tests/test_views.py
  src/etools/applications/partners/urls_v2.py
  src/etools/applications/partners/views/interventions_v2.py
  src/etools/applications/reports/admin.py
  src/etools/applications/reports/serializers/v1.py
  src/etools/applications/reports/tests/factories.py
  src/etools/applications/reports/tests/test_models.py
  src/etools/applications/reports/tests/test_serializers.py
  src/etools/applications/reports/tests/test_views.py
  src/etools/applications/reports/views/v1.py
  src/etools/applications/t2f/serializers/static_data.py
  src/etools/applications/t2f/tests/factories.py
  src/etools/applications/t2f/tests/test_exports.py
  src/etools/applications/tpm/serializers/visit.py
  src/etools/applications/tpm/tests/factories.py
  src/etools/applications/tpm/views.py
  src/etools/applications/users/views.py
  src/etools/config/urls.py
Labels: READY

#1716 [ch6335] traveler latest date
  .gitignore
  src/etools/applications/t2f/serializers/travel.py
  src/etools/applications/t2f/tests/test_dashboard.py
Labels: READY

#1718 Send engagement submit to country focal points
  src/etools/applications/audit/models.py
  src/etools/applications/audit/tests/base.py
  src/etools/applications/audit/tests/test_email.py
  src/etools/applications/users/tests/factories.py
Labels: READY

#1717 Use travel activity instead of t2f travel inside action point
  src/etools/applications/action_points/filters.py
  src/etools/applications/action_points/management/commands/update_action_points_permissions.py
  src/etools/applications/action_points/migrations/0005_auto_20180713_0805.py
  src/etools/applications/action_points/models.py
  src/etools/applications/action_points/serializers.py
  src/etools/applications/action_points/tests/test_models.py
  src/etools/applications/action_points/tests/test_views.py
  src/etools/applications/action_points/views.py
  src/etools/applications/t2f/models.py
Labels: READY, has-migrations

#1720 TPM updates
  src/etools/applications/tpm/export/renderers.py
  src/etools/applications/tpm/export/serializers.py
  src/etools/applications/tpm/templates/tpm/visit_letter_pdf.html
Labels: READY

#1723 Reuse/add a staff member which was deleted from the Audit staff members list.
  src/etools/applications/audit/purchase_order/migrations/0005_auditorstaffmember_hidden.py
  src/etools/applications/audit/purchase_order/models.py
  src/etools/applications/audit/serializers/auditor.py
  src/etools/applications/audit/signals.py
  src/etools/applications/audit/tests/test_views.py
  src/etools/applications/audit/views.py
Labels: READY, has-migrations

#1724 moved sections api
  src/etools/applications/reports/tests/test_views.py
  src/etools/applications/reports/urls_v2.py
  src/etools/applications/users/models.py
  src/etools/applications/users/views.py
  src/etools/applications/users/views_v2.py
  src/etools/config/urls.py
Labels: READY

#1714 Gis locations API changes
  src/etools/applications/management/views/gis_v1.py
Labels: READY

#1727 Remove unicef signatory
  src/etools/applications/partners/admin.py
  src/etools/applications/partners/exports_v2.py
  src/etools/applications/partners/migrations/0019_intervention_signed_by_unicef.py
  src/etools/applications/partners/migrations/0020_auto_20180719_1815.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/serializers/agreements_v2.py
  src/etools/applications/partners/serializers/exports/interventions.py
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIAgreements/fixtures.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIAgreements/get__api_v2_agreements_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIAgreements/get__api_v2_agreements_233_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIAgreements/get__api_v2_agreements_amendments_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/fixtures.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_101_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_amendments_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_indicators_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_map_.response.json
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/tests/test_export_intervention.py
  src/etools/applications/partners/tests/test_serializers.py
  src/etools/applications/partners/tests/test_validation_interventions.py
  src/etools/applications/partners/validation/agreements.py
  src/etools/applications/partners/validation/interventions.py
  src/etools/assets/partner/agreement_permissions.csv
  src/etools/assets/partner/intervention_permissions.csv
Labels: READY, has-migrations

#1495 [ch5824] t2f new Action Points
  src/etools/applications/action_points/admin.py
  src/etools/applications/action_points/serializers.py
  src/etools/applications/action_points/views.py
  src/etools/applications/audit/tests/test_views.py
  src/etools/applications/t2f/admin.py
  src/etools/applications/t2f/filters/action_points.py
  src/etools/applications/t2f/filters/invoices.py
  src/etools/applications/t2f/filters/travel_list.py
  src/etools/applications/t2f/management/commands/migrate_ap.py
  src/etools/applications/t2f/models.py
  src/etools/applications/t2f/renderers.py
  src/etools/applications/t2f/serializers/export.py
  src/etools/applications/t2f/serializers/filters/action_points.py
  src/etools/applications/t2f/serializers/mailing.py
  src/etools/applications/t2f/serializers/travel.py
  src/etools/applications/t2f/tests/factories.py
  src/etools/applications/t2f/tests/test_action_points.py
  src/etools/applications/t2f/tests/test_cost_summary_calculator.py
  src/etools/applications/t2f/tests/test_dashboard.py
  src/etools/applications/t2f/tests/test_dsa_calculations.py
  src/etools/applications/t2f/tests/test_exports.py
  src/etools/applications/t2f/tests/test_invoice_making.py
  src/etools/applications/t2f/tests/test_overlapping_trips.py
  src/etools/applications/t2f/tests/test_permission_matrix.py
  src/etools/applications/t2f/tests/test_state_machine.py
  src/etools/applications/t2f/tests/test_threshold.py
  src/etools/applications/t2f/tests/test_travel_details.py
  src/etools/applications/t2f/tests/test_travel_list.py
  src/etools/applications/t2f/tests/test_vision_export.py
  src/etools/applications/t2f/urls.py
  src/etools/applications/t2f/views/dashboard.py
  src/etools/applications/t2f/views/exports.py
  src/etools/applications/t2f/views/generics.py
  src/etools/applications/t2f/views/travel.py
Labels: READY

#1731 label
  src/etools/applications/t2f/models.py
Labels: READY

#1733 tweaks for hact
  src/etools/applications/partners/models.py
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIAgreements/fixtures.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIAgreements/get__api_v2_agreements_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIAgreements/get__api_v2_agreements_122_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIAgreements/get__api_v2_agreements_amendments_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/fixtures.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_101_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_amendments_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_indicators_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_map_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestPartners/fixtures.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestPartners/get__api_v2_partners_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestPartners/get__api_v2_partners_101_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestPartners/get__api_v2_partners_not_programmatic_visit_.response.json
  src/etools/applications/partners/tests/test_api.py
Labels: READY

#1721 Action points & audit updates
  src/etools/applications/EquiTrack/data/action_points_categories.json
  src/etools/applications/action_points/export/renderers.py
  src/etools/applications/action_points/export/serializers.py
  src/etools/applications/action_points/management/commands/update_action_points_permissions.py
  src/etools/applications/action_points/metadata.py
  src/etools/applications/action_points/migrations/0006_auto_20180718_1439.py
  src/etools/applications/action_points/models.py
  src/etools/applications/action_points/serializers.py
  src/etools/applications/action_points/tests/factories.py
  src/etools/applications/action_points/tests/test_views.py
  src/etools/applications/action_points/transitions/conditions.py
  src/etools/applications/action_points/views.py
  src/etools/applications/attachments/serializers.py
  src/etools/applications/audit/models.py
  src/etools/applications/audit/serializers/engagement.py
  src/etools/applications/audit/serializers/export.py
  src/etools/applications/audit/templates/audit/engagement_pdf.html
  src/etools/applications/audit/tests/test_views.py
  src/etools/applications/tpm/models.py
  src/etools/applications/tpm/serializers/visit.py
  src/etools/applications/utils/common/urlresolvers.py
Labels: READY, has-migrations, permissions update required

#1729 Update pca contract templates
  src/etools/applications/partners/tests/test_views.py
  src/etools/applications/partners/views/v1.py
  src/etools/templates/partners/pca/english_pdf.html
  src/etools/templates/partners/pca/french_pdf.html
  src/etools/templates/partners/pca/ifrc_english_pdf.html
  src/etools/templates/partners/pca/ifrc_french_pdf.html
  src/etools/templates/partners/pca/portuguese_pdf.html
  src/etools/templates/partners/pca/russian_pdf.html
  src/etools/templates/partners/pca/spanish_pdf.html
Labels: READY

#1736 [ch6009] new login redirect
  src/etools/config/settings/base.py
Labels: READY

#1737 Filter Action Point list to multiple status
  src/etools/applications/action_points/tests/test_views.py
  src/etools/applications/action_points/views.py
Labels: READY

#1740 fix dashboard
  src/etools/applications/t2f/views/dashboard.py
Labels: READY

#1739 Add internal_prc_review attachment to InterventionAmendment
  src/etools/applications/partners/models.py
  src/etools/applications/partners/serializers/exports/interventions.py
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_amendments_.response.json
  src/etools/applications/partners/tests/test_api_interventions.py
Labels: READY

#1746 Action points updates
  src/etools/applications/action_points/admin.py
  src/etools/applications/action_points/models.py
  src/etools/applications/action_points/serializers.py
  src/etools/applications/action_points/signals.py
  src/etools/applications/action_points/tests/test_emails.py
  src/etools/applications/action_points/tests/test_views.py
  src/etools/applications/audit/serializers/engagement.py
  src/etools/applications/audit/signals.py
  src/etools/applications/audit/tests/test_views.py
  src/etools/applications/audit/views.py
  src/etools/applications/tpm/serializers/visit.py
  src/etools/applications/tpm/tests/test_views.py
Labels: READY

#1748 Fix unavailability to process with url from tpm invite email.
  src/etools/applications/audit/signals.py
  src/etools/applications/tpm/signals.py
  src/etools/applications/users/tests/test_views.py
  src/etools/applications/users/views.py
Labels: READY

#1749 Add attachment file type if it does not exist
  src/etools/applications/attachments/serializers.py
Labels: READY

#1744 update locations
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/fixtures.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_101_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_amendments_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_indicators_.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_map_.response.json
  src/etools/applications/t2f/serializers/static_data.py
  src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPILocations/get__api_locations-light_.response.json
  src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPILocations/get__api_locations_.response.json
  src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPILocations/get__api_locations_101_.response.json
  src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPILocations/get__api_locations_pcode_abc_.response.json
  src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPILocations/get__locations_autocomplete_.response.json
  src/etools/libraries/locations/tests/test_views.py
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/test.txt
Labels: READY

#1752 fix migrate_ap command
  src/etools/applications/t2f/management/commands/migrate_ap.py
Labels: READY

#1734 Add agreement link to attachment flat endpoint data
  src/etools/applications/attachments/management/commands/update_object_links.py
  src/etools/applications/attachments/migrations/0009_attachmentflat_agreement_link.py
  src/etools/applications/attachments/models.py
  src/etools/applications/attachments/tests/test_views.py
  src/etools/applications/attachments/utils.py
  src/etools/applications/partners/models.py
Labels: READY

#1751 Attachment upload validation
  src/etools/applications/attachments/serializers.py
  src/etools/applications/attachments/tests/test_views.py
  src/etools/applications/attachments/validators.py
Labels: READY

#1757 added properties to chart api extension
  src/etools/applications/hact/models.py
Labels: READY

#1758 fixed user admin
  src/etools/applications/users/admin.py
  src/etools/applications/users/tasks.py
Labels: READY
