Repository unicef/etools, pull requests merged in 2019-07, with the labels that each got.

#2421 [ch12815] allow to see reports for any status
  src/etools/applications/audit/management/commands/update_audit_permissions.py
Labels: READY

#2424 v7.2
  src/etools/__init__.py
Labels: MERGE beginning next sprint, READY

#2414 CH 12818 - fix unit test warnings.
  src/etools/applications/partners/utils.py
Labels: MERGE beginning next sprint, READY

#2425 [ch12682] FAM attchment permissions
  src/etools/applications/audit/management/commands/update_audit_permissions.py
Labels: READY

#2323 [ch6560] move to python 3.7
  .circleci/config.yml
  .circleci/images/primary/Dockerfile
  Dockerfile
  Dockerfile-dev
  Pipfile
  Pipfile.lock
  tox.ini
Labels: MERGE beginning next sprint

#2417 [ch12015] forbid uppercase chars when adding email
  src/etools/applications/firms/serializers.py
  src/etools/libraries/djangolib/tests/test_validators.py
  src/etools/libraries/djangolib/validators.py
Labels: MERGE beginning next sprint, READY

#2382 [ch12242] partner dashboard core values assess date
  src/etools/applications/partners/serializers/partner_organization_v2.py
  src/etools/applications/partners/tests/test_views.py
  src/etools/applications/partners/views/partner_organization_v2.py
Labels: MERGE beginning next sprint, READY

#2397 Update requirements
  Pipfile
  Pipfile.lock
Labels: MERGE beginning next sprint

#2426 [ch12424] intervention filter by partner/agreement
  src/etools/applications/partners/views/interventions_v2.py
  src/etools/applications/reports/views/v2.py
Labels: MERGE beginning next sprint, READY

#2416 Firm improvements
  src/etools/applications/audit/purchase_order/migrations/0007_auto_20190625_1437.py
  src/etools/applications/audit/purchase_order/models.py
  src/etools/applications/firms/models.py
  src/etools/applications/tpm/tpmpartners/migrations/0005_auto_20190625_1437.py
  src/etools/applications/tpm/tpmpartners/models.py
Labels: MERGE beginning next sprint, READY

#2430 Update django-storage to 1.7.1
  Pipfile
  Pipfile.lock
  src/etools/libraries/azure_storage_backend.py
  src/etools/libraries/tests/test_storages_azure.py
Labels: READY

#2436 [Ch13098] Fix french PCA document issues
  src/etools/applications/partners/templates/pca/french_pdf.html
Labels: READY

#2439 [ch12873] hact spot check required
  src/etools/applications/partners/models.py
  src/etools/applications/partners/tests/test_models.py
Labels: READY

#2443 [ch13380] tpm visit allow null in the admin
  src/etools/applications/activities/migrations/0003_auto_20190722_1417.py
  src/etools/applications/activities/models.py
  src/etools/applications/tpm/admin.py
Labels: READY

#2446 [ch12873] fix spot_check_required
  src/etools/applications/partners/models.py
Labels: READY

#2448 [ch13273] ament permissions
  src/etools/applications/audit/management/commands/update_audit_permissions.py
Labels: READY

#2452 French PCA template quickfix
  src/etools/applications/partners/templates/pca/french_pdf.html
  src/etools/applications/partners/templates/pca/ifrc_french_pdf.html
Labels: READY
