Repository unicef/etools, pull requests merged in 2019-01, with the labels that each got.

#2088 Fix factories to handle running tests on last day of the year
  src/etools/applications/t2f/tests/factories.py
Labels: READY

#2087 enhancement: change arrayfield default
  src/etools/applications/action_points/export/renderers.py
  src/etools/applications/audit/migrations/0012_auto_20181229_0249.py
  src/etools/applications/audit/models.py
  src/etools/applications/permissions2/migrations/0003_auto_20181229_0249.py
  src/etools/applications/permissions2/models.py
  src/etools/applications/reports/migrations/0014_auto_20181229_0249.py
  src/etools/applications/reports/models.py
  src/etools/applications/t2f/migrations/0010_auto_20181229_0249.py
  src/etools/applications/t2f/models.py
Labels: READY

#2092 [ch9062] trip fix export
  src/etools/applications/t2f/views/exports.py
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/test.txt
Labels: READY

#2083 t2f more cleaning
  src/etools/applications/t2f/admin.py
  src/etools/applications/t2f/deployment.md
Labels: READY

#2091 [ch9144] trips added field to export
  src/etools/applications/t2f/serializers/export.py
  src/etools/applications/t2f/tests/test_exports.py
Labels: READY

#2094 t2f: remove invoice model
  src/etools/applications/t2f/admin.py
  src/etools/applications/t2f/filters/invoices.py
  src/etools/applications/t2f/helpers/invoice_maker.py
  src/etools/applications/t2f/migrations/0011_auto_20190102_1919.py
  src/etools/applications/t2f/models.py
  src/etools/applications/t2f/serializers/filters/invoices.py
  src/etools/applications/t2f/serializers/invoices.py
  src/etools/applications/t2f/templates/base.html
  src/etools/applications/t2f/templates/emails/failed_invoice_sync.html
  src/etools/applications/t2f/tests/factories.py
  src/etools/applications/t2f/tests/test_invoice_endpoints.py
  src/etools/applications/t2f/tests/test_mailing.py
  src/etools/applications/t2f/tests/test_models.py
  src/etools/applications/t2f/urls.py
  src/etools/applications/t2f/views/invoices.py
Labels: READY, has-migrations

#2098 publics isort
  src/etools/applications/publics/management/commands/load_initial_data.py
  src/etools/applications/publics/serializers.py
  src/etools/applications/publics/tasks.py
  src/etools/applications/publics/tests/test_dsa_rates.py
  src/etools/applications/publics/tests/test_models.py
  src/etools/applications/publics/tests/test_static_data_endpoints.py
  src/etools/applications/publics/tests/test_synchronizers.py
  src/etools/applications/publics/urls.py
Labels: READY

#2097 Add hact programmatic visit report to travel activity export
  src/etools/applications/t2f/serializers/export.py
  src/etools/applications/t2f/tests/test_exports.py
Labels: READY

#2104 update etools version
  src/etools/__init__.py
Labels: READY

#2103 Flake
  .flake8
  src/etools/applications/EquiTrack/middleware.py
  src/etools/applications/EquiTrack/utils.py
  src/etools/applications/action_points/models.py
  src/etools/applications/audit/serializers/risks.py
  src/etools/applications/permissions2/conditions.py
  src/etools/applications/utils/common/views.py
Labels: READY

#2096 Add DRAFT status to agreement status automatic transitions
  src/etools/applications/partners/tasks.py
  src/etools/applications/partners/tests/test_tasks.py
Labels: READY

#2105 [ch9293] tweak country admin
  src/etools/applications/users/templates/admin/users/country/change_form.html
Labels: READY

#2100 [ch9246] allow filter activity by type
  src/etools/applications/t2f/views/travel.py
Labels: READY

#2089 Refactor t2f permission matrix
  src/etools/applications/t2f/helpers/permission_matrix.py
  src/etools/applications/t2f/management/commands/_private.py
  src/etools/applications/t2f/management/commands/et2f_init.py
  src/etools/applications/t2f/permission_matrix.json
  src/etools/applications/t2f/permissions.py
  src/etools/applications/t2f/tests/test_permission_matrix.py
  src/etools/applications/t2f/tests/test_state_machine.py
Labels: READY

#2085 t2f: remove clearance
  src/etools/applications/t2f/admin.py
  src/etools/applications/t2f/helpers/clone_travel.py
  src/etools/applications/t2f/management/commands/_private.py
  src/etools/applications/t2f/migrations/0012_auto_20190104_1911.py
  src/etools/applications/t2f/models.py
  src/etools/applications/t2f/serializers/travel.py
  src/etools/applications/t2f/tests/factories.py
  src/etools/applications/t2f/tests/test_overlapping_trips.py
  src/etools/applications/t2f/tests/test_permission_matrix.py
  src/etools/applications/t2f/tests/test_travel_details.py
  src/etools/applications/t2f/tests/test_travel_list.py
Labels: READY, has-migrations

#2086 [ch8668] hact: remove spot checks count from trips
  src/etools/applications/partners/models.py
  src/etools/applications/partners/tests/test_models.py
Labels: READY

#1960 moved inspector and schema [refactoring]
  src/etools/applications/EquiTrack/inspectors.py
  src/etools/applications/EquiTrack/schemas.py
  src/etools/config/settings/base.py
  src/etools/config/urls.py
Labels: on hold

#2106 [Field monitoring] csv exports for planning
  src/etools/applications/field_monitoring/planning/export/__init__.py
  src/etools/applications/field_monitoring/planning/export/renderers.py
  src/etools/applications/field_monitoring/planning/export/serializers.py
  src/etools/applications/field_monitoring/planning/tests/test_views.py
  src/etools/applications/field_monitoring/planning/views.py
Labels: READY

#2112 [ch9147] remove partnership from static
  src/etools/applications/t2f/serializers/static_data.py
  src/etools/applications/t2f/tests/test_static_data_endpoint.py
  src/etools/applications/t2f/views/generics.py
Labels: READY

#2095 Update trips to use etools attachments library
  src/etools/applications/attachments/tests/test_utils.py
  src/etools/applications/attachments/utils.py
  src/etools/applications/partners/utils.py
  src/etools/applications/t2f/management/commands/copy_t2f_travel_attachments.py
  src/etools/applications/t2f/migrations/0013_auto_20190103_1345.py
  src/etools/applications/t2f/models.py
  src/etools/applications/t2f/serializers/travel.py
  src/etools/applications/t2f/tests/test_travel_details.py
Labels: READY, has-migrations

#2115 Exclude Trips from document library
  src/etools/applications/attachments/models.py
  src/etools/applications/attachments/tests/test_models.py
  src/etools/applications/attachments/tests/test_utils.py
  src/etools/applications/attachments/utils.py
Labels: READY

#2113 Add staff member unique email validation
  src/etools/applications/partners/serializers/partner_organization_v2.py
  src/etools/applications/partners/tests/test_api_partners.py
  src/etools/applications/partners/tests/test_views.py
Labels: READY

#2116 Trips test coverage
  src/etools/applications/t2f/helpers/permission_matrix.py
  src/etools/applications/t2f/management/commands/et2f_init.py
  src/etools/applications/t2f/management/commands/import_permission_matrix.py
  src/etools/applications/t2f/models.py
  src/etools/applications/t2f/tests/test_commands.py
  src/etools/applications/t2f/tests/test_models.py
  src/etools/applications/t2f/tests/test_permission_matrix.py
  src/etools/applications/t2f/tests/test_travel_list.py
Labels: READY

#2114 [ch9344] added TimeStampedModel for locations and users
  src/etools/applications/partners/tests/test_api.py
  src/etools/applications/users/migrations/0008_auto_20190111_1525.py
  src/etools/applications/users/models.py
  src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPICartoDB/fixtures.json
  src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPICartoDB/get__locations_cartodbtables_.response.json
  src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPILocations/fixtures.json
  src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPILocations/get__api_locations-light_.response.json
  src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPILocations/get__api_locations-types_.response.json
  src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPILocations/get__api_locations_.response.json
  src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPILocations/get__api_locations_101_.response.json
  src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPILocations/get__api_locations_pcode_abc_.response.json
  src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPILocations/get__locations_autocomplete_.response.json
  src/etools/libraries/locations/tests/test_api.py
  src/etools/libraries/utils/test/api_checker.py
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/input/test.in
  src/requirements/test.txt
Labels: READY

#2120 [ch9340] fixed filtering on trips dashboard
  src/etools/applications/t2f/views/dashboard.py
Labels: READY

#2117 tenant support library
  src/etools/applications/EquiTrack/auth.py
  src/etools/applications/EquiTrack/middleware.py
  src/etools/applications/EquiTrack/tests/test_utils.py
  src/etools/applications/EquiTrack/util_scripts.py
  src/etools/applications/EquiTrack/utils.py
  src/etools/applications/attachments/management/commands/denormalize_attachments.py
  src/etools/applications/attachments/management/commands/update_attachment_source.py
  src/etools/applications/attachments/management/commands/update_object_links.py
  src/etools/applications/firms/models.py
  src/etools/applications/management/issues/checks.py
  src/etools/applications/management/tasks.py
  src/etools/applications/management/views/reports.py
  src/etools/applications/partners/tasks.py
  src/etools/applications/partners/utils.py
  src/etools/applications/t2f/management/commands/copy_t2f_travel_attachments.py
  src/etools/applications/utils/common/models/mixins.py
  src/etools/applications/utils/common/utils.py
  src/etools/libraries/tenant_support/__init__.py
  src/etools/libraries/tenant_support/models.py
  src/etools/libraries/tenant_support/tests/__init__.py
  src/etools/libraries/tenant_support/tests/test_utils.py
  src/etools/libraries/tenant_support/utils.py
Labels: READY

#2123 REFACTORING moved get_data_from_insight into vision app
  src/etools/applications/EquiTrack/utils.py
  src/etools/applications/partners/views/partner_organization_v2.py
  src/etools/applications/partners/views/v1.py
  src/etools/applications/vision/utils.py
Labels: READY

#2126 [ch9376] usersync cleaning
  src/etools/applications/management/templates/portal.html
  src/etools/applications/users/admin.py
  src/etools/applications/users/tasks.py
  src/etools/applications/users/tests/test_tasks.py
Labels: READY

#2128 clean removing legacy
  .pyup.yml
  src/etools/config/saml/attribute-maps/adfs_v20.py
  src/etools/config/saml/attribute-maps/basic.py
  src/etools/config/saml/certs/.gitkeep
  src/etools/config/saml/etripspub.cer
  src/etools/config/saml/stspem.cer
  src/etools/config/settings/base.py
  src/etools/config/settings/local.py
  src/etools/config/urls.py
Labels: READY

#1678 Local cache redis
  .circleci/config.yml
  src/etools/applications/partners/apps.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/signals.py
  src/etools/applications/partners/tests/test_models.py
  src/etools/applications/reports/apps.py
  src/etools/applications/reports/models.py
  src/etools/applications/reports/signals.py
Labels: READY

#2124 REFACTORING cleaning EquiTrack
  src/etools/applications/EquiTrack/models.py
  src/etools/applications/EquiTrack/serializers.py
  src/etools/applications/EquiTrack/utils.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/permissions.py
  src/etools/applications/partners/views/partner_organization_v2.py
  src/etools/applications/reports/permissions.py
  src/etools/libraries/djangolib/models.py
  src/etools/libraries/djangolib/utils.py
Labels: READY

#2125 REFACTORING move factory to test library
  src/etools/applications/action_points/tests/factories.py
  src/etools/applications/tpm/tests/factories.py
  src/etools/libraries/tests/__init__.py
  src/etools/libraries/tests/factories.py
  src/etools/libraries/tests/test_storages_azure.py
Labels: READY

#2129 moved sentry client
  src/etools/config/sentry.py
  src/etools/config/settings/production.py
Labels: READY

#2132 Change docstrings style
  src/etools/applications/EquiTrack/tests/cases.py
  src/etools/applications/EquiTrack/tests/mixins.py
  src/etools/applications/EquiTrack/utils.py
  src/etools/applications/audit/tests/test_email.py
  src/etools/applications/audit/tests/test_views.py
  src/etools/applications/funds/tests/test_api.py
  src/etools/applications/funds/tests/test_models.py
  src/etools/applications/management/tests/test_api.py
  src/etools/applications/management/tests/test_models.py
  src/etools/applications/management/tests/test_views.py
  src/etools/applications/management/views/gis_v1.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/permissions.py
  src/etools/applications/partners/tests/factories.py
  src/etools/applications/partners/tests/test_api_agreements.py
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/tests/test_api_partners.py
  src/etools/applications/partners/tests/test_api_pmp.py
  src/etools/applications/partners/tests/test_api_prp.py
  src/etools/applications/partners/tests/test_models.py
  src/etools/applications/partners/tests/test_serializers.py
  src/etools/applications/partners/tests/test_tasks.py
  src/etools/applications/partners/tests/test_views.py
  src/etools/applications/partners/validation/agreements.py
  src/etools/applications/partners/validation/interventions.py
  src/etools/applications/publics/tests/test_models.py
  src/etools/applications/reports/permissions.py
  src/etools/applications/reports/tests/test_models.py
  src/etools/applications/reports/tests/test_views.py
  src/etools/applications/t2f/serializers/travel.py
  src/etools/applications/t2f/tests/test_models.py
  src/etools/applications/t2f/tests/test_static_data_endpoint.py
  src/etools/applications/t2f/tests/test_travel_details.py
  src/etools/applications/t2f/tests/test_travel_list.py
  src/etools/applications/users/tests/test_models.py
  src/etools/applications/utils/common/tests/test_utils.py
  src/etools/applications/utils/common/utils.py
  src/etools/applications/vision/tests/test_models.py
  src/etools/libraries/locations/task_utils.py
  src/etools/libraries/locations/tests/test_views.py
Labels: READY

#2133 Grammar and translation changes
  src/etools/applications/action_points/categories/migrations/0002_auto_20190122_1412.py
  src/etools/applications/action_points/categories/models.py
  src/etools/applications/environment/migrations/0002_auto_20190122_1412.py
  src/etools/applications/environment/models.py
  src/etools/applications/hact/migrations/0003_auto_20190122_1412.py
  src/etools/applications/hact/models.py
  src/etools/applications/partners/admin.py
  src/etools/applications/partners/migrations/0031_auto_20190122_1412.py
  src/etools/applications/partners/models.py
  src/etools/applications/users/admin.py
  src/etools/applications/users/migrations/0009_auto_20190122_1412.py
  src/etools/applications/users/models.py
  src/etools/libraries/locations/admin.py
Labels: READY

#2139 [ch9486] email with social auth - change email link
  src/etools/applications/audit/notifications/staff_member-invite.py
  src/etools/applications/audit/purchase_order/models.py
  src/etools/applications/firms/utils.py
  src/etools/applications/permissions2/views.py
  src/etools/applications/tpm/models.py
  src/etools/applications/utils/common/tests/test_utils.py
  src/etools/applications/utils/common/urlresolvers.py
Labels: READY
