Repository unicef/etools, pull requests merged in 2019-02, with the labels that each got.

#2153 [ch9620] fixed inactive workspace
  src/etools/templates/removed_workspace.html
Labels: READY

#2122 Intervention dashboard view performance tweaks
  src/etools/applications/partners/serializers/dashboards.py
  src/etools/applications/partners/tests/test_api_dashboards.py
  src/etools/applications/partners/views/dashboards.py
Labels: READY

#2148 Intervention attachment admin
  src/etools/applications/partners/admin.py
Labels: READY

#2157 Fix type filter in hact_visit_report field
  src/etools/applications/t2f/serializers/export.py
  src/etools/applications/t2f/tests/test_exports.py
Labels: READY

#2162 Update intervention frs calculation query, handle non distinct values
  src/etools/applications/partners/models.py
  src/etools/applications/partners/tests/test_api_partners.py
Labels: READY

#2163 Ci updates
  .circleci/config.yml
  .circleci/images/primary/Dockerfile
  .gitignore
  Dockerfile
  Dockerfile-dev
  Pipfile
  Pipfile.lock
  requirements.txt
  setup.py
  src/etools/applications/users/tests/factories.py
  src/etools/config/settings/base.py
  src/requirements/base.txt
  src/requirements/input/base.in
  src/requirements/input/test.in
  src/requirements/test.txt
  tasks.py
  tox.ini
Labels: READY

#2164 v6.8
  src/etools/__init__.py
Labels: READY

#2150 [ch9577] intervetnion list view allows 'end_after' filter
  src/etools/applications/partners/views/interventions_v2.py
Labels: READY

#2161 Final report
  src/etools/applications/audit/models.py
  src/etools/applications/audit/tests/base.py
  src/etools/applications/audit/tests/test_transitions.py
  src/etools/applications/audit/utils.py
Labels: READY

#2152 Set label for internal prc review type
  src/etools/applications/attachments/migrations/0014_auto_20190204_0915.py
Labels: READY, data-migration, has-migrations

#2165 dev env update
  Dockerfile-dev
Labels: READY

#2167 Pd indicator validation
  src/etools/applications/reports/serializers/v2.py
  src/etools/applications/reports/tests/test_serializers.py
  src/etools/applications/reports/tests/test_validators.py
  src/etools/applications/reports/validators.py
Labels: READY

#2151 [ch9394] fixed freeze_hact_data command
  src/etools/applications/hact/management/commands/freeze_hact_data.py
Labels: READY

#2149 [Ch6774]Another location import deadlock fix
  src/etools/libraries/locations/admin.py
Labels: READY

#2016 [ch8996] django 2.1
  .circleci/config.yml
  Pipfile
  Pipfile.lock
  src/etools/applications/audit/migrations/0013_auto_20190102_1905.py
Labels: MERGE beginning next sprint, READY, enhancement, model-migration

#2137 [ch9486] remove unicef token
  src/etools/applications/action_points/models.py
  src/etools/applications/audit/models.py
  src/etools/applications/audit/purchase_order/models.py
  src/etools/applications/email_auth/notifications/token-login.py
  src/etools/applications/tokens/__init__.py
  src/etools/applications/tokens/forms.py
  src/etools/applications/tokens/middleware.py
  src/etools/applications/tokens/templates/tokens/login.html
  src/etools/applications/tokens/tests/__init__.py
  src/etools/applications/tokens/tests/test_middleware.py
  src/etools/applications/tokens/tests/test_views.py
  src/etools/applications/tokens/urls.py
  src/etools/applications/tokens/utils.py
  src/etools/applications/tokens/views.py
  src/etools/applications/tpm/models.py
  src/etools/config/settings/base.py
  src/etools/config/urls.py
Labels: on hold

#2142 REFACTORING: EquiTrack permissions
  src/etools/applications/EquiTrack/permissions.py
  src/etools/applications/EquiTrack/utils.py
  src/etools/applications/partners/models.py
  src/etools/applications/users/tests/test_views_v3.py
  src/etools/applications/users/views.py
  src/etools/applications/users/views_v3.py
Labels: READY

#2099 t2f: remove costs models
  src/etools/applications/t2f/admin.py
  src/etools/applications/t2f/helpers/clone_travel.py
  src/etools/applications/t2f/helpers/cost_summary_calculator.py
  src/etools/applications/t2f/migrations/0009_auto_20181227_0815.py
  src/etools/applications/t2f/migrations/0010_auto_20181229_0249.py
  src/etools/applications/t2f/migrations/0014_auto_20190123_2101.py
  src/etools/applications/t2f/models.py
  src/etools/applications/t2f/serializers/export.py
  src/etools/applications/t2f/serializers/mailing.py
  src/etools/applications/t2f/serializers/travel.py
  src/etools/applications/t2f/tests/factories.py
  src/etools/applications/t2f/tests/test_cost_summary_calculator.py
  src/etools/applications/t2f/tests/test_dashboard.py
  src/etools/applications/t2f/tests/test_dsa_calculations.py
  src/etools/applications/t2f/tests/test_exports.py
  src/etools/applications/t2f/tests/test_mailing.py
  src/etools/applications/t2f/tests/test_overlapping_trips.py
  src/etools/applications/t2f/tests/test_permission_matrix.py
  src/etools/applications/t2f/tests/test_state_machine.py
  src/etools/applications/t2f/tests/test_travel.py
  src/etools/applications/t2f/tests/test_travel_details.py
  src/etools/applications/t2f/tests/test_travel_list.py
Labels: READY, model-migration

#2136 REACTORING pythonlib
  src/etools/applications/EquiTrack/permissions.py
  src/etools/applications/EquiTrack/utils.py
  src/etools/applications/audit/serializers/export.py
  src/etools/applications/audit/serializers/risks.py
  src/etools/applications/hact/management/commands/freeze_hact_data.py
  src/etools/applications/hact/migrations/0001_initial.py
  src/etools/applications/hact/models.py
  src/etools/applications/partners/migrations/0001_initial.py
  src/etools/applications/partners/migrations/0010_auto_20180514_1104.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/permissions.py
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/utils/common/utils.py
  src/etools/libraries/pythonlib/__init__.py
  src/etools/libraries/pythonlib/collections.py
  src/etools/libraries/pythonlib/datetime.py
  src/etools/libraries/pythonlib/encoders.py
  src/etools/libraries/pythonlib/hash.py
  src/etools/libraries/pythonlib/tests/__init__.py
  src/etools/libraries/pythonlib/tests/test_utils.py
Labels: READY

#2155 Pmp notifications
  src/etools/applications/partners/management/commands/send_intervention_draft_notification.py
  src/etools/applications/partners/management/commands/send_intervention_past_start_notification.py
  src/etools/applications/partners/notifications/intervention-draft.py
  src/etools/applications/partners/notifications/intervention-past-start.py
  src/etools/applications/partners/tasks.py
  src/etools/applications/partners/tests/test_commands.py
  src/etools/applications/partners/tests/test_tasks.py
  src/etools/applications/partners/tests/test_utils.py
  src/etools/applications/partners/utils.py
Labels: READY

#2172 [ch9222] expose DCT as floatt
  src/etools/applications/partners/serializers/partner_organization_v2.py
  src/etools/applications/partners/tests/test_views.py
Labels: READY

#2168 [ch9364] staff spot checks export: rename export file name
  src/etools/applications/audit/views.py
Labels: READY

#2166 Reporting requirement edit 'in termination' status perms
  src/etools/applications/partners/permissions.py
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/assets/partner/intervention_permissions.csv
Labels: READY

#2159 update package dependecies
  Pipfile
  Pipfile.lock
Labels: READY

#2135 removed legacy u'
  src/etools/applications/EquiTrack/management/commands/clear-migrations-table.py
  src/etools/applications/EquiTrack/management/commands/init-celery.py
  src/etools/applications/EquiTrack/util_scripts.py
  src/etools/applications/attachments/migrations/0003_fix_null_values.py
  src/etools/applications/attachments/tests/test_models.py
  src/etools/applications/audit/migrations/0003_fix_null_values.py
  src/etools/applications/audit/purchase_order/migrations/0002_fix_null_values.py
  src/etools/applications/audit/purchase_order/tasks.py
  src/etools/applications/audit/tests/test_views.py
  src/etools/applications/funds/migrations/0004_fix_null_values.py
  src/etools/applications/funds/models.py
  src/etools/applications/funds/tests/test_models.py
  src/etools/applications/management/tasks.py
  src/etools/applications/management/tests/test_models.py
  src/etools/applications/partners/forms.py
  src/etools/applications/partners/migrations/0004_fix_null_values.py
  src/etools/applications/partners/mixins.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/serializers/dashboards.py
  src/etools/applications/partners/serializers/partner_organization_v2.py
  src/etools/applications/partners/synchronizers.py
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/tests/test_export_agreement.py
  src/etools/applications/partners/tests/test_export_intervention.py
  src/etools/applications/partners/tests/test_export_partner.py
  src/etools/applications/partners/tests/test_exports.py
  src/etools/applications/partners/tests/test_models.py
  src/etools/applications/partners/tests/test_serializers.py
  src/etools/applications/partners/tests/test_tasks.py
  src/etools/applications/partners/tests/test_views.py
  src/etools/applications/partners/views/interventions_v2.py
  src/etools/applications/publics/migrations/0002_fix_null_values.py
  src/etools/applications/publics/tests/test_models.py
  src/etools/applications/reports/management/commands/init-result-type.py
  src/etools/applications/reports/migrations/0002_fix_null_values.py
  src/etools/applications/reports/models.py
  src/etools/applications/reports/tests/test_models.py
  src/etools/applications/t2f/migrations/0002_fix_null_values.py
  src/etools/applications/t2f/tests/test_models.py
  src/etools/applications/t2f/tests/test_travel_details.py
  src/etools/applications/t2f/tests/test_travel_list.py
  src/etools/applications/tpm/tests/test_views.py
  src/etools/applications/tpm/tpmpartners/tasks.py
  src/etools/applications/users/admin.py
  src/etools/applications/users/migrations/0003_fix_null_values.py
  src/etools/applications/users/models.py
  src/etools/applications/users/tasks.py
  src/etools/applications/users/tests/test_models.py
  src/etools/applications/users/tests/test_views.py
  src/etools/applications/users/tests/test_views_v3.py
  src/etools/applications/vision/migrations/0002_fix_null_values.py
  src/etools/applications/vision/models.py
  src/etools/applications/vision/tasks.py
  src/etools/applications/vision/tests/test_models.py
  src/etools/applications/vision/tests/test_tasks.py
Labels: READY

#2134 REFACTORING djangolib
  src/etools/applications/EquiTrack/tests/test_urls.py
  src/etools/applications/EquiTrack/urlresolvers.py
  src/etools/applications/EquiTrack/utils.py
  src/etools/applications/action_points/models.py
  src/etools/applications/action_points/serializers.py
  src/etools/applications/action_points/tests/factories.py
  src/etools/applications/audit/models.py
  src/etools/applications/audit/purchase_order/models.py
  src/etools/applications/firms/utils.py
  src/etools/applications/hact/migrations/0001_initial.py
  src/etools/applications/partners/migrations/0001_initial.py
  src/etools/applications/partners/migrations/0010_auto_20180514_1104.py
  src/etools/applications/partners/permissions.py
  src/etools/applications/partners/tasks.py
  src/etools/applications/partners/tests/test_api.py
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/t2f/models.py
  src/etools/applications/tokens/utils.py
  src/etools/applications/tpm/export/serializers.py
  src/etools/applications/tpm/models.py
  src/etools/applications/utils/common/tests/test_utils.py
  src/etools/applications/utils/common/urlresolvers.py
  src/etools/applications/utils/common/utils.py
  src/etools/libraries/djangolib/tests/__init__.py
  src/etools/libraries/djangolib/urlresolvers.py
  src/etools/libraries/djangolib/utils.py
  src/etools/libraries/locations/tests/test_api.py
  src/etools/libraries/pythonlib/urlresolvers.py
  src/etools/libraries/tests/api_checker.py
  src/etools/libraries/tests/utils.py
  src/etools/libraries/utils/test/__init__.py
Labels: READY

#2169 t2f cleaning
  src/etools/applications/t2f/serializers/export.py
  src/etools/applications/t2f/tests/test_exports.py
  src/etools/applications/t2f/tests/test_travel_list.py
  src/etools/applications/t2f/urls.py
  src/etools/applications/t2f/views/exports.py
Labels: READY

#2176 admin links: get vision api from settings
  src/etools/applications/EquiTrack/templatetags/etools.py
  src/etools/applications/users/templates/admin/users/country/change_form.html
Labels: READY

#2178 [ch9019] alternative
  Pipfile
  Pipfile.lock
  src/etools/applications/action_points/export/renderers.py
  src/etools/applications/action_points/export/serializers.py
Labels: READY

#2174 Intervention attachment admin
  src/etools/applications/partners/admin.py
Labels: READY

#2179 Engagement attachment links
  src/etools/applications/audit/serializers/attachments.py
  src/etools/applications/audit/tests/test_attachment_link_views.py
  src/etools/applications/audit/tests/test_views.py
  src/etools/applications/audit/urls.py
  src/etools/applications/audit/views.py
Labels: READY

#2177 Modify PCA templates
  src/etools/templates/partners/pca/english_pdf.html
  src/etools/templates/partners/pca/french_pdf.html
  src/etools/templates/partners/pca/ifrc_english_pdf.html
  src/etools/templates/partners/pca/ifrc_french_pdf.html
  src/etools/templates/partners/pca/portuguese_pdf.html
  src/etools/templates/partners/pca/russian_pdf.html
  src/etools/templates/partners/pca/spanish_pdf.html
Labels: READY

#2186 [ch9676] remove total_amount_of_ineligible_expenditure has mandatory field
  src/etools/applications/audit/transitions/conditions.py
Labels: READY

#2189 [CH7894] PCA templates typo fixes
  src/etools/templates/partners/pca/english_pdf.html
  src/etools/templates/partners/pca/french_pdf.html
  src/etools/templates/partners/pca/ifrc_english_pdf.html
  src/etools/templates/partners/pca/ifrc_french_pdf.html
  src/etools/templates/partners/pca/spanish_pdf.html
Labels: WIP

#2185 update develop with Master
  src/etools/applications/EquiTrack/auth.py
  src/etools/templates/partners/pca/english_pdf.html
  src/etools/templates/partners/pca/french_pdf.html
  src/etools/templates/partners/pca/ifrc_english_pdf.html
  src/etools/templates/partners/pca/ifrc_french_pdf.html
  src/etools/templates/partners/pca/portuguese_pdf.html
  src/etools/templates/partners/pca/russian_pdf.html
  src/etools/templates/partners/pca/spanish_pdf.html
Labels: READY

#2198 Ensure code is set for Intervention Attachment formset
  src/etools/applications/partners/admin.py
Labels: READY

#2199 Fix issues generating final report
  src/etools/applications/audit/models.py
  src/etools/applications/audit/utils.py
Labels: READY

#2196 Travel Activity is required for T2FActionPoint models
  src/etools/applications/audit/admin.py
  src/etools/applications/audit/forms.py
  src/etools/applications/t2f/admin.py
  src/etools/applications/t2f/forms.py
Labels: READY

#2201 Correct InterventionAttachment admin handling
  src/etools/applications/partners/admin.py
Labels: READY

#2203 Override attachment field value in InterventionAttachmentInline
  src/etools/applications/partners/admin.py
  src/etools/applications/partners/forms.py
Labels: READY

#2208 Remove attachment_file from list display in InterventionAttachment admin
  src/etools/applications/partners/admin.py
Labels: READY

#2209 Update way generated file is saved
  src/etools/applications/audit/tests/test_transitions.py
  src/etools/applications/audit/utils.py
Labels: READY

#2211 Reduce permissions for Traveler group
  src/etools/applications/t2f/permissions.py
Labels: READY
