Repository unicef/etools, pull requests merged in 2019-11, with the labels that each got.

#2565 PSEA notifications
  src/etools/applications/psea/models.py
  src/etools/applications/psea/notifications/assessment-assigned.py
  src/etools/applications/psea/tests/test_models.py
  src/etools/applications/psea/validation.py
Labels: READY

#2564 PSEA action point email assigned
  src/etools/applications/action_points/signals.py
  src/etools/applications/psea/__init__.py
  src/etools/applications/psea/apps.py
  src/etools/applications/psea/models.py
  src/etools/applications/psea/tests/test_models.py
  src/etools/applications/psea/tests/test_views.py
Labels: READY

#2563 Prevent external users being able to edit focal points
  src/etools/applications/psea/models.py
  src/etools/applications/psea/permission_matrix/assessment_permissions.csv
  src/etools/applications/psea/permissions.py
  src/etools/applications/psea/tests/test_views.py
Labels: READY

#2571 Ensure country override set when adding external user to tenant
  src/etools/applications/users/serializers_v3.py
  src/etools/applications/users/tests/test_views_v3.py
Labels: READY

#2569 Assessment date not required in initial states
  src/etools/applications/psea/serializers.py
  src/etools/applications/psea/tests/test_views.py
Labels: READY

#2577 Handle blank value for assessment date
  src/etools/applications/psea/serializers.py
  src/etools/applications/psea/tests/test_views.py
Labels: READY

#2580 Add html message content for psea notifications
  src/etools/applications/psea/notifications/assessment-action_point_assigned.py
  src/etools/applications/psea/notifications/assessment-assigned.py
  src/etools/applications/psea/notifications/assessment-assigned_focal.py
  src/etools/applications/psea/notifications/assessment-final.py
  src/etools/applications/psea/notifications/assessment-rejected.py
  src/etools/applications/psea/notifications/assessment-submitted.py
Labels: READY

#2583 Reporting requirements can be added for contingency PDs in signed state
  src/etools/applications/partners/permission_matrix/intervention_permissions.csv
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/tests/test_api_interventions.py
Labels: READY

#2582 Allow unicef users to add action points
  src/etools/applications/audit/management/commands/update_audit_permissions.py
  src/etools/applications/audit/tests/test_views.py
Labels: READY

#2575 [ch13835] FAM change permissions
  src/etools/applications/audit/management/commands/update_audit_permissions.py
Labels: READY

#2568 [ch15276] FAM notifications
  src/etools/applications/audit/admin.py
  src/etools/applications/audit/management/commands/update_audit_permissions.py
  src/etools/applications/audit/migrations/0019_engagement_users_notified.py
  src/etools/applications/audit/models.py
  src/etools/applications/audit/permissions.py
  src/etools/applications/audit/serializers/engagement.py
  src/etools/applications/audit/tests/base.py
  src/etools/applications/audit/tests/test_email.py
  src/etools/applications/audit/tests/test_views.py
  src/etools/applications/firms/serializers.py
Labels: READY

#2567 Update length of PartnerStaffMember title
  src/etools/applications/partners/migrations/0039_auto_20191106_1345.py
  src/etools/applications/partners/models.py
Labels: READY

#2561 Amendment signed date validation changes
  src/etools/applications/partners/serializers/agreements_v2.py
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIAgreements/get__api_v2_agreements_5__None.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIAgreements/get__api_v2_agreements__None.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIAgreements/get__api_v2_agreements_amendments__None.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_101__None.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions__None.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_amendments__None.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_applied-indicators__None.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_indicators__None.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_map__None.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestPartners/get__api_v2_partners_101__None.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestPartners/get__api_v2_partners__None.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestPartners/get__api_v2_partners_not_programmatic_visit__None.response.json
  src/etools/applications/partners/tests/test_api_agreements.py
  src/etools/applications/partners/tests/test_views.py
Labels: READY

#2524 [Ch15316] location remap issues
  src/etools/config/settings/local.py
  src/etools/libraries/locations/task_utils.py
  src/etools/libraries/locations/tasks.py
  src/etools/libraries/locations/tests/test_tasks.py
Labels: READY

#2472 Action Points reference number moved to db
  src/etools/applications/action_points/migrations/0011_actionpoint_reference_number.py
  src/etools/applications/action_points/models.py
  src/etools/applications/action_points/signals.py
Labels: MERGE beginning next sprint, READY

#2479 [Ch13203] Intervention amendment notifications
  src/etools/applications/partners/notifications/intervention-amendment-added.py
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/tests/test_views.py
  src/etools/applications/partners/utils.py
  src/etools/applications/partners/views/interventions_v2.py
Labels: changes-requested

#2584 [ch16534] hact dash remove hact active filter
  src/etools/applications/hact/models.py
  src/etools/applications/partners/models.py
Labels: READY

#2576 7.6
  src/etools/__init__.py
Labels: READY

#2562 update reqs
  Pipfile
  Pipfile.lock
  src/etools/applications/audit/urls.py
  src/etools/applications/management/urls.py
  src/etools/applications/psea/urls.py
  src/etools/applications/tpm/urls.py
  src/etools/libraries/azure_graph_api/client.py
  src/etools/libraries/azure_graph_api/tests/test_client.py
  src/etools/libraries/azure_graph_api/utils.py
  src/etools/libraries/locations/urls.py
Labels: MERGE beginning next sprint

#2591 Correct action point migration
  src/etools/applications/action_points/migrations/0011_actionpoint_reference_number.py
Labels: READY

#2593 Handle FakeTenant in action point migration gracefully
  src/etools/applications/action_points/migrations/0011_actionpoint_reference_number.py
Labels: READY

#2462 Doc Type cleanup
  Pipfile
  Pipfile.lock
  src/etools/applications/attachments/management/commands/cleanup_file_types.py
  src/etools/applications/attachments/migrations/0001_initial.py
  src/etools/applications/attachments/migrations/0016_auto_20190708_1607.py
  src/etools/applications/attachments/models.py
  src/etools/applications/attachments/tests/test_commands.py
  src/etools/applications/attachments/tests/test_models.py
  src/etools/applications/attachments/tests/test_utils.py
  src/etools/applications/attachments/tests/test_views.py
  src/etools/applications/audit/serializers/engagement.py
  src/etools/applications/audit/tests/base.py
  src/etools/applications/audit/tests/test_views.py
  src/etools/applications/audit/utils.py
  src/etools/applications/core/data/attachments_file_types.json
  src/etools/applications/partners/tests/test_api_agreements.py
  src/etools/applications/partners/tests/test_api_partners.py
  src/etools/applications/partners/tests/test_api_prp.py
  src/etools/applications/partners/tests/test_commands.py
  src/etools/applications/partners/tests/test_tasks.py
  src/etools/applications/partners/tests/test_views.py
  src/etools/applications/partners/utils.py
  src/etools/applications/psea/serializers.py
  src/etools/applications/psea/tests/test_views.py
  src/etools/applications/t2f/tests/test_travel_details.py
  src/etools/applications/tpm/serializers/attachments.py
  src/etools/applications/tpm/tests/test_views.py
Labels: READY

#2595 Update unicef attachments reqs to 0.7.0
  Pipfile
  Pipfile.lock
Labels: READY

#2588 dockerignore
  .dockerignore
Labels: READY

#2598 Update reference to tests files in migration
  src/etools/applications/action_points/migrations/0011_actionpoint_reference_number.py
Labels: READY

#2600 remove libc-dev
  Dockerfile
Labels: READY

#2538 Move offices model to tenants
  src/etools/applications/action_points/migrations/0012_auto_20191011_1303.py
  src/etools/applications/action_points/models.py
  src/etools/applications/action_points/serializers.py
  src/etools/applications/action_points/tests/factories.py
  src/etools/applications/action_points/tests/test_views.py
  src/etools/applications/audit/serializers/engagement.py
  src/etools/applications/audit/tests/test_views.py
  src/etools/applications/core/tests/test_middleware.py
  src/etools/applications/environment/tests/test_models.py
  src/etools/applications/partners/migrations/0040_auto_20191011_1429.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIAgreements/get__api_v2_agreements_5__None.response.json
  src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_101__None.response.json
  src/etools/applications/partners/tests/test_views.py
  src/etools/applications/psea/serializers.py
  src/etools/applications/psea/tests/test_views.py
  src/etools/applications/reports/admin.py
  src/etools/applications/reports/migrations/0020_office.py
  src/etools/applications/reports/migrations/0021_auto_20191011_1201.py
  src/etools/applications/reports/migrations/0022_userprofileoffice.py
  src/etools/applications/reports/migrations/0023_auto_20191014_1546.py
  src/etools/applications/reports/models.py
  src/etools/applications/reports/serializers/v2.py
  src/etools/applications/reports/tests/factories.py
  src/etools/applications/reports/tests/test_views.py
  src/etools/applications/reports/views/v2.py
  src/etools/applications/t2f/migrations/0016_auto_20191011_1348.py
  src/etools/applications/t2f/models.py
  src/etools/applications/t2f/tests/factories.py
  src/etools/applications/t2f/tests/test_exports.py
  src/etools/applications/tpm/migrations/0009_auto_20191014_1304.py
  src/etools/applications/tpm/migrations/0010_auto_20191029_1826.py
  src/etools/applications/tpm/models.py
  src/etools/applications/tpm/serializers/visit.py
  src/etools/applications/tpm/tests/_api_checker/etools.applications.tpm.tests.test_api/TestAPIActivities/get__api_tpm_activities__None.response.json
  src/etools/applications/tpm/tests/factories.py
  src/etools/applications/tpm/tests/test_api.py
  src/etools/applications/tpm/tests/test_views.py
  src/etools/applications/users/admin.py
  src/etools/applications/users/migrations/0013_auto_20191010_1621.py
  src/etools/applications/users/models.py
  src/etools/applications/users/serializers.py
  src/etools/applications/users/tests/factories.py
  src/etools/applications/users/tests/test_admin.py
  src/etools/applications/users/tests/test_models.py
  src/etools/applications/users/tests/test_views.py
  src/etools/applications/users/views.py
  src/etools/applications/users/views_v2.py
  src/etools/config/settings/local.py
  src/etools/config/urls.py
  src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPILocations/get__api_locations-light__None.response.json
  src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPILocations/get__api_locations__None.response.json
Labels: MERGE beginning next sprint, READY

#2605 Fix admin user office
  src/etools/applications/reports/admin.py
  src/etools/applications/reports/migrations/0023_auto_20191014_1546.py
  src/etools/applications/reports/migrations/0024_auto_20191122_1559.py
  src/etools/applications/users/admin.py
Labels: READY

#2603 Spot check sections/offices fields added
  src/etools/applications/audit/management/commands/update_audit_permissions.py
  src/etools/applications/audit/migrations/0020_auto_20191125_2045.py
  src/etools/applications/audit/models.py
  src/etools/applications/audit/serializers/engagement.py
  src/etools/applications/audit/tests/test_views.py
  src/etools/applications/audit/views.py
Labels: READY

#2610 Amendment signed date validation changes
  src/etools/applications/partners/serializers/agreements_v2.py
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/tests/test_api_agreements.py
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/tests/test_views.py
Labels: READY

#2612 Correct validation message for PD amendment signed date
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/tests/test_api_interventions.py
Labels: READY
