Repository unicef/etools, pull requests merged in 2021-09, with the labels that each got.

#3075 [ePD] Update etools-validator package & fix tests
  src/etools/applications/audit/purchase_order/tests/test_synchronizers.py
  src/etools/applications/audit/purchase_order/tests/test_tasks.py
  src/etools/applications/audit/tests/test_views.py
  src/etools/applications/audit/views.py
  src/etools/applications/core/tests/test_userprofile_tags.py
  src/etools/applications/environment/tests/test_models.py
  src/etools/applications/field_monitoring/data_collection/tests/test_offline.py
  src/etools/applications/funds/tests/test_views.py
  src/etools/applications/hact/tests/test_tasks.py
  src/etools/applications/management/tests/test_views.py
  src/etools/applications/offline/tests/test_fields.py
  src/etools/applications/partners/tests/test_api_partners.py
  src/etools/applications/partners/tests/test_prp_sync.py
  src/etools/applications/partners/tests/test_validation_interventions.py
  src/etools/applications/publics/tests/test_synchronizers.py
  src/etools/applications/users/tests/test_admin.py
  src/etools/applications/users/views_v3.py
  src/etools/libraries/azure_graph_api/tests/test_client.py
  src/etools/libraries/azure_graph_api/tests/test_tasks.py
  src/etools/libraries/azure_graph_api/tests/test_utils.py
  src/etools/libraries/monitoring/tests/test_checks.py
  src/etools/libraries/monitoring/tests/test_views.py
Labels: READY, ePD

#3059 [ePD] Update transition error structure: provide more info about required fields
  src/etools/applications/partners/tests/test_v3_interventions.py
  src/etools/applications/partners/validation/interventions.py
Labels: READY, ePD

#2929 [ePD] Add expired status to PD
  src/etools/applications/partners/migrations/0090_alter_intervention_status.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/tasks.py
  src/etools/applications/partners/tests/test_tasks.py
Labels: READY, ePD

#3076 [FAM] Add search functionality to users api
  src/etools/applications/users/tests/test_views_v3.py
  src/etools/applications/users/views_v3.py
Labels: READY

#3079 [PMP] Fix issue when hact values are not updated in case of grouping activities.
  src/etools/applications/field_monitoring/planning/models.py
  src/etools/applications/field_monitoring/planning/tests/test_views.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/serializers/partner_organization_v2.py
  src/etools/applications/partners/tests/test_api_partners.py
Labels: READY

#3082 [ePD] Fix missing emails for PRC "Send Notifications" button
  src/etools/applications/partners/notifications/intervention-prc-review-notification.py
Labels: READY, ePD

#2766 [ePD] Transition active PD to new CP
  src/etools/applications/core/data/enabled_celery_tasks.json
  src/etools/applications/partners/tasks.py
  src/etools/applications/partners/tests/test_tasks.py
Labels: READY, ePD

#3087 Epd tweaks
  src/etools/applications/partners/models.py
  src/etools/applications/partners/permission_matrix/intervention_permissions.csv
  src/etools/applications/partners/permissions.py
  src/etools/applications/partners/serializers/interventions_v3.py
  src/etools/applications/partners/tests/factories.py
  src/etools/applications/partners/tests/test_amendments.py
  src/etools/applications/partners/tests/test_epd_management/test_risks.py
  src/etools/applications/partners/tests/test_v3_serializers_intervention.py
  src/etools/applications/partners/validation/interventions.py
  src/etools/applications/partners/views/interventions_v3_actions.py
Labels: WIP

#3088 Make only focal points able to edit
  src/etools/applications/partners/permission_matrix/intervention_permissions.csv
  src/etools/applications/partners/permissions.py
  src/etools/applications/partners/tests/test_api_amendments.py
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/tests/test_api_prp.py
  src/etools/applications/partners/tests/test_epd_management/base.py
  src/etools/applications/partners/tests/test_models.py
  src/etools/applications/partners/tests/test_utils.py
  src/etools/applications/partners/tests/test_v3_intervention_activity.py
  src/etools/applications/partners/tests/test_v3_intervention_lower_results.py
  src/etools/applications/partners/tests/test_v3_interventions.py
  src/etools/applications/partners/tests/test_views.py
  src/etools/applications/reports/tests/test_v3_views.py
Labels: READY

#3089 Sites for ePD
  src/etools/applications/partners/amendment_utils.py
  src/etools/applications/partners/migrations/0091_intervention_sites.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/permission_matrix/intervention_permissions.csv
  src/etools/applications/partners/permissions.py
  src/etools/applications/partners/serializers/interventions_v3.py
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/tests/test_v3_interventions.py
Labels: READY

#3090 [ePD] Supply contribution disappear at Amendment merge
  src/etools/applications/partners/admin.py
  src/etools/applications/partners/amendment_utils.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/tests/test_amendments.py
  src/etools/applications/partners/tests/test_v3_pmp_dropdowns.py
  src/etools/applications/partners/views/v3.py
Labels: READY, ePD

#3091 [ePD] Add activation protocol PD field
  src/etools/applications/partners/migrations/0092_intervention_activation_protocol.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/permission_matrix/intervention_permissions.csv
  src/etools/applications/partners/serializers/interventions_v3.py
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/tests/test_export_intervention.py
  src/etools/applications/partners/tests/test_v3_interventions.py
Labels: READY, ePD

#3092 [ePD] Create PD HTML Template for export to PDF.
  src/etools/applications/partners/models.py
  src/etools/applications/partners/serializers/interventions_v3.py
  src/etools/applications/partners/templates/pd/detail.html
  src/etools/applications/partners/tests/test_v3_interventions.py
  src/etools/applications/partners/tests/test_v3_serializers_intervention.py
  src/etools/applications/partners/views/interventions_v3.py
  src/etools/applications/reports/models.py
Labels: READY, ePD

#3093 [ePD] When partner or unicef focal points are updated on the main intervention, any amendments do not reflect the updates
  src/etools/applications/partners/models.py
  src/etools/applications/partners/signals.py
  src/etools/applications/partners/tests/test_amendments.py
Labels: READY, ePD

#3098 [ch26903] hide fund commitment button from admin
  src/etools/applications/users/admin.py
Labels: READY

#3097 [PMP] Empty monitoring activities
  src/etools/applications/field_monitoring/data_collection/migrations/0003_auto_20210923_1505.py
  src/etools/applications/field_monitoring/data_collection/models.py
  src/etools/applications/field_monitoring/data_collection/serializers.py
  src/etools/applications/field_monitoring/data_collection/tests/factories.py
  src/etools/applications/field_monitoring/planning/models.py
  src/etools/applications/field_monitoring/planning/tests/test_models.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/serializers/partner_organization_v2.py
Labels: READY

#3094 [PMP] [ch26828 - 1] Disallow similar pairs of intervention + cp output for result links
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/tests/test_api_interventions.py
Labels: READY
