Repository unicef/etools, pull requests merged in 2021-06, with the labels that each got.

#3009 [ch25833] PSEA fix assign notifications
  src/etools/applications/psea/admin.py
  src/etools/applications/psea/models.py
  src/etools/applications/psea/notifications/assessment-action_point_assigned.py
  src/etools/applications/psea/tests/test_models.py
Labels: READY

#3010 locations archived "fix"
  src/etools/applications/field_monitoring/fm_settings/models.py
Labels: READY

#3004 [ch25658] changed psea labels
  src/etools/applications/psea/migrations/0014_auto_20210518_1411.py
  src/etools/applications/psea/models.py
Labels: READY

#3011 import location fix
  src/etools/libraries/locations/tasks.py
Labels: READY

#3002 psea fixed field lenght
  src/etools/applications/psea/migrations/0015_auto_20210607_1657.py
  src/etools/applications/psea/models.py
Labels: READY

#3012 prp api: allow filter by number
  src/etools/applications/partners/views/prp_v1.py
Labels: READY

#2997 [ePD] Intervention PRC
  src/etools/applications/partners/migrations/0081_auto_20210517_1039.py
  src/etools/applications/partners/migrations/0082_auto_20210601_1302.py
  src/etools/applications/partners/migrations/0083_auto_20210607_1956.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/notifications/intervention-prc-review-notification.py
  src/etools/applications/partners/permission_matrix/intervention_permissions.csv
  src/etools/applications/partners/permissions.py
  src/etools/applications/partners/serializers/interventions_v3.py
  src/etools/applications/partners/serializers/v3.py
  src/etools/applications/partners/signals.py
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/tests/test_epd_management/base.py
  src/etools/applications/partners/tests/test_prc_review.py
  src/etools/applications/partners/tests/test_v3_interventions.py
  src/etools/applications/partners/urls_v3.py
  src/etools/applications/partners/validation/interventions.py
  src/etools/applications/partners/views/interventions_v3.py
  src/etools/applications/partners/views/interventions_v3_actions.py
  src/etools/applications/partners/views/v3.py
  src/etools/applications/users/migrations/0016_auto_20210519_1038.py
  src/etools/applications/users/tests/test_models.py
Labels: ePD

#3005 [ePD] New field structure for Input level from PD activities
  src/etools/applications/partners/tests/test_v3_intervention_activity.py
  src/etools/applications/reports/migrations/0033_auto_20210520_1310.py
  src/etools/applications/reports/migrations/0034_auto_20210520_1353.py
  src/etools/applications/reports/migrations/0035_auto_20210608_0915.py
  src/etools/applications/reports/models.py
  src/etools/applications/reports/serializers/v2.py
  src/etools/applications/reports/tests/factories.py
Labels: READY, ePD

#3007 [ePD] Allow Supply Contribution to be made by Partner also
  src/etools/applications/partners/migrations/0081_auto_20210521_0929.py
  src/etools/applications/partners/migrations/0084_merge_20210608_0951.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/serializers/interventions_v3.py
  src/etools/applications/partners/tests/test_models.py
  src/etools/applications/partners/tests/test_v3_interventions.py
  src/etools/applications/partners/views/interventions_v3.py
Labels: READY, ePD

#2982 update postgres image for tests
  .circleci/config.yml
  docker-compose.yml
  docker-compose_v2.yml
Labels: READY

#3003 [ePD] Intervention amendments
  src/etools/applications/partners/admin.py
  src/etools/applications/partners/amendment_utils.py
  src/etools/applications/partners/migrations/0080_auto_20210608_0941.py
  src/etools/applications/partners/migrations/0084_merge_20210608_0948.py
  src/etools/applications/partners/migrations/0085_merge_20210609_1507.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/permission_matrix/intervention_permissions.csv
  src/etools/applications/partners/permissions.py
  src/etools/applications/partners/serializers/exports/interventions.py
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/serializers/interventions_v3.py
  src/etools/applications/partners/serializers/v3.py
  src/etools/applications/partners/signals.py
  src/etools/applications/partners/tests/factories.py
  src/etools/applications/partners/tests/test_amendments.py
  src/etools/applications/partners/tests/test_api_amendments.py
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/tests/test_epd_management/base.py
  src/etools/applications/partners/tests/test_epd_management/test_amendments.py
  src/etools/applications/partners/tests/test_export_intervention.py
  src/etools/applications/partners/tests/test_models.py
  src/etools/applications/partners/tests/test_validation_interventions.py
  src/etools/applications/partners/tests/test_views.py
  src/etools/applications/partners/urls_v3.py
  src/etools/applications/partners/validation/interventions.py
  src/etools/applications/partners/views/interventions_v3_actions.py
  src/etools/applications/reports/models.py
  src/etools/applications/reports/signals.py
Labels: ePD

#3018 [FM] Rename Person Responsible to Visit Lead
  src/etools/applications/field_monitoring/data_collection/offline/synchronizer.py
  src/etools/applications/field_monitoring/data_collection/tests/test_offline.py
  src/etools/applications/field_monitoring/data_collection/tests/test_views.py
  src/etools/applications/field_monitoring/permissions.py
  src/etools/applications/field_monitoring/planning/activity_validation/permissions.py
  src/etools/applications/field_monitoring/planning/activity_validation/permissions_matrix.csv
  src/etools/applications/field_monitoring/planning/admin.py
  src/etools/applications/field_monitoring/planning/filters.py
  src/etools/applications/field_monitoring/planning/migrations/0010_auto_20210614_0738.py
  src/etools/applications/field_monitoring/planning/models.py
  src/etools/applications/field_monitoring/planning/notifications/activity-staff-submit.py
  src/etools/applications/field_monitoring/planning/serializers.py
  src/etools/applications/field_monitoring/planning/signals.py
  src/etools/applications/field_monitoring/planning/tests/factories.py
  src/etools/applications/field_monitoring/planning/tests/test_views.py
  src/etools/applications/field_monitoring/planning/transitions/permissions.py
  src/etools/applications/field_monitoring/planning/views.py
  src/etools/applications/psea/notifications/assessment-action_point_assigned.py
  utils/trigger_redeploy.py
Labels: READY

#3019 [ch21780] psea-export-layout
  src/etools/applications/psea/templates/psea_pdf.html
Labels: READY

#3016 [ch15926] increase value limit to 20 chars
  src/etools/applications/reports/migrations/0026_auto_20210611_1403.py
  src/etools/applications/reports/models.py
Labels: READY

#3015 [ePD] Intervention amendments update
  src/etools/applications/partners/amendment_utils.py
  src/etools/applications/partners/filters.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/tests/test_amendments.py
  src/etools/applications/partners/tests/test_api_amendments.py
  src/etools/applications/partners/tests/test_v3_interventions.py
  src/etools/applications/partners/tests/test_views.py
  src/etools/applications/partners/views/interventions_v2.py
  src/etools/applications/partners/views/interventions_v3_actions.py
Labels: READY, ePD

#3020 [ch21780] psea amend export
  src/etools/applications/psea/serializers.py
Labels: READY

#3017 [ch25659] psea nfr attachment
  src/etools/applications/core/data/attachments_file_types.json
  src/etools/applications/psea/admin.py
  src/etools/applications/psea/models.py
  src/etools/applications/psea/notifications/assessment-final.py
  src/etools/applications/psea/permission_matrix/assessment_permissions.csv
  src/etools/applications/psea/serializers.py
  src/etools/applications/psea/tests/test_models.py
  src/etools/applications/psea/views.py
  src/etools/applications/tpm/admin.py
Labels: READY

#3021 [ch25833] fix psea ap notification
  src/etools/applications/psea/notifications/assessment-action_point_assigned.py
Labels: READY

#3014 [ePD] Add `Accept on behalf of Partner` action for UNICEF user
  src/etools/applications/partners/migrations/0086_intervention_accepted_on_behalf_of_partner.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/notifications/intervention-unicef-accepted-behalf-of-partner.py
  src/etools/applications/partners/serializers/interventions_v3.py
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/tests/test_export_intervention.py
  src/etools/applications/partners/tests/test_v3_interventions.py
  src/etools/applications/partners/tests/test_v3_serializers_intervention.py
  src/etools/applications/partners/urls_v3.py
  src/etools/applications/partners/views/interventions_v3_actions.py
Labels: ePD

#3023 [ePD] Intervention amendments: no-review type, custom names in difference, save difference on review
  src/etools/applications/partners/amendment_utils.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/serializers/interventions_v3.py
  src/etools/applications/partners/tests/test_amendments.py
  src/etools/applications/partners/tests/test_api_amendments.py
  src/etools/applications/partners/validation/interventions.py
  src/etools/applications/partners/views/interventions_v3_actions.py
  src/etools/applications/reports/models.py
Labels: READY, ePD

#3025 [ch25833] fix psea notification
  src/etools/applications/psea/notifications/assessment-action_point_assigned.py
Labels: READY
