Repository unicef/etools, pull requests merged in 2021-08, with the labels that each got.

#3037 [ch25641] action point intervetion list serializer
  src/etools/applications/action_points/serializers.py
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/tests/test_views.py
Labels: READY

#3038 [ch26142] country: added bi dashboard field
  src/etools/applications/users/migrations/0016_country_custom_dashboards.py
  src/etools/applications/users/models.py
  src/etools/applications/users/serializers_v3.py
Labels: READY

#3040 [ch26287] output programme area
  src/etools/applications/reports/migrations/0027_auto_20210714_2147.py
  src/etools/applications/reports/models.py
  src/etools/applications/reports/synchronizers.py
  src/etools/applications/reports/tests/test_synchronizers.py
Labels: READY

#3046 [ePD] Cancel button should only be visible to focal points and business owner
  src/etools/applications/partners/serializers/interventions_v3.py
  src/etools/applications/partners/tests/test_v3_serializers_intervention.py
Labels: READY

#3049 [ePD] Backend error on Exporting list of agreements
  src/etools/applications/partners/tests/test_v3_agreements.py
  src/etools/applications/partners/views/agreements_v3.py
Labels: READY, ePD

#3050 [ch26385] action point admin
  src/etools/applications/action_points/admin.py
  src/etools/applications/field_monitoring/planning/admin.py
  src/etools/applications/psea/admin.py
  src/etools/applications/t2f/admin.py
  src/etools/applications/tpm/admin.py
  src/etools/applications/tpm/migrations/0006_auto_20180522_0736.py
  src/etools/applications/tpm/models.py
Labels: READY

#3053 Dj3 to develop
  .circleci/config.yml
  .circleci/images/primary/Dockerfile
  Dockerfile-base
  Pipfile
  Pipfile.lock
  src/etools/applications/audit/migrations/0001_initial.py
  src/etools/applications/audit/models.py
  src/etools/applications/audit/tests/test_views.py
  src/etools/applications/environment/migrations/0001_initial.py
  src/etools/applications/environment/models.py
  src/etools/applications/field_monitoring/data_collection/migrations/0001_initial_20191113.py
  src/etools/applications/field_monitoring/data_collection/models.py
  src/etools/applications/field_monitoring/data_collection/tests/test_views.py
  src/etools/applications/field_monitoring/fm_settings/migrations/0001_initial_20191113.py
  src/etools/applications/field_monitoring/fm_settings/models.py
  src/etools/applications/hact/migrations/0001_initial.py
  src/etools/applications/hact/models.py
  src/etools/applications/partners/migrations/0001_initial.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/permissions.py
  src/etools/applications/publics/migrations/0001_initial.py
  src/etools/applications/reports/migrations/0009_auto_20180606_1807.py
  src/etools/applications/reports/migrations/0013_auto_20180709_1348.py
  src/etools/applications/reports/migrations/0014_auto_20181229_0249.py
  src/etools/applications/reports/models.py
  src/etools/applications/t2f/migrations/0001_initial.py
  src/etools/applications/t2f/models.py
  src/etools/applications/t2f/tests/test_exports.py
  src/etools/applications/users/migrations/0016_country_custom_dashboards.py
  src/etools/applications/users/models.py
  src/etools/config/settings/base.py
  src/etools/libraries/djangolib/tests/utils.py
  tox.ini
Labels: READY

#3055 Epd dj3
  .circleci/config.yml
  .circleci/images/primary/Dockerfile
  Dockerfile-base
  Pipfile
  Pipfile.lock
  src/etools/applications/audit/migrations/0001_initial.py
  src/etools/applications/audit/models.py
  src/etools/applications/audit/tests/test_views.py
  src/etools/applications/comments/tests/test_views.py
  src/etools/applications/environment/migrations/0001_initial.py
  src/etools/applications/environment/models.py
  src/etools/applications/field_monitoring/data_collection/migrations/0001_initial_20191113.py
  src/etools/applications/field_monitoring/data_collection/models.py
  src/etools/applications/field_monitoring/data_collection/tests/test_views.py
  src/etools/applications/field_monitoring/fm_settings/migrations/0001_initial_20191113.py
  src/etools/applications/field_monitoring/fm_settings/models.py
  src/etools/applications/hact/migrations/0001_initial.py
  src/etools/applications/hact/models.py
  src/etools/applications/partners/migrations/0001_initial.py
  src/etools/applications/partners/migrations/0080_auto_20210608_0941.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/permissions.py
  src/etools/applications/publics/migrations/0001_initial.py
  src/etools/applications/reports/migrations/0009_auto_20180606_1807.py
  src/etools/applications/reports/migrations/0013_auto_20180709_1348.py
  src/etools/applications/reports/migrations/0014_auto_20181229_0249.py
  src/etools/applications/reports/migrations/0037_merge_20210805_1609.py
  src/etools/applications/reports/models.py
  src/etools/applications/t2f/migrations/0001_initial.py
  src/etools/applications/t2f/models.py
  src/etools/applications/t2f/tests/test_exports.py
  src/etools/applications/users/migrations/0016_country_custom_dashboards.py
  src/etools/applications/users/migrations/0017_merge_20210805_1609.py
  src/etools/applications/users/models.py
  src/etools/config/settings/base.py
  src/etools/libraries/djangolib/tests/utils.py
  tox.ini
Labels: READY

#3051 [ch26389] fix fr sync
  src/etools/applications/funds/migrations/0012_alter_fundsreservationitem_line_item_text.py
  src/etools/applications/funds/models.py
Labels: READY

#3061 [ePD] Possibility to filter list by Budget Owner
  src/etools/applications/partners/tests/test_v3_interventions.py
  src/etools/applications/partners/views/interventions_v2.py
Labels: READY, ePD

#3060 [ePD] Fix json migrations
  src/etools/applications/partners/migrations/0081_auto_20210517_1039.py
  src/etools/applications/partners/models.py
Labels: READY, ePD

#3058 fix question target mixin
  src/etools/applications/field_monitoring/data_collection/migrations/0001_initial_20191113.py
  src/etools/applications/field_monitoring/planning/migrations/0001_initial_20191113.py
  src/etools/applications/field_monitoring/planning/models.py
Labels: READY

#3054 [ePD] Return empty actions list when intervention is cancelled
  src/etools/applications/partners/tests/test_v3_interventions.py
Labels: READY

#2901 [ePD] Error on PD Budget Export of PD list filtered only by Status
  src/etools/applications/partners/serializers/exports/interventions.py
  src/etools/applications/partners/tests/test_exports.py
Labels: READY, ePD

#2908 [ePD] Add CFEI Field to PD List Exports
  src/etools/applications/partners/exports_v2.py
  src/etools/applications/partners/serializers/exports/interventions.py
  src/etools/applications/partners/tests/test_export_intervention.py
  src/etools/applications/partners/tests/test_exports.py
  src/etools/applications/reports/tests/test_exports.py
  src/etools/applications/reports/views/v2.py
Labels: on hold, READY, ePD

#2934 [ePD] Rename PD/SSFA to PD/SPD where applicable
  src/etools/applications/action_points/export/renderers.py
  src/etools/applications/action_points/migrations/0014_auto_20210108_1634.py
  src/etools/applications/action_points/models.py
  src/etools/applications/action_points/serializers.py
  src/etools/applications/attachments/management/commands/init-attachment-file-types.py
  src/etools/applications/audit/serializers/engagement.py
  src/etools/applications/core/data/attachments_file_types.json
  src/etools/applications/field_monitoring/fm_settings/migrations/0008_auto_20210108_1634.py
  src/etools/applications/field_monitoring/fm_settings/models.py
  src/etools/applications/field_monitoring/planning/activity_validation/validations/basic.py
  src/etools/applications/field_monitoring/planning/activity_validation/validations/state.py
  src/etools/applications/field_monitoring/planning/migrations/0008_auto_20210108_1634.py
  src/etools/applications/field_monitoring/planning/models.py
  src/etools/applications/field_monitoring/planning/serializers.py
  src/etools/applications/funds/tests/test_views.py
  src/etools/applications/funds/views.py
  src/etools/applications/partners/exports_v2.py
  src/etools/applications/partners/migrations/0078_auto_20210108_1634.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/notifications/intervention-draft.py
  src/etools/applications/partners/notifications/intervention-past-start.py
  src/etools/applications/partners/notifications/partnership-created-updated.py
  src/etools/applications/partners/notifications/partnership-signed-frs.py
  src/etools/applications/partners/serializers/exports/interventions.py
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/tests/test_export_intervention.py
  src/etools/applications/partners/tests/test_exports.py
  src/etools/applications/partners/utils.py
  src/etools/applications/partners/validation/interventions.py
  src/etools/applications/reports/exports.py
  src/etools/applications/reports/serializers/v2.py
  src/etools/applications/reports/tests/test_serializers.py
  src/etools/applications/tpm/export/renderers.py
  src/etools/applications/tpm/notifications/visit-action_point_assigned.py
  src/etools/applications/tpm/notifications/visit-approve_report.py
  src/etools/applications/tpm/notifications/visit-approve_report_tpm.py
  src/etools/applications/tpm/notifications/visit-assign.py
  src/etools/applications/tpm/notifications/visit-report.py
  src/etools/applications/tpm/notifications/visit-report_rejected.py
  src/etools/applications/tpm/serializers/visit.py
Labels: READY, ePD

#3029 Update partner_organization_v2.py
  src/etools/applications/partners/views/partner_organization_v2.py
Labels: READY

#2659 fix hact dumps
  src/etools/applications/hact/management/commands/freeze_hact_data.py
  src/etools/applications/hact/migrations/0001_initial.py
  src/etools/applications/hact/models.py
  src/etools/applications/partners/migrations/0001_initial.py
  src/etools/applications/partners/migrations/0041_auto_20191209_2039.py
  src/etools/applications/partners/models.py
Labels: READY

#3057 update jwt library
  Pipfile
  Pipfile.lock
  src/etools/applications/core/auth.py
  src/etools/applications/core/permissions.py
  src/etools/applications/core/simplejwt.py
  src/etools/applications/core/views.py
  src/etools/config/settings/base.py
  src/etools/config/settings/production.py
  src/etools/config/urls.py
Labels: READY

#3067 [ePD] fix tests
  src/etools/applications/partners/tests/test_exports.py
Labels: READY

#3068 leeway part 2
  Pipfile
  Pipfile.lock
  src/etools/applications/core/simplejwt.py
  src/etools/applications/core/views.py
  src/etools/config/settings/base.py
Labels: READY

#3047 Locations
  Pipfile
  Pipfile.lock
  src/etools/applications/management/views/gis_v1.py
  src/etools/applications/t2f/tests/test_exports.py
  src/etools/libraries/locations/admin.py
  src/etools/libraries/locations/exceptions.py
  src/etools/libraries/locations/task_utils.py
  src/etools/libraries/locations/tasks.py
  src/etools/libraries/locations/tests/test_tasks.py
  src/etools/libraries/locations/tests/test_views.py
  src/etools/templates/admin/location_remap.html
Labels: READY

#3066 [FAM] Update endpoints to support pagination, page_size and search
  src/etools/applications/partners/tests/test_views.py
  src/etools/applications/partners/views/partner_organization_v2.py
  src/etools/applications/users/tests/test_views_v3.py
  src/etools/applications/users/views_v3.py
  src/etools/applications/utils/pagination.py
Labels: READY

#3065 [FAM] On Engagement List an API is taking long to load
  src/etools/applications/audit/tests/test_views.py
  src/etools/applications/audit/views.py
Labels: READY

#2850 [ePD] Add PD list sent_to_partner filtering option
  src/etools/applications/partners/tests/test_v3_interventions.py
  src/etools/applications/partners/views/interventions_v2.py
  src/etools/applications/partners/views/interventions_v3.py
Labels: READY, ePD

#3062 [ePD] Update reference number for amended intervention
  src/etools/applications/partners/models.py
  src/etools/applications/partners/tests/test_amendments.py
  src/etools/applications/partners/tests/test_models.py
Labels: READY, ePD
