Repository unicef/etools, pull requests merged in 2021-03, with the labels that each got.

#2926 [FM] Geographic Coverage Map: colors are not updated according to colors legend for visited sites.
  src/etools/applications/field_monitoring/analyze/tests/test_views.py
  src/etools/applications/field_monitoring/analyze/views.py
  src/etools/libraries/djangolib/models.py
  src/etools/libraries/djangolib/tests/test_models.py
Labels: READY

#2952 sentry staging 2719 RAMSynchronizer fix
  src/etools/applications/reports/synchronizers.py
Labels: READY

#2951 [ch24679] PartnerPlannedVisits for 2022
  src/etools/applications/field_monitoring/analyze/serializers.py
  src/etools/applications/field_monitoring/analyze/tests/test_views.py
Labels: READY

#2949 fix pdf for invalid agreement
  src/etools/applications/partners/views/v1.py
Labels: READY

#2950 remove insight admin link
  src/etools/applications/users/admin.py
  src/etools/applications/users/templates/admin/users/country/change_form.html
Labels: READY

#2953 Sentry 1193
  src/etools/applications/management/views/general.py
Labels: READY, changes-requested, question

#2969 workspace api: add schema_name
  src/etools/applications/users/serializers.py
Labels: READY

#2968 [ch25163] amend ram sync
  src/etools/applications/reports/synchronizers.py
Labels: READY

#2966 [ch25159] action point fm filter
  src/etools/applications/action_points/filters.py
Labels: READY

#2965 [ch23935] overall planned visits
  src/etools/applications/field_monitoring/analyze/serializers.py
  src/etools/applications/field_monitoring/analyze/tests/test_views.py
Labels: READY

#2967 [ch25197] fix add_country command
  src/etools/applications/reports/migrations/0023_auto_20191014_1546.py
Labels: READY

#2971 [ch25270] FM Monitoring Activities: migrate single field office to multiple
  src/etools/applications/field_monitoring/planning/activity_validation/permissions_matrix.csv
  src/etools/applications/field_monitoring/planning/filters.py
  src/etools/applications/field_monitoring/planning/migrations/0008_monitoringactivity_offices.py
  src/etools/applications/field_monitoring/planning/migrations/0009_auto_20210318_2046.py
  src/etools/applications/field_monitoring/planning/models.py
  src/etools/applications/field_monitoring/planning/serializers.py
  src/etools/applications/field_monitoring/planning/tests/factories.py
  src/etools/applications/field_monitoring/planning/tests/test_views.py
Labels: READY

#2970 [ch15114] psea assessment: added sea_risk_rating filter
  src/etools/applications/psea/views.py
Labels: READY

#2962 [ch25121] notify email when import is completed
  src/etools/applications/core/notifications/import_complete.py
  src/etools/libraries/locations/admin.py
  src/etools/libraries/locations/tasks.py
Labels: READY

#2958 [ch25032] fam admin
  src/etools/applications/audit/admin.py
Labels: READY, question

#2955 [ch18003] amend partner export
  src/etools/applications/partners/exports_v2.py
  src/etools/applications/partners/serializers/exports/partner_organization.py
  src/etools/applications/partners/tests/test_export_partner.py
  src/etools/applications/partners/tests/test_exports.py
Labels: READY

#2946 sentry staging 1256
  src/etools/libraries/azure_graph_api/utils.py
Labels: READY, question

#2928 Correct default_ordering list for available actions
  src/etools/applications/partners/serializers/interventions_v3.py
  src/etools/applications/partners/tests/test_v3_serializers_intervention.py
Labels: READY

#2973 fix migration
  src/etools/applications/field_monitoring/planning/migrations/0009_auto_20210318_2046.py
Labels: READY
