Repository unicef/etools, pull requests merged in 2022-04, with the labels that each got.

#3241 Trips rob tweaks2
  src/etools/applications/field_monitoring/fm_settings/models.py
  src/etools/applications/travel/migrations/0007_auto_20220405_0916.py
  src/etools/applications/travel/models.py
  src/etools/applications/travel/permission_matrix/trip_permissions.csv
  src/etools/applications/travel/views.py
Labels: READY

#3245 [ch28881] Trips: delete endpoint for draft trips only
  src/etools/applications/travel/tests/test_views.py
  src/etools/applications/travel/views.py
Labels: READY

#3236 update docker base image
  Dockerfile
Labels: READY

#3247 revert base image
  Dockerfile
Labels: READY

#3231 [ ePD][ch28911] new endpoint: /api/pmp/v3/interventions/<id>/results-structure/
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/serializers/interventions_v3.py
  src/etools/applications/partners/tests/test_v3_intervention_results_structure.py
  src/etools/applications/partners/urls_v3.py
  src/etools/applications/partners/views/interventions_v3.py
  src/etools/applications/reports/serializers/v2.py
Labels: READY

#3252 Trips list: add delete permission
  src/etools/applications/travel/serializers.py
  src/etools/applications/travel/tests/test_views.py
Labels: READY

#3250 [ePD] Add new field called "Confidential" on the PD
  src/etools/applications/partners/migrations/0097_intervention_confidential.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/permission_matrix/intervention_permissions.csv
  src/etools/applications/partners/serializers/interventions_v3.py
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/tests/test_export_intervention.py
  src/etools/applications/partners/tests/test_v3_interventions.py
Labels: READY

#3249 [ch28518] Trips: list search and filters
  src/etools/applications/travel/filters.py
  src/etools/applications/travel/tests/test_views.py
  src/etools/applications/travel/views.py
Labels: READY

#3248 [ch28905]Trips: Add new action to skip supervisor approval
  src/etools/applications/travel/models.py
  src/etools/applications/travel/serializers.py
  src/etools/applications/travel/tests/test_serializers.py
  src/etools/applications/travel/tests/test_views.py
  src/etools/applications/travel/views.py
Labels: READY

#3073 [ePD] Merge pds expiration and transfering to active cp
  src/etools/applications/core/data/enabled_celery_tasks.json
  src/etools/applications/partners/tasks.py
Labels: READY, ePD

#3136 [ePD] Allow indicator title being edited
  src/etools/applications/partners/models.py
  src/etools/applications/partners/tests/test_amendments.py
  src/etools/applications/partners/tests/test_v3_interventions.py
  src/etools/applications/reports/models.py
  src/etools/applications/reports/serializers/v2.py
  src/etools/applications/reports/tests/test_models.py
  src/etools/applications/reports/tests/test_serializers.py
Labels: READY, ePD

#3148 [ePD] Amendments: Sites added in Geographical Coverage in amendment mode are not showed as Difference in Amendment details
  src/etools/applications/partners/permission_matrix/intervention_permissions.csv
  src/etools/applications/partners/tests/test_api_amendments.py
Labels: READY, ePD

#3185 [ePD] Terminate action should not break due to validation on quarters and activities.
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/tests/test_v3_interventions.py
Labels: READY, ePD

#3213 [ch28499] fix attachments filetype group
  src/etools/applications/audit/tests/test_transitions.py
  src/etools/applications/audit/utils.py
  src/etools/applications/core/data/attachments_file_types.json
  src/etools/applications/partners/utils.py
Labels: READY

#3227 [ch28785] flat attachments for FAM and PSEA
  src/etools/applications/attachments/tests/test_views.py
  src/etools/applications/attachments/utils.py
Labels: READY

#3228 [ch28830] Admin integrity err on total_value and exchange_rate blank
  src/etools/applications/audit/models.py
Labels: READY

#3234 FM: Single export visit
  src/etools/applications/field_monitoring/data_collection/admin.py
  src/etools/applications/field_monitoring/data_collection/models.py
  src/etools/applications/field_monitoring/data_collection/tests/factories.py
  src/etools/applications/field_monitoring/planning/models.py
  src/etools/applications/field_monitoring/planning/templates/fm/visit_pdf.html
  src/etools/applications/field_monitoring/planning/tests/test_models.py
  src/etools/applications/field_monitoring/planning/tests/test_views.py
  src/etools/applications/field_monitoring/planning/views.py
  src/etools/assets/images/UNICEF_logo_with_text_white.png
Labels: READY

#3244 [ch28879]Trips: Updating activity from Monitoring Activity to other type cleans up the monitoring activity
  src/etools/applications/travel/tests/test_views.py
  src/etools/applications/travel/views.py
Labels: READY

#3242 [ch28880]Trips: Supervisor, Description, Office and Section not mandatory in Draft
  src/etools/applications/travel/migrations/0008_fields_not_mandatory_in_draft.py
  src/etools/applications/travel/models.py
  src/etools/applications/travel/permission_matrix/trip_permissions.csv
  src/etools/applications/travel/tests/test_views.py
Labels: READY

#3243 [ch28908]Trips: exclude Submitted from status_list when travel has status "Approved"
  src/etools/applications/travel/serializers.py
Labels: question

#3251 [ePD] Auto numbering for Activity Items
  src/etools/applications/reports/migrations/0041_interventionactivityitem_code.py
  src/etools/applications/reports/migrations/0042_auto_20220408_1104.py
  src/etools/applications/reports/models.py
  src/etools/applications/reports/serializers/v2.py
  src/etools/applications/reports/signals.py
  src/etools/applications/reports/tests/test_models.py
Labels: READY, ePD

#3200 [ePD] save related models to intervention snapshot
  src/etools/applications/partners/amendment_utils.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/serializers/intervention_snapshot.py
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/serializers/interventions_v3.py
  src/etools/applications/partners/serializers/v3.py
  src/etools/applications/partners/tests/test_prc_review.py
  src/etools/applications/partners/tests/test_serializers_intervention.py
  src/etools/applications/partners/tests/test_v3_intervention_lower_results.py
  src/etools/applications/partners/tests/test_v3_interventions.py
  src/etools/applications/partners/views/interventions_v2.py
  src/etools/applications/partners/views/interventions_v3.py
  src/etools/applications/reports/serializers/v2.py
Labels: READY, ePD

#3235 [ePD] Validations to be confirmed or developed on partner or unicef accept
  src/etools/applications/partners/permission_matrix/intervention_permissions.csv
  src/etools/applications/partners/permissions.py
  src/etools/applications/partners/tests/factories.py
  src/etools/applications/partners/tests/test_api_amendments.py
  src/etools/applications/partners/tests/test_api_interventions.py
  src/etools/applications/partners/tests/test_epd_management/base.py
  src/etools/applications/partners/tests/test_v3_interventions.py
  src/etools/applications/partners/validation/interventions.py
Labels: READY, ePD

#3260 Trips: Added edit permissions for office and section in draft status
  src/etools/applications/travel/permission_matrix/trip_permissions.csv
Labels: READY

#3258 [ch29084] Added comma before country in pca templates
  src/etools/applications/partners/templates/pca/arabic_pdf.html
  src/etools/applications/partners/templates/pca/english_pdf.html
  src/etools/applications/partners/templates/pca/french_pdf.html
  src/etools/applications/partners/templates/pca/portuguese_pdf.html
  src/etools/applications/partners/templates/pca/russian_pdf.html
  src/etools/applications/partners/templates/pca/spanish_pdf.html
Labels: READY

#3238 Trips: email fixes
  src/etools/applications/travel/models.py
  src/etools/applications/travel/notifications/trip-approved.py
  src/etools/applications/travel/notifications/trip-rejected.py
  src/etools/applications/travel/notifications/trip-submitted.py
  src/etools/applications/travel/notifications/trip-subreview.py
  src/etools/applications/travel/tests/test_models.py
Labels: READY

#3265 locations tweaks 4.0.1
  Pipfile
  Pipfile.lock
Labels: READY

#3266 [ch29094] FAM: replace unique_id with reference_number
  src/etools/applications/audit/filters.py
  src/etools/applications/audit/models.py
  src/etools/applications/audit/notifications/engagement-reported_by_auditor.py
  src/etools/applications/audit/serializers/engagement.py
Labels: READY

#3267 tweak attachment admin
  src/etools/applications/attachments/admin.py
Labels: READY

#3237 [ch28836] export csv
  src/etools/applications/partners/tests/test_export_partner.py
  src/etools/applications/partners/tests/test_exports.py
  src/etools/applications/partners/views/partner_organization_v2.py
Labels: READY

#3268 [ch29167]FAM: replace model clean method with migration
  src/etools/applications/audit/migrations/0023_auto_20220415_1130.py
  src/etools/applications/audit/models.py
Labels: READY

#3272 [ePD] Fixes from testing
  src/etools/applications/partners/amendment_utils.py
  src/etools/applications/partners/migrations/0098_auto_20220426_1123.py
  src/etools/applications/partners/migrations/0099_auto_20220426_1131.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/permissions.py
  src/etools/applications/partners/tests/test_amendments.py
  src/etools/applications/partners/tests/test_api_amendments.py
  src/etools/applications/partners/tests/test_v3_interventions.py
  src/etools/config/settings/base.py
Labels: READY, ePD
