Repository unicef/etools, pull requests merged in 2022-05, with the labels that each got.

#3273 [ePD] Confidential field is supposed to be boolean
  src/etools/applications/partners/migrations/0100_alter_intervention_confidential.py
  src/etools/applications/partners/models.py
Labels: READY, ePD

#3276 [ePD] Hierarchy code for PD Output after post creation assignment to CP Output
  src/etools/applications/partners/models.py
  src/etools/applications/partners/serializers/v3.py
  src/etools/applications/partners/tests/test_v3_intervention_activity.py
  src/etools/applications/partners/tests/test_v3_intervention_lower_results.py
  src/etools/applications/reports/models.py
Labels: READY, ePD

#3275 [ch29091] ePD: admin partner staff members search error
  src/etools/applications/partners/admin.py
Labels: READY

#3280 Hierarchy code for PD Output after post creation assignment to CP Output #2
  src/etools/applications/partners/models.py
  src/etools/applications/partners/serializers/v3.py
  src/etools/applications/partners/tests/test_v3_intervention_lower_results.py
  src/etools/applications/reports/models.py
Labels: READY, ePD

#3284 [ch29624] ePD: add activation_protocol to InterventionAdmin
  src/etools/applications/partners/admin.py
Labels: READY, ePD

#3278 [ch29189] ePD: Remove SSFA reference from error messages
  src/etools/applications/partners/tests/test_serializers.py
  src/etools/applications/partners/validation/agreements.py
Labels: READY, ePD

#3285 [ch29621] ePD: creating partner staff member has user with wrong last name
  src/etools/applications/partners/serializers/partner_organization_v2.py
  src/etools/applications/partners/tests/test_api_partners.py
Labels: READY, ePD

#3286 [ch29622] ePD: PRC secretary send back and sent for review malformed email url
  src/etools/applications/partners/models.py
  src/etools/applications/partners/notifications/intervention-prc_review_sent_back.py
  src/etools/applications/partners/views/interventions_v3_actions.py
Labels: READY, ePD

#3287 [ch29623] ePD: PD in signed state cannot edit start/end date and HQ contrib
  src/etools/applications/partners/permission_matrix/intervention_permissions.csv
  src/etools/applications/partners/tests/test_epd_management/base.py
  src/etools/applications/partners/tests/test_epd_management/test_signed_documents.py
Labels: READY, ePD

#3295 [ePD] Fix lower results auto numbering IntergityError in migrations
  src/etools/applications/reports/migrations/0039_auto_20220222_1135.py
  src/etools/applications/reports/migrations/0043_auto_20220510_0717.py
Labels: bug, READY, ePD

#3293 [ch29669] t2f: T2FActionPointAdmin status is readonly so that direct modification is not allowed
  src/etools/applications/t2f/admin.py
Labels: READY

#3298 [Develop] Auto-transitions to active (via task) for PDs in the future do not work as expected.
  src/etools/applications/partners/tasks.py
  src/etools/applications/partners/tests/test_tasks.py
Labels: READY

#3302 [ch29943] ePD: added total_supply field for unicef + partner supplies total
  src/etools/applications/partners/models.py
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/tests/test_models.py
  src/etools/applications/partners/tests/test_v3_interventions.py
Labels: READY

#3303 [ch29797] ePD Editor: fix for activity item index not updated on cp assign
  src/etools/applications/partners/serializers/v3.py
  src/etools/applications/partners/tests/test_v3_intervention_lower_results.py
Labels: READY

#3306 [ch29637] ePD supply table upload fails
  src/etools/applications/partners/serializers/interventions_v3.py
  src/etools/applications/partners/tests/test_v3_interventions.py
  src/etools/applications/partners/views/interventions_v3.py
Labels: READY, ePD
