Repository unicef/etools, pull requests merged in 2023-05, with the labels that each got.

#3481 [ch33318] Post ePD: deploy title word limit
  src/etools/applications/partners/migrations/0113_alter_intervention_title.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/permission_matrix/intervention_permissions.csv
  src/etools/applications/partners/permissions.py
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/tests/test_tasks.py
  src/etools/applications/partners/tests/test_v3_interventions.py
Labels: READY

#3483 [ch33553] Excel export error
  src/etools/applications/partners/exports_v2.py
Labels: READY

#3484 Post ePD deploy - Amendment merge
  src/etools/applications/partners/permissions.py
  src/etools/applications/partners/tests/test_api_amendments.py
  src/etools/applications/partners/views/interventions_v3_actions.py
Labels: WIP

#3486 AMP: PME and UNICEF Audit Focal Point permissions
  src/etools/applications/users/permissions.py
  src/etools/applications/users/tests/test_views_v3.py
  src/etools/applications/users/views_v3.py
Labels: READY

#3480 [ch33759] AMP Sentry fixes
  src/etools/applications/hact/tasks.py
  src/etools/applications/hact/tests/test_tasks.py
  src/etools/applications/partners/synchronizers.py
  src/etools/applications/partners/tasks.py
  src/etools/applications/partners/tests/test_prp_sync.py
  src/etools/applications/tpm/tpmpartners/synchronizers.py
  src/etools/applications/travel/tests/test_views.py
Labels: READY

#3497 Fixes for has_active_realm to be in current context
  src/etools/applications/partners/models.py
  src/etools/applications/partners/tests/test_export_partner.py
  src/etools/applications/partners/tests/test_v3_interventions.py
  src/etools/applications/partners/tests/test_v3_partner_organizations.py
  src/etools/applications/partners/tests/test_views.py
  src/etools/applications/partners/urls_v2.py
  src/etools/applications/partners/views/partner_organization_v2.py
  src/etools/applications/partners/views/partner_organization_v3.py
  src/etools/applications/partners/views/v3.py
  src/etools/applications/tpm/views.py
  src/etools/applications/users/admin.py
  src/etools/applications/users/filters.py
  src/etools/applications/users/tests/test_views_v3.py
  src/etools/applications/users/views_v3.py
Labels: READY

#3496 [FAM] Change Micro Assessment Questionnaire
  src/etools/applications/audit/exports.py
  src/etools/applications/audit/migrations/0028_auto_20230515_0551.py
  src/etools/applications/audit/models.py
  src/etools/applications/audit/serializers/engagement.py
  src/etools/applications/audit/serializers/export.py
  src/etools/applications/audit/serializers/risks.py
  src/etools/applications/audit/tests/test_transitions.py
  src/etools/applications/audit/tests/test_views.py
  src/etools/applications/audit/transitions/conditions.py
  src/etools/applications/core/data/audit_risks_blueprints.json
Labels: READY

#3502 [ch33972] Fix translation for FACE
  src/etools/applications/partners/locale/ar/LC_MESSAGES/django.mo
  src/etools/applications/partners/locale/ar/LC_MESSAGES/django.po
  src/etools/applications/partners/locale/es/LC_MESSAGES/django.mo
  src/etools/applications/partners/locale/es/LC_MESSAGES/django.po
  src/etools/applications/partners/locale/fr/LC_MESSAGES/django.mo
  src/etools/applications/partners/locale/fr/LC_MESSAGES/django.po
  src/etools/applications/partners/locale/pt/LC_MESSAGES/django.mo
  src/etools/applications/partners/locale/pt/LC_MESSAGES/django.po
  src/etools/applications/partners/locale/ru/LC_MESSAGES/django.mo
  src/etools/applications/partners/locale/ru/LC_MESSAGES/django.po
Labels: READY

#3501 [ch33860] AMP: audit staff-members label missing
  src/etools/applications/audit/serializers/engagement.py
  src/etools/applications/audit/tests/test_views.py
Labels: READY

#3500 [ch33870] AMP: added tpm staff member not displayed
  src/etools/applications/field_monitoring/planning/filters.py
  src/etools/applications/field_monitoring/planning/serializers.py
  src/etools/applications/field_monitoring/planning/tests/test_views.py
  src/etools/applications/field_monitoring/planning/views.py
  src/etools/applications/partners/tasks.py
Labels: READY

#3505 [ch33998] consider has_active_realm in field-monitoring/planning/users/ logic
  src/etools/applications/audit/views.py
  src/etools/applications/field_monitoring/planning/serializers.py
  src/etools/applications/field_monitoring/planning/views.py
  src/etools/applications/users/migrations/0023_alter_user_managers.py
  src/etools/applications/users/models.py
Labels: READY

#3513 [FM] Action Points to be hidden for the TPM user
  src/etools/applications/field_monitoring/planning/activity_validation/permissions_matrix.csv
Labels: READY

#3511 [ch34085] replace Inoperative with No Access for partner staff user status
  src/etools/applications/field_monitoring/planning/activity_validation/validations/basic.py
  src/etools/applications/field_monitoring/planning/locale/ar/LC_MESSAGES/django.mo
  src/etools/applications/field_monitoring/planning/locale/ar/LC_MESSAGES/django.po
  src/etools/applications/field_monitoring/planning/locale/es/LC_MESSAGES/django.mo
  src/etools/applications/field_monitoring/planning/locale/es/LC_MESSAGES/django.po
  src/etools/applications/field_monitoring/planning/locale/fr/LC_MESSAGES/django.mo
  src/etools/applications/field_monitoring/planning/locale/fr/LC_MESSAGES/django.po
  src/etools/applications/field_monitoring/planning/locale/pt/LC_MESSAGES/django.mo
  src/etools/applications/field_monitoring/planning/locale/pt/LC_MESSAGES/django.po
  src/etools/applications/field_monitoring/planning/locale/ru/LC_MESSAGES/django.mo
  src/etools/applications/field_monitoring/planning/locale/ru/LC_MESSAGES/django.po
  src/etools/applications/field_monitoring/planning/serializers.py
  src/etools/applications/field_monitoring/planning/tests/test_views.py
  src/etools/applications/users/filters.py
Labels: question

#3507 [FAM] Audit Staff Teams Members permissions for editing cleanup
  src/etools/applications/audit/management/commands/update_audit_permissions.py
Labels: READY

#3506 [PMP] Programmatic Visits: A specific Site is saved only on one timeframe quarter/year
  src/etools/applications/partners/serializers/interventions_v2.py
  src/etools/applications/partners/tests/test_epd_management/test_programmatic_visits.py
Labels: READY

#3499 [FAM] Year of audit - display actual year instead of '>1 year ago'
  src/etools/applications/audit/admin.py
  src/etools/applications/audit/migrations/0028_audit_year_of_audit_recalculate.py
  src/etools/applications/audit/migrations/0029_merge_20230523_1049.py
Labels: READY
