Repository unicef/etools, pull requests merged in 2024-08, with the labels that each got.

#3734 [PMP] To change the logic of the system to NOT calculate the planned PVs for canceled PDs
  src/etools/applications/partners/models.py
  src/etools/applications/partners/tests/test_models.py
Labels: READY

#3738 [Develop] unicef-attachments issue on upload
  src/etools/libraries/azure_storage_backend.py
Labels: READY

#3742 [ch37461] AMP: allow external users to update their job descriptions
  src/etools/applications/users/serializers_v3.py
  src/etools/applications/users/tests/test_views_v3.py
Labels: question

#3741 [FM] Remote monitoring radio button
  src/etools/applications/field_monitoring/planning/activity_validation/permissions_matrix.csv
  src/etools/applications/field_monitoring/planning/locale/ar/LC_MESSAGES/django.po
  src/etools/applications/field_monitoring/planning/locale/es/LC_MESSAGES/django.po
  src/etools/applications/field_monitoring/planning/locale/fr/LC_MESSAGES/django.po
  src/etools/applications/field_monitoring/planning/locale/pt/LC_MESSAGES/django.po
  src/etools/applications/field_monitoring/planning/locale/ru/LC_MESSAGES/django.po
  src/etools/applications/field_monitoring/planning/migrations/0004_monitoringactivity_remote_monitoring.py
  src/etools/applications/field_monitoring/planning/models.py
  src/etools/applications/field_monitoring/planning/serializers.py
  src/etools/applications/field_monitoring/planning/tests/test_views.py
Labels: READY

#3735 [PMP] Request a change that only the PRC secretary role can cancel the PD
  src/etools/applications/partners/locale/ar/LC_MESSAGES/django.po
  src/etools/applications/partners/locale/es/LC_MESSAGES/django.po
  src/etools/applications/partners/locale/fr/LC_MESSAGES/django.po
  src/etools/applications/partners/locale/pt/LC_MESSAGES/django.po
  src/etools/applications/partners/locale/ru/LC_MESSAGES/django.po
  src/etools/applications/partners/serializers/interventions_v3.py
  src/etools/applications/partners/tests/test_v3_interventions.py
  src/etools/applications/partners/tests/test_v3_serializers_intervention.py
  src/etools/applications/partners/views/interventions_v3_actions.py
Labels: READY

#3722 [FM] Export for visits page
  src/etools/applications/field_monitoring/planning/export/__init__.py
  src/etools/applications/field_monitoring/planning/export/renderers.py
  src/etools/applications/field_monitoring/planning/export/serializers.py
  src/etools/applications/field_monitoring/planning/locale/ar/LC_MESSAGES/django.po
  src/etools/applications/field_monitoring/planning/locale/es/LC_MESSAGES/django.po
  src/etools/applications/field_monitoring/planning/locale/fr/LC_MESSAGES/django.po
  src/etools/applications/field_monitoring/planning/locale/pt/LC_MESSAGES/django.po
  src/etools/applications/field_monitoring/planning/locale/ru/LC_MESSAGES/django.po
  src/etools/applications/field_monitoring/planning/tests/test_views.py
  src/etools/applications/field_monitoring/planning/views.py
Labels: changes-requested
