Repository unicef/etools, pull requests merged in 2024-06, with the labels that each got.

#3666 [FM] Use try and except / move on when sending forms to OLC and it is down. Send exception to sentry
  src/etools/applications/field_monitoring/data_collection/locale/ar/LC_MESSAGES/django.po
  src/etools/applications/field_monitoring/data_collection/locale/es/LC_MESSAGES/django.po
  src/etools/applications/field_monitoring/data_collection/locale/fr/LC_MESSAGES/django.po
  src/etools/applications/field_monitoring/data_collection/locale/pt/LC_MESSAGES/django.po
  src/etools/applications/field_monitoring/data_collection/locale/ru/LC_MESSAGES/django.po
  src/etools/applications/field_monitoring/data_collection/tests/test_offline.py
  src/etools/applications/field_monitoring/data_collection/views.py
  src/etools/applications/offline/fields/files.py
  src/etools/applications/offline/tests/test_fields.py
Labels: enhancement, READY

#3673 [PMP] Supply list upload: Successful upload for inappropriate list
  src/etools/applications/partners/locale/ar/LC_MESSAGES/django.po
  src/etools/applications/partners/locale/es/LC_MESSAGES/django.po
  src/etools/applications/partners/locale/fr/LC_MESSAGES/django.po
  src/etools/applications/partners/locale/pt/LC_MESSAGES/django.po
  src/etools/applications/partners/locale/ru/LC_MESSAGES/django.po
  src/etools/applications/partners/tests/test_v3_interventions.py
  src/etools/applications/partners/views/interventions_v3.py
Labels: enhancement, READY, ePD

#3624 [ch35934] New Notification to UNICEF Focal persons
  src/etools/applications/core/management/commands/init-celery.py
  src/etools/applications/partners/notifications/expiring_partner.py
  src/etools/applications/partners/tasks.py
  src/etools/applications/partners/tests/test_tasks.py
Labels: READY

#3667 [ch37072] PMP: prevent adding duplicated name disaggregation
  src/etools/applications/reports/models.py
  src/etools/applications/reports/serializers/v2.py
  src/etools/applications/reports/tests/test_views.py
Labels: READY

#3674 [Dashboard] I can still Export with indirect access
  src/etools/applications/partners/exports_v2.py
  src/etools/applications/partners/locale/ar/LC_MESSAGES/django.po
  src/etools/applications/partners/locale/es/LC_MESSAGES/django.po
  src/etools/applications/partners/locale/fr/LC_MESSAGES/django.po
  src/etools/applications/partners/locale/pt/LC_MESSAGES/django.po
  src/etools/applications/partners/locale/ru/LC_MESSAGES/django.po
  src/etools/applications/partners/serializers/partner_organization_v2.py
  src/etools/applications/partners/tests/test_api_partners.py
  src/etools/applications/partners/tests/test_export_partner.py
  src/etools/applications/partners/tests/test_views.py
  src/etools/applications/partners/urls_v2.py
  src/etools/applications/partners/views/partner_organization_v2.py
Labels: READY

#3660 [FAM] Face Report Dates add to Spot Checks
  src/etools/applications/audit/management/commands/update_audit_permissions.py
  src/etools/applications/audit/migrations/0031_auto_20240507_1059.py
  src/etools/applications/audit/models.py
  src/etools/applications/audit/serializers/engagement.py
Labels: READY

#3683 [ch36049] FAM: validation on financial Findings local currency
  src/etools/applications/audit/serializers/engagement.py
  src/etools/applications/audit/tests/test_views.py
Labels: READY

#3685 [ch29971] Admin agreements: add-the-ability-to-revert-a-terminated-pca
  src/etools/applications/partners/admin.py
  src/etools/applications/partners/locale/ar/LC_MESSAGES/django.po
  src/etools/applications/partners/locale/es/LC_MESSAGES/django.po
  src/etools/applications/partners/locale/fr/LC_MESSAGES/django.po
  src/etools/applications/partners/locale/pt/LC_MESSAGES/django.po
  src/etools/applications/partners/locale/ru/LC_MESSAGES/django.po
  src/etools/applications/partners/tests/test_admin.py
Labels: READY

#3638 [Develop] Revised PD title not showing after PD amendment merge
  src/etools/applications/partners/amendment_utils.py
  src/etools/applications/partners/models.py
  src/etools/applications/partners/tests/test_amendments.py
Labels: enhancement, READY

#3689 LMSM - Sort by expiry date in Checkout
  src/etools/applications/last_mile/migrations/0004_alter_item_options.py
  src/etools/applications/last_mile/models.py
  src/etools/applications/last_mile/tests/test_views.py
Labels: READY

#3690 LMSM - Make Location Mandatory during checkout
  src/etools/applications/last_mile/serializers.py
  src/etools/applications/last_mile/tests/test_views.py
Labels: READY

#3695 [ch37444] LMSM - Doc upload mandatory for wastage
  src/etools/applications/last_mile/serializers.py
  src/etools/applications/last_mile/tests/test_views.py
Labels: READY

#3698 [FIX] Missing audit migration
  runtests.sh
  src/etools/applications/audit/migrations/0032_auto_20240613_1204.py
Labels: READY
